/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface (null) (ToDoAlarmsDelegate)
- (void)toDoAlarms:(id)arg1 alarmAdded:(id)arg2;
- (void)toDoAlarms:(id)arg1 alarmRemoved:(id)arg2;
- (void)toDoAlarms:(id)arg1 alarmUpdated:(id)arg2;
@end

