/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface (null) (Convenience)
- (unsigned long long)highestIndexOfObject:(id)arg1 inRange:(struct _NSRange)arg2;
- (BOOL)insertObjectIfAbsent:(id)arg1 usingSortFunction:(void *)arg2 context:(void *)arg3;
- (void)addAbsentObjectsFromArray:(id)arg1;
- (BOOL)addObjectIfAbsent:(id)arg1;
- (BOOL)addObjectIfAbsentAccordingToEquals:(id)arg1;
- (void)addObjectsFromSet:(id)arg1;
- (void)removeObjectsFromSet:(id)arg1;
@end

