/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface (null) (FontAdditions)
+ (void)resetHeaderAttributes;
+ (id)boldHeaderAttributes;
+ (id)boldGrayHeaderAttributes;
+ (id)bigBoldWhiteHeaderAttributes;
+ (id)mediumWhiteHeaderAttributes;
+ (id)blueHeaderAttributes;
+ (id)headerAttributes;
+ (id)fixedPitchAttributes;
+ (double)headerFontSize;
@end

