/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class IMAPAccount, NSArray;

@interface _IMAPMailboxDeletionQueueEntry
{
    NSArray *urls;
    NSArray *paths;
    IMAPAccount *account;
}

@property(retain) IMAPAccount *account; // @synthesize account;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"IMAPAccount",&,N,Vaccount,P

@property(retain) NSArray *paths; // @synthesize paths;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"NSArray",&,N,Vpaths,P

@property(retain) NSArray *urls; // @synthesize urls;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"NSArray",&,N,Vurls,P


- (void)dealloc;
- (id)account;
- (void)setAccount:(id)arg1;
- (id)paths;
- (void)setPaths:(id)arg1;
- (id)urls;
- (void)setUrls:(id)arg1;

@end

