/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "MessageConsumer-Protocol.h"

@class InvocationQueue;

@interface _LibraryStoreMessageConsumer <MessageConsumer>
{
    id _libraryStore;
    InvocationQueue *_callbackQueue;
    BOOL _addCountsForMessages;
}

@property BOOL addCountsForMessages; // @synthesize addCountsForMessages=_addCountsForMessages;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,V_addCountsForMessages


- (id)initWithLibraryStore:(id)arg1 useCallbackQueue:(BOOL)arg2;
- (void)dealloc;
- (void)newMessagesAvailable:(id)arg1;
- (void)newMessagesAvailable:(id)arg1 ranks:(id)arg2;
- (BOOL)shouldCancel;
- (void)libraryFinishedSendingMessages;
- (BOOL)addCountsForMessages;
- (void)setAddCountsForMessages:(BOOL)arg1;

@end

