/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface _MailboxUidChildrenEnumerator
{
    struct __CFTree *_root;
    struct __CFTree *_currentTree;
    BOOL _includeHidden;
}

- (id)initWithTree:(struct __CFTree *)arg1 includeHiddenChildren:(BOOL)arg2;
- (id)init;
- (void)dealloc;
- (id)nextObject;

@end

