/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

//#import <Message/_MFObjectLock.h>
#import <_MFObjectLock.h>

@interface _MFRecursiveLock : _MFObjectLock
{
    unsigned int requestedCount:16;
}

- (void)lock;
- (BOOL)tryLock;
- (void)unlockForObject:(id)fp8;
- (void)forceUnlockForObject:(id)fp8;
- (id)description;

@end

