/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSImageRep.h"

@interface _NSCGImageRep : NSImageRep
{
    struct CGImage *_cgImage;
}

+ (void)initialize;
- (id)init;
- (id)initWithCGImage:(struct CGImage *)fp8;
- (id)initWithFocusedViewRect:(struct _NSRect)fp8;
- (void)dealloc;
- (struct _NSRect)boundingBox;
- (struct CGImage *)CGImage;
- (BOOL)draw;
- (BOOL)drawAtPoint:(struct _NSPoint)fp8;
- (BOOL)drawInRect:(struct _NSRect)fp8;
- (BOOL)_isValid;
- (BOOL)_drawFromRect:(struct _NSRect)fp8 toRect:(struct _NSRect)fp24 operation:(int)fp40 alpha:(float)fp44 compositing:(BOOL)fp48 flipped:(BOOL)fp52 ignoreContext:(BOOL)fp56;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;

@end

