/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSArray, NSDictionary, NSMutableArray;

@interface _SetFlags
{
    NSDictionary *_flagsToSet;
    NSMutableArray *_messages;
}

@property(readonly) NSArray *messages; // @synthesize messages=_messages;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSArray",R,V_messages,P

@property(readonly) NSDictionary *flagsToSet; // @synthesize flagsToSet=_flagsToSet;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSDictionary",R,V_flagsToSet,P


- (id)initWithFlagsDictionary:(id)arg1 messages:(id)arg2;
- (id)init;
- (void)dealloc;
- (void)addMessages:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)messages;
- (id)flagsToSet;

@end

