/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "ABRecord.h"

@interface ABRecord (MailAdditions)
- (id)firstName;
- (id)lastName;
- (id)middleName;
- (id)extension;
- (id)_fullName;
- (id)email;
- (id)compoundName;
- (id)compoundNameAndEmail;
- (BOOL)isGroup;
@end

