/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/Account.h>

@interface Account (Applescript)
- (int)accountType;
- (void)setAccountPassword:(id)arg1;
- (id)accountPassword;
- (void)setServerName:(id)arg1;
- (id)serverName;
- (void)setLoginName:(id)arg1;
- (id)loginName;
- (void)setAccountName:(id)arg1;
- (id)accountName;
- (int)customAuthentication;
- (void)setCustomAuthentication:(int)arg1;
@end

