/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSMachPortDelegate-Protocol.h"

@class MFError, NSInvocation, NSMachPort, NSMutableSet, NSString, SafeValueCache;

@interface ActivityMonitor <NSMachPortDelegate>
{
    NSString *_itemDescription;
    NSString *_taskName;
    NSString *_statusMessage;
    NSString *_descriptionString;
    NSMutableSet *_subMonitors;
    NSInvocation *_cancelInvocation;
    NSMachPort *_cancelPort;
    SafeValueCache *_targetDisplayNameCache;
    MFError *_error;
    id _delegate;
    id _target;
    double _doneValue;
    double previousDoneness;
    double _itemValue;
    double _itemMinValue;
    double _itemMaxValue;
    double _startTime;
    double _itemLastNotifiedTime;
    double _percentDone;
    long long shouldUnifyDoneness;
    long long currentProgressStage;
    long long numberOfProgressStages;
    long long _key;
    unsigned long long _itemsDone;
    unsigned long long _itemsTotal;
    unsigned long long _itemFudgeFactor;
    int _changeCount;
    int _activityType;
    unsigned char _priority;
    BOOL _canCancel;
    BOOL _shouldCancel;
    BOOL _isActive;
    BOOL _isProgressing;
    BOOL _shouldPromptUserOnTermination;
}

@property BOOL canBeCancelled;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N

@property BOOL shouldCancel;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N

@property(retain) MFError *error; // @synthesize error=_error;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"MFError",&,V_error,P

@property double doneValue; // @synthesize doneValue=_doneValue;
@property double itemMaxValue; // @synthesize itemMaxValue=_itemMaxValue;
@property double itemMinValue; // @synthesize itemMinValue=_itemMinValue;
@property double itemValue; // @synthesize itemValue=_itemValue;
@property unsigned long long itemsTotal; // @synthesize itemsTotal=_itemsTotal;
@property unsigned long long itemsDone; // @synthesize itemsDone=_itemsDone;
@property BOOL isProgressing; // @synthesize isProgressing=_isProgressing;
@property(copy) NSString *itemDescription; // @synthesize itemDescription=_itemDescription;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,V_itemDescription,P

@property(retain) NSInvocation *cancelInvocation; // @synthesize cancelInvocation=_cancelInvocation;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSInvocation",&,V_cancelInvocation,P


+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (double)determinateProgress;
+ (void)setCurrentMonitor:(id)arg1;
+ (id)currentMonitor;
- (id)init;
- (void)dealloc;
- (BOOL)isActive;
- (void)setDelegate:(id)arg1;
- (void)postActivityStarting;
- (void)handlePortMessage:(id)arg1;
- (void)postActivityFinished;
- (void)_didChange;
- (int)changeCount;
- (void)setStatusMessage:(id)arg1;
- (void)setStatusMessage:(id)arg1 percentDone:(double)arg2;
- (id)statusMessage;
- (void)setPercentDone:(double)arg1;
- (double)percentDone;
- (double)unifiedFractionDone;
- (void)beginProgressFor:(long long)arg1;
- (unsigned char)priority;
- (void)setPriority:(unsigned char)arg1;
- (id)activityDescription;
- (id)_updatedTargetDisplayName:(id)arg1;
- (id)description;
- (id)taskName;
- (void)setTaskName:(id)arg1;
- (void)setActivityTarget:(id)arg1;
- (id)activityTarget;
- (void)addActivityTarget:(id)arg1;
- (void)removeActivityTarget:(id)arg1;
- (void)setPrimaryTarget:(id)arg1;
- (id)activityTargets;
- (BOOL)canBeCancelled;
- (void)setCanBeCancelled:(BOOL)arg1;
- (BOOL)shouldCancel;
- (void)setShouldCancel:(BOOL)arg1;
- (void)addSubMonitor:(id)arg1;
- (void)removeSubMonitor:(id)arg1;
- (void)cancel;
- (long long)acquireExclusiveAccessKey;
- (void)relinquishExclusiveAccessKey:(long long)arg1;
- (void)setStatusMessage:(id)arg1 percentDone:(double)arg2 withKey:(long long)arg3;
- (void)setStatusMessage:(id)arg1 withKey:(long long)arg2;
- (void)setPercentDone:(double)arg1 withKey:(long long)arg2;
- (void)_setCancelPort:(id)arg1;
- (id)cancelPort;
- (void)updateDoneValue;
- (void)setDoneValue:(double)arg1;
- (int)activityType;
- (void)setActivityType:(int)arg1;
- (void)setItemFudgeFactor:(unsigned long long)arg1;
- (void)setIsProgressing:(BOOL)arg1;
- (void)setItemMaxValue:(double)arg1;
- (void)setItemIndeterminateValue;
- (void)setItem:(id)arg1;
- (void)resetItemValue;
- (void)setItemValue:(double)arg1;
- (void)setItemsDone:(unsigned long long)arg1;
- (void)setItemsTotal:(unsigned long long)arg1;
- (void)incrementItemValue:(double)arg1;
- (void)incrementItemsDone:(unsigned long long)arg1;
- (void)incrementItemsTotal:(unsigned long long)arg1;
- (void)markCompleted:(BOOL)arg1;
- (void)resetActivityType;
- (BOOL)shouldPromptUserOnTermination;
- (void)setShouldPromptUserOnTermination;
- (id)error;
- (void)setError:(id)arg1;
- (double)doneValue;
- (double)itemMaxValue;
- (double)itemMinValue;
- (void)setItemMinValue:(double)arg1;
- (double)itemValue;
- (unsigned long long)itemsTotal;
- (unsigned long long)itemsDone;
- (BOOL)isProgressing;
- (id)itemDescription;
- (void)setItemDescription:(id)arg1;
- (id)cancelInvocation;
- (void)setCancelInvocation:(id)arg1;

@end

