/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/POP3Connection.h>

@interface APOPConnection : POP3Connection
{
}

- (BOOL)authenticateUsingAccount:(id)arg1;
- (int)_authenticateUsingHostname:(id)arg1 username:(id)arg2 password:(id)arg3 authenticator:(id)arg4;

@end

