/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface AuthScheme
{
}

+ (void)initialize;
+ (id)knownSchemes;
+ (void)registerSchemeClass:(Class)arg1;
+ (id)schemeWithName:(id)arg1;
+ (id)authSchemesForAccount:(id)arg1 connection:(id)arg2;
+ (id)schemeWithAccountInfo:(id)arg1;
- (id)retain;
- (unsigned long long)retainCount;
- (void)release;
- (id)autorelease;
- (Class)connectionClassForAccount:(id)arg1;
- (Class)authenticatorClassForAccount:(id)arg1;
- (BOOL)hasEncryption;
- (int)securityLevel;
- (BOOL)canAuthenticateAccount:(id)arg1 connection:(id)arg2;
- (id)authenticatorForAccount:(id)arg1 connection:(id)arg2;
- (BOOL)requiresPassword;
- (BOOL)requiresDomain;
- (id)name;
- (id)humanReadableName;
- (long long)compareBySecurityLevel:(id)arg1;

@end

