/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol CalendarStoreConduit <NSObject>
- (id)initWithToDosCache:(id)arg1 todoCalendars:(id)arg2;
- (void)initialSynchronization;
- (id)calTaskWithID:(id)arg1;
- (void)synchronize;
- (void)addToDo:(id)arg1;
- (void)saveToDo:(id)arg1;
- (void)removeToDo:(id)arg1;
- (void)addCalendar:(id)arg1;
- (void)saveCalendar:(id)arg1;
- (void)removeCalendar:(id)arg1;
- (void)addCalendarGroup:(id)arg1;
- (void)saveCalendarGroup:(id)arg1;
- (void)removeCalendarGroup:(id)arg1;
- (void)removeCalendarGroup:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)holdNotifications;
- (void)resumeNotifications;
- (void)recreateIMAPGroups:(id)arg1 calendars:(id)arg2 todos:(id)arg3;
@end

