/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/Criterion.h>

@interface Criterion (LibraryAdditions)
- (BOOL)isExpressibleInTigerSchema;
- (id)criterionExpressionForEqualRelativeDates:(CDAnonymousStruct12 *)arg1 depth:(unsigned long long)arg2 enclosingSmartMailboxes:(id)arg3;
- (id)criterionValueForNotEqualRelativeDates:(int *)arg1;
- (id)criterionForSQL;
- (id)SQLExpressionWithTables:(unsigned long long *)arg1 baseTable:(unsigned long long)arg2;
- (unsigned long long)bestBaseTable;
@end

