/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSUserDefaults;

@interface Defaults : NSObject
{
    NSUserDefaults *defaults;
}

+ (id)sharedInstance;
+ (void)setupLoggingDefaults;
+ (id)logMessages;
+ (id)macBuddyPlist;
+ (id)mailSetupFromMacBuddy;
- (id)primaryEmailAddress;
- (void)setPrimaryEmailAddress:(id)fp8;
- (int)headerDetailLevel;
- (void)setHeaderDetailLevel:(int)fp8;
- (id)_regexesForCustomDisplayedHeaders;
- (id)headersToDisplayFromHeaderKeys:(id)fp8 headerDetailLevel:(int)fp12;
- (id)customDisplayedHeaders;
- (void)setCustomDisplayedHeaders:(id)fp8;
- (int)sendFormat;
- (void)setSendFormat:(int)fp8;
- (id)mailAccountDirectory;
- (void)setDefaultMailDirectory:(id)fp8;
- (id)defaultMailDirectory;
- (id)archiveMailbox;
- (id)draftsMailbox;
- (id)trashMailboxName;
- (BOOL)autosaveWindows;
- (void)setAutosaveWindows:(BOOL)fp8;
- (id)quotingColorList;
- (void)setQuotingColorList:(id)fp8;
- (id)colorForQuoteLevel:(int)fp8;
- (id)userStyleSheetURL;
- (id)alternateAddressesForSelf;
- (id)dictionaryForKey:(id)fp8;
- (id)stringForKey:(id)fp8;
- (void)removeObjectForKey:(id)fp8;
- (void)setObject:(id)fp8 forKey:(id)fp12;
- (id)objectForKey:(id)fp8;
- (void)setBool:(BOOL)fp8 forKey:(id)fp12;
- (BOOL)boolForKey:(id)fp8;
- (int)integerForKey:(id)fp8;
- (BOOL)synchronize;

@end

