/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Message/Account.h>

@interface DeliveryAccount : Account
{
}

+ (void)_postDeliveryAccountsHaveChanged;
+ (id)deliveryAccounts;
+ (void)setDeliveryAccounts:(id)fp8;
+ (void)addDeliveryAccount:(id)fp8;
+ (void)removeDeliveryAccount:(id)fp8;
+ (void)saveAccountInfoToDefaults;
+ (id)accountWithUniqueId:(id)fp8;
+ (id)accountWithIdentifier:(id)fp8;
+ (id)existingAccountWithHostname:(id)fp8 username:(id)fp12;
+ (id)accountWithHostname:(id)fp8 username:(id)fp12;
+ (id)accountWithHostname:(id)fp8 username:(id)fp12 lookForExistingAccounts:(BOOL)fp16;
+ (id)newDefaultInstance;
- (Class)deliveryClass;
- (id)identifier;
- (void)updateFromSyncedDictionary:(id)fp8;
- (BOOL)shouldUseAuthentication;
- (void)setShouldUseAuthentication:(BOOL)fp8;
- (unsigned long long)maximumMessageBytes;
- (void)setMaximumMessageBytes:(unsigned long long)fp8;

@end

