/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSString, NSURL;

@interface EnclosureTransporter
{
    NSURL *URL;
    NSString *MIMEType;
    long long length;
}

@property long long length; // @synthesize length;
@property(copy) NSString *MIMEType; // @synthesize MIMEType;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,VMIMEType,P

@property(copy) NSURL *URL; // @synthesize URL;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSURL",C,VURL,P


- (void)dealloc;
- (id)initWithEnclosure:(id)arg1;
- (long long)length;
- (void)setLength:(long long)arg1;
- (id)MIMEType;
- (void)setMIMEType:(id)arg1;
- (id)URL;
- (void)setURL:(id)arg1;

@end

