/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSArray, NSDate, NSString, NSTimeZone, NSURL;

@interface EntryTransporter
{
    NSString *title;
    NSString *identifier;
    NSURL *alternateURL;
    NSURL *baseURL;
    BOOL isRead;
    BOOL isFlagged;
    long long rank;
    NSDate *datePublished;
    NSTimeZone *timeZonePublished;
    NSDate *dateUpdated;
    NSTimeZone *timeZoneUpdated;
    NSArray *authors;
    NSArray *enclosures;
    NSString *HTMLContent;
    NSString *textContent;
}

@property(retain) NSArray *enclosures; // @synthesize enclosures;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSArray",&,Venclosures,P

@property(retain) NSArray *authors; // @synthesize authors;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSArray",&,Vauthors,P

@property(copy) NSString *textContent; // @synthesize textContent;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,VtextContent,P

@property(copy) NSString *HTMLContent; // @synthesize HTMLContent;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,VHTMLContent,P

@property(copy) NSTimeZone *timeZoneUpdated; // @synthesize timeZoneUpdated;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSTimeZone",C,VtimeZoneUpdated,P

@property(copy) NSDate *dateUpdated; // @synthesize dateUpdated;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSDate",C,VdateUpdated,P

@property(copy) NSTimeZone *timeZonePublished; // @synthesize timeZonePublished;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSTimeZone",C,VtimeZonePublished,P

@property(copy) NSDate *datePublished; // @synthesize datePublished;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSDate",C,VdatePublished,P

@property long long rank; // @synthesize rank;
@property BOOL isFlagged; // @synthesize isFlagged;
@property BOOL isRead; // @synthesize isRead;
@property(copy) NSURL *baseURL; // @synthesize baseURL;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSURL",C,VbaseURL,P

@property(copy) NSURL *alternateURL; // @synthesize alternateURL;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSURL",C,ValternateURL,P

@property(copy) NSString *identifier; // @synthesize identifier;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,Videntifier,P

@property(copy) NSString *title; // @synthesize title;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,Vtitle,P


+ (id)transporterArrayWithEntries:(id)arg1;
- (void)dealloc;
- (id)initWithEntry:(id)arg1;
- (id)enclosures;
- (void)setEnclosures:(id)arg1;
- (id)authors;
- (void)setAuthors:(id)arg1;
- (id)textContent;
- (void)setTextContent:(id)arg1;
- (id)HTMLContent;
- (void)setHTMLContent:(id)arg1;
- (id)timeZoneUpdated;
- (void)setTimeZoneUpdated:(id)arg1;
- (id)dateUpdated;
- (void)setDateUpdated:(id)arg1;
- (id)timeZonePublished;
- (void)setTimeZonePublished:(id)arg1;
- (id)datePublished;
- (void)setDatePublished:(id)arg1;
- (long long)rank;
- (void)setRank:(long long)arg1;
- (BOOL)isFlagged;
- (void)setIsFlagged:(BOOL)arg1;
- (BOOL)isRead;
- (void)setIsRead:(BOOL)arg1;
- (id)baseURL;
- (void)setBaseURL:(id)arg1;
- (id)alternateURL;
- (void)setAlternateURL:(id)arg1;
- (id)identifier;
- (void)setIdentifier:(id)arg1;
- (id)title;
- (void)setTitle:(id)arg1;

@end

