/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "EWSAutodiscoverBindingDelegate-Protocol.h"

@class NSDictionary, NSError, NSString;

@interface EWSAutodiscovery <EWSAutodiscoverBindingDelegate>
{
    NSString *_emailAddress;
    NSString *_password;
    NSString *_userName;
    NSDictionary *_receivingAccountInfo;
    long long _status;
    NSError *_lastError;
}

@property(copy) NSError *lastError; // @synthesize lastError=_lastError;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSError",C,V_lastError,P

@property long long status; // @synthesize status=_status;
@property(copy) NSDictionary *receivingAccountInfo; // @synthesize receivingAccountInfo=_receivingAccountInfo;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSDictionary",C,V_receivingAccountInfo,P

@property(copy) NSString *userName; // @synthesize userName=_userName;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,V_userName,P

@property(copy) NSString *password; // @synthesize password=_password;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"NSString",C,N,V_password,P

@property(copy) NSString *emailAddress; // @synthesize emailAddress=_emailAddress;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"NSString",C,N,V_emailAddress,P


+ (void)initialize;
- (id)init;
- (id)initWithEmailAddress:(id)arg1 userName:(id)arg2 password:(id)arg3;
- (void)dealloc;
- (long long)executeSynchronouslyWithMonitor:(id)arg1;
- (void)autodiscoverBinding:(id)arg1 didCancelAuthenticationChallenge:(id)arg2;
- (void)autodiscoverBinding:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2;
- (void)autodiscoverBinding:(id)arg1 didFinishWithResponse:(id)arg2;
- (void)autodiscoverBinding:(id)arg1 didFailWithError:(id)arg2;
- (void)autodiscoverBinding:(id)arg1 didReceiveCertificateError:(id)arg2;
- (id)lastError;
- (void)setLastError:(id)arg1;
- (long long)status;
- (void)setStatus:(long long)arg1;
- (id)receivingAccountInfo;
- (void)setReceivingAccountInfo:(id)arg1;
- (id)userName;
- (void)setUserName:(id)arg1;
- (id)password;
- (void)setPassword:(id)arg1;
- (id)emailAddress;
- (void)setEmailAddress:(id)arg1;

@end

