/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/EWSRequestOperation.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface EWSCreateItemRequestOperation : EWSRequestOperation <NSCoding>
{
    NSString *_EWSFolderIdString;
    NSString *_offlineCreatedEWSItemIdString;
    long long _disposition;
    BOOL _messageType;
    BOOL _wroteOfflineData;
}

@property BOOL wroteOfflineData; // @synthesize wroteOfflineData=_wroteOfflineData;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,V_wroteOfflineData

@property(retain) NSString *offlineCreatedEWSItemIdString; // @synthesize offlineCreatedEWSItemIdString=_offlineCreatedEWSItemIdString;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",&,V_offlineCreatedEWSItemIdString,P

@property long long disposition; // @synthesize disposition=_disposition;
// Preceeding property had unknown attributes: N
// Original attribute string: Tq,N,V_disposition

@property BOOL messageType; // @synthesize messageType=_messageType;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,V_messageType

@property(retain) NSString *EWSFolderIdString; // @synthesize EWSFolderIdString=_EWSFolderIdString;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"NSString",&,N,V_EWSFolderIdString,P


+ (Class)classForResponse;
- (id)initWithFolderIdString:(id)arg1 messageType:(BOOL)arg2 disposition:(long long)arg3 gateway:(id)arg4 errorHandler:(id)arg5;
- (void)_ewsCreateItemRequestOperationCommonInitWithFolderIdString:(id)arg1 messageType:(BOOL)arg2 disposition:(long long)arg3;
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)activityString;
- (void)setupOfflineResponse;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)wroteOfflineData;
- (void)setWroteOfflineData:(BOOL)arg1;
- (id)offlineCreatedEWSItemIdString;
- (void)setOfflineCreatedEWSItemIdString:(id)arg1;
- (long long)disposition;
- (void)setDisposition:(long long)arg1;
- (BOOL)messageType;
- (void)setMessageType:(BOOL)arg1;
- (id)EWSFolderIdString;
- (void)setEWSFolderIdString:(id)arg1;

@end

