/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/EWSCreateItemRequestOperation.h>

@class EWSGetItemsResponseOperation, NSString;

@interface EWSCreateEventReplyRequestOperation : EWSCreateItemRequestOperation
{
    NSString *_messageMeetingItemIdString;
    BOOL _messageResponseType;
    EWSGetItemsResponseOperation *_getItemsResponse;
}

@property(retain) EWSGetItemsResponseOperation *getItemsResponse; // @synthesize getItemsResponse=_getItemsResponse;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"EWSGetItemsResponseOperation",&,N,V_getItemsResponse,P

@property BOOL messageResponseType; // @synthesize messageResponseType=_messageResponseType;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,V_messageResponseType

@property(retain) NSString *messageMeetingItemIdString; // @synthesize messageMeetingItemIdString=_messageMeetingItemIdString;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"NSString",&,N,V_messageMeetingItemIdString,P


+ (Class)classForResponse;
- (id)initWithItemIdString:(id)arg1 folderIdString:(id)arg2 messageType:(BOOL)arg3 responseType:(BOOL)arg4 disposition:(long long)arg5 gateway:(id)arg6 errorHandler:(id)arg7;
- (void)_ewsCreateEventReplyRequestOperationCommonInitWithItemIdString:(id)arg1 responseType:(BOOL)arg2;
- (id)initWithFolderIdString:(id)arg1 messageType:(BOOL)arg2 disposition:(long long)arg3 gateway:(id)arg4 errorHandler:(id)arg5;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)prepareRequest;
- (id)getItemsResponse;
- (void)setGetItemsResponse:(id)arg1;
- (BOOL)messageResponseType;
- (void)setMessageResponseType:(BOOL)arg1;
- (id)messageMeetingItemIdString;
- (void)setMessageMeetingItemIdString:(id)arg1;

@end

