/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MailDelivery.h>

#import "EWSErrorHandler-Protocol.h"

@class MFError;

@interface EWSDelivery : MailDelivery <EWSErrorHandler>
{
    MFError *_error;
}

@property(retain) MFError *error; // @synthesize error=_error;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"MFError",&,V_error,P


- (void)dealloc;
- (Class)deliveryClass;
- (id)headersForDelivery;
- (int)deliverSynchronously;
- (void)handleEWSError:(id)arg1;
- (id)error;
- (void)setError:(id)arg1;

@end

