/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/EWSRequestOperation.h>

#import "NSCoding-Protocol.h"

@class NSArray, NSString;

@interface EWSDeleteItemsRequestOperation : EWSRequestOperation <NSCoding>
{
    NSArray *_EWSItemIds;
    NSString *_folderIdString;
}

@property(retain) NSString *folderIdString; // @synthesize folderIdString=_folderIdString;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"NSString",&,N,V_folderIdString,P

@property(retain) NSArray *EWSItemIds; // @synthesize EWSItemIds=_EWSItemIds;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"NSArray",&,N,V_EWSItemIds,P


+ (Class)classForResponse;
- (id)initWithEWSItemIds:(id)arg1 folderIdString:(id)arg2 gateway:(id)arg3;
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)activityString;
- (id)prepareRequest;
- (void)setupOfflineResponse;
- (id)folderIdString;
- (void)setFolderIdString:(id)arg1;
- (id)EWSItemIds;
- (void)setEWSItemIds:(id)arg1;

@end

