/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/EWSRequestOperation.h>

@class NSArray;

@interface EWSGetItemsRequestOperation : EWSRequestOperation
{
    NSArray *_EWSItemIds;
    NSArray *_additionalProperties;
}

@property(retain) NSArray *additionalProperties; // @synthesize additionalProperties=_additionalProperties;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"NSArray",&,N,V_additionalProperties,P

@property(retain) NSArray *EWSItemIds; // @synthesize EWSItemIds=_EWSItemIds;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"NSArray",&,N,V_EWSItemIds,P


+ (Class)classForResponse;
- (id)initWithEWSItemIds:(id)arg1 additionalProperties:(id)arg2 gateway:(id)arg3 errorHandler:(id)arg4;
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;
- (void)dealloc;
- (id)activityString;
- (id)prepareRequest;
- (id)additionalProperties;
- (void)setAdditionalProperties:(id)arg1;
- (id)EWSItemIds;
- (void)setEWSItemIds:(id)arg1;

@end

