/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/EWSResponseOperation.h>

@class NSArray, NSMutableArray;

@interface EWSGetItemsResponseOperation : EWSResponseOperation
{
    NSArray *_EWSItemIdsRequested;
    NSMutableArray *_EWSItems;
}

@property(retain) NSArray *EWSItemIdsRequested; // @synthesize EWSItemIdsRequested=_EWSItemIdsRequested;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSArray",&,V_EWSItemIdsRequested,P

@property(retain) NSMutableArray *EWSItems; // @synthesize EWSItems=_EWSItems;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSMutableArray",&,V_EWSItems,P


- (void)dealloc;
- (void)prepareToExecuteWithResponse:(id)arg1 forRequestOperation:(id)arg2;
- (void)executeOperation;
- (id)EWSItemIdsRequested;
- (void)setEWSItemIdsRequested:(id)arg1;
- (id)EWSItems;
- (void)setEWSItems:(id)arg1;

@end

