/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/EWSGateway.h>

#import "NSKeyedUnarchiverDelegate-Protocol.h"

@class EWSConnection, EWSResponseOperation, NSMutableDictionary;

@interface EWSOfflineGateway : EWSGateway <NSKeyedUnarchiverDelegate>
{
    EWSConnection *_offlineConnection;
    NSMutableDictionary *_offlineToRealEWSIdStrings;
    id _offlineToRealEWSIdStringsLock;
    EWSResponseOperation *_lastResponseDecoded;
}

@property(retain) NSMutableDictionary *offlineToRealEWSIdStrings;
// Preceeding property had unknown attributes: D,N,P
// Original attribute string: T@"NSMutableDictionary",&,D,N,P

@property(retain) EWSResponseOperation *lastResponseDecoded; // @synthesize lastResponseDecoded=_lastResponseDecoded;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"EWSResponseOperation",&,V_lastResponseDecoded,P

@property(retain) EWSConnection *offlineConnection; // @synthesize offlineConnection=_offlineConnection;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"EWSConnection",&,V_offlineConnection,P


- (id)initWithAccount:(id)arg1 connection:(id)arg2;
- (id)initWithAccount:(id)arg1;
- (void)dealloc;
- (id)connection;
- (void)addRequest:(id)arg1;
- (id)resolvedIdStringForIdString:(id)arg1;
- (void)addOfflineToRealEWSIdStrings:(id)arg1 forRequest:(id)arg2;
- (void)takeRequestOffline:(id)arg1 error:(id)arg2;
- (id)playbackRequests:(id)arg1 offlineToRealEWSIdStrings:(id *)arg2 error:(id *)arg3;
- (void)setOfflineToRealEWSIdStrings:(id)arg1;
- (id)offlineToRealEWSIdStrings;
- (id)_EWSFolderFromCreateRequestOperation:(id)arg1;
- (id)_deleteRequestRemovingUndeletedItems:(id)arg1;
- (void)_moveMessageFromFailedCreateRequest:(id)arg1 withBackupManager:(id)arg2 toMailboxNamed:(id)arg3 actualName:(id *)arg4;
- (void)_undeleteMessagesFromFailedCopyRequest:(id)arg1;
- (void)_undeleteMessagesFromFailedDeleteRequest:(id)arg1;
- (id)unarchiver:(id)arg1 didDecodeObject:(id)arg2;
- (id)lastResponseDecoded;
- (void)setLastResponseDecoded:(id)arg1;
- (id)offlineConnection;
- (void)setOfflineConnection:(id)arg1;

@end

