/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/EWSRequestOperation.h>

@class NSString;

@interface EWSSyncFolderHierarchyRequestOperation : EWSRequestOperation
{
    NSString *_syncState;
}

@property(copy) NSString *syncState; // @synthesize syncState=_syncState;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"NSString",C,N,V_syncState,P


+ (Class)classForResponse;
- (id)initWithSyncState:(id)arg1 createBlock:(id)arg2 updateBlock:(void)arg3 deleteBlock:(id)arg4 gateway:(void)arg5;
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;
- (void)dealloc;
- (id)activityString;
- (id)prepareRequest;
- (id)syncState;
- (void)setSyncState:(id)arg1;

@end

