/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/EWSResponseOperation.h>

@class EWSStore, NSArray, NSMutableArray, NSString;

@interface EWSSyncFolderItemsResponseMessageOperation : EWSResponseOperation
{
    EWSStore *_store;
    NSString *_folderIdString;
    NSString *_startSyncState;
    NSString *_endSyncState;
    NSMutableArray *_messagesWithoutHeaders;
}

@property(readonly) NSArray *messagesWithoutHeaders;
// Preceeding property had unknown attributes: D,P
// Original attribute string: T@"NSArray",R,D,P

@property(retain) NSString *endSyncState; // @synthesize endSyncState=_endSyncState;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",&,V_endSyncState,P

@property(retain) NSString *startSyncState; // @synthesize startSyncState=_startSyncState;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",&,V_startSyncState,P

@property(retain) NSString *folderIdString; // @synthesize folderIdString=_folderIdString;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",&,V_folderIdString,P

@property(retain) EWSStore *store; // @synthesize store=_store;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"EWSStore",&,V_store,P


+ (void)initialize;
- (void)prepareToExecuteWithResponse:(id)arg1 forRequestOperation:(id)arg2;
- (void)dealloc;
- (void)executeOperation;
- (void)_handleSyncFolderItemsCreateOrUpdate:(id)arg1 forStore:(id)arg2 messagesToUpdate:(id)arg3 libraryIDs:(id)arg4 messagesToCreate:(id)arg5 messagesThatFinished:(id)arg6;
- (void)_addMessageWithoutHeaders:(id)arg1;
- (id)messagesWithoutHeaders;
- (id)endSyncState;
- (void)setEndSyncState:(id)arg1;
- (id)startSyncState;
- (void)setStartSyncState:(id)arg1;
- (id)folderIdString;
- (void)setFolderIdString:(id)arg1;
- (id)store;
- (void)setStore:(id)arg1;

@end

