/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/EWSRequestOperation.h>

@class EWSGetItemsResponseOperation;

@interface EWSSuppressReadReceiptsRequestOperation : EWSRequestOperation
{
    EWSGetItemsResponseOperation *_getItemsResponse;
}

@property(retain) EWSGetItemsResponseOperation *getItemsResponse; // @synthesize getItemsResponse=_getItemsResponse;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"EWSGetItemsResponseOperation",&,N,V_getItemsResponse,P


+ (Class)classForResponse;
- (id)initWithGetItemsResponse:(id)arg1 gateway:(id)arg2;
- (id)initWithGateway:(id)arg1 errorHandler:(id)arg2;
- (void)dealloc;
- (id)prepareRequest;
- (id)getItemsResponse;
- (void)setGetItemsResponse:(id)arg1;

@end

