/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/SASLAuthenticator.h>

#import "SASLSecurityLayer-Protocol.h"

@interface GSSAPIAuthenticator : SASLAuthenticator <SASLSecurityLayer>
{
    unsigned int _maxBufferSize;
    unsigned int _substate:2;
    unsigned int _securityLevel:4;
    struct gss_ctx_id_struct *_gssContext;
    struct gss_name_struct *_targetName;
    struct gss_cred_id_struct *_credentials;
    unsigned int _qopState;
    int _requestConfidentiality;
}

- (void)dealloc;
- (void)finalize;
- (int)fillClientPrincipal:(id *)arg1 servicePrincipal:(id *)arg2 usingAccount:(id)arg3;
- (void)setAuthenticationState:(int)arg1;
- (id)responseForServerData:(id)arg1;
- (id)securityLayer;
- (unsigned int)encryptionBufferSize;
- (id)createDecryptedDataForBytes:(const char *)arg1 length:(unsigned long long)arg2;
- (id)createEncryptedDataForBytes:(const char *)arg1 length:(unsigned long long)arg2;

@end

