/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface HeaderParsingUtils
{
}

+ (id)dictionaryForReceivedHeader:(id)arg1;
+ (void)_setReceivedValuesInDictionary:(id)arg1 key:(id)arg2 value:(id)arg3 comment:(id)arg4 actualHostDotted:(id)arg5 actualHostIP:(id)arg6;
+ (BOOL)isHostRemote:(id)arg1;
+ (id)firstRemoteReceivedHeaderForReceivedHeaders:(id)arg1;

@end

