/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface ImageJunkMetadata
{
    int _type;
    struct CGSize _size;
    unsigned long long _frameCount;
    unsigned long long _pixelCount;
    unsigned long long _byteCount;
    double _density;
    BOOL _isAnimated;
}

@property(readonly) int sizeCategory;
@property(readonly) int densityCategory;
@property unsigned long long frameCount; // @synthesize frameCount=_frameCount;
@property BOOL isAnimated; // @synthesize isAnimated=_isAnimated;
@property double density; // @synthesize density=_density;
@property unsigned long long byteCount; // @synthesize byteCount=_byteCount;
@property unsigned long long pixelCount; // @synthesize pixelCount=_pixelCount;
@property struct CGSize size; // @synthesize size=_size;
@property int type; // @synthesize type=_type;

+ (id)stringForImageType:(int)arg1;
+ (id)lsmMarkerForImageSizeCategory:(int)arg1;
+ (id)lsmMarkerForImageDensityCategory:(int)arg1;
- (id)initWithImage:(id)arg1 name:(id)arg2 type:(int)arg3;
- (void)dealloc;
- (void)computeDensity;
- (void)setByteCount:(unsigned long long)arg1;
- (void)setPixelCount:(unsigned long long)arg1;
- (int)sizeCategory;
- (int)densityCategory;
- (id)description;
- (unsigned long long)frameCount;
- (void)setFrameCount:(unsigned long long)arg1;
- (BOOL)isAnimated;
- (void)setIsAnimated:(BOOL)arg1;
- (double)density;
- (void)setDensity:(double)arg1;
- (unsigned long long)byteCount;
- (unsigned long long)pixelCount;
- (struct CGSize)size;
- (void)setSize:(struct CGSize)arg1;
- (int)type;
- (void)setType:(int)arg1;

@end

