/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPSingleClientOperation.h>

@class NSString, SASLAuthenticator;

@interface IMAPClientAuthenticateOperation : IMAPSingleClientOperation
{
    NSString *_authenticateType;
    SASLAuthenticator *_authenticator;
}

@property(retain) SASLAuthenticator *authenticator; // @synthesize authenticator=_authenticator;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"SASLAuthenticator",&,V_authenticator,P

@property(copy) NSString *authenticateType; // @synthesize authenticateType=_authenticateType;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,V_authenticateType,P


- (void)dealloc;
- (id)initWithAuthenticator:(id)arg1;
- (id)commandTypeString;
- (BOOL)handlesAllUntaggedResponses;
- (id)createCommandDataForLiteralPlus:(BOOL)arg1;
- (BOOL)executeOnConnection:(id)arg1;
- (id)authenticator;
- (void)setAuthenticator:(id)arg1;
- (id)authenticateType;
- (void)setAuthenticateType:(id)arg1;

@end

