/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "IMAPResponseHandler-Protocol.h"

@class IMAPGateway, IMAPMailbox, InvocationQueue, LibraryIMAPStore, NSArray, NSMutableArray, NSMutableIndexSet;

@interface IMAPMailboxSyncEngine <IMAPResponseHandler>
{
    id _syncEngineLock;
    IMAPGateway *_gateway;
    LibraryIMAPStore *_store;
    IMAPMailbox *_IMAPMailbox;
    NSMutableArray *_auxiliaryLists;
    NSMutableIndexSet *_allNewUids;
    NSMutableIndexSet *_UIDsNeedingSkeletons;
    unsigned int _uidNext;
    unsigned int _uidValidity;
    unsigned int _libraryClientUidNext;
    unsigned long long _numMessagesOnServer;
    unsigned long long _firstMessageNumber;
    NSMutableArray *_messageDetails;
    unsigned long long _maxSkeletonsToFetch;
    NSMutableIndexSet *_expungedUids;
    BOOL _automaticallyStartThread;
    BOOL _storeIsInbox;
    BOOL _newMailReceivedInInbox;
    BOOL _checkedForNewUids;
    BOOL _synchronizedOldMessages;
    int _progressType;
    BOOL _connectionSupportsUIDPLUS;
    unsigned long long _progressTotal;
    unsigned long long _checkNewMailCount;
    InvocationQueue *_syncEngineQueue;
    NSMutableArray *_messagesNeedingAttachmentNames;
    BOOL _messagesNeedAttachmentNames;
    BOOL _isReset;
    BOOL _needToUpdateExists;
    BOOL _newResponsesAvailable;
    unsigned int _newUidValidity;
    NSMutableArray *_messagesAddedToLibrary;
    NSMutableArray *_uidsAddedToServer;
    NSMutableArray *_messagesAddedToServer;
    NSArray *_messagesBeingRouted;
}

@property BOOL connectionSupportsUIDPLUS; // @synthesize connectionSupportsUIDPLUS=_connectionSupportsUIDPLUS;
@property unsigned int uidNext; // @synthesize uidNext=_uidNext;
@property unsigned long long numMessagesOnServer; // @synthesize numMessagesOnServer=_numMessagesOnServer;
@property BOOL messageListIsSynchronized; // @synthesize messageListIsSynchronized=_synchronizedOldMessages;

- (void)dealloc;
- (id)initWithStore:(id)arg1;
- (id)init;
- (id)_copyIMAPMailbox;
- (id)_copyLibraryIMAPStore;
- (BOOL)isReset;
- (void)reset;
- (void)_resetClearingGateway:(BOOL)arg1 clearingStore:(BOOL)arg2;
- (void)invalidateStore;
- (void)_setupForNewIMAPMailbox:(id)arg1 andGateway:(id)arg2;
- (void)setGatewayFromIMAPMailbox:(id)arg1;
- (void)updateCountOfMessagesOnServerFromIMAPMailbox:(id)arg1;
- (void)_lockedUpdateCountOfMessagesOnServerIfNecessary;
- (void)setUidValidity:(unsigned int)arg1;
- (void)responsesWereAddedToIMAPMailbox:(id)arg1;
- (void)_handleMessagesWereAddedToLibrary:(id)arg1 withMonitor:(id)arg2;
- (void)messagesWereAddedToLibrary:(id)arg1;
- (id)messagesBeingAdded;
- (void)setAutomaticallyStartsBackgroundThread:(BOOL)arg1;
- (void)runSynchronouslyWithMessages:(id)arg1;
- (void)requestCheckingNewMail;
- (void)_handleNewUIDsAddedToServer:(id)arg1 forMessages:(id)arg2;
- (void)newUIDsWereAddedToServer:(id)arg1 forMessages:(id)arg2;
- (void)_pushFlags:(id)arg1 forMessageIDs:(id)arg2 toStore:(id)arg3 updateServer:(BOOL)arg4 usingCriterion:(id)arg5 withMonitor:(id)arg6;
- (void)_pushFlags:(id)arg1 toStore:(id)arg2 updateServer:(BOOL)arg3 withMonitor:(id)arg4;
- (void)_processAttachmentNames;
- (void)_setAttachmentNamesForMessage:(id)arg1;
- (id)_checkOutGateway;
- (BOOL)_setGateway:(id)arg1;
- (void)_notifyBackgroundFetchCompleted;
- (BOOL)_hasPendingChanges;
- (void)_updatePendingChangesWithMonitor:(id)arg1;
- (void)_goWithMessages:(id)arg1;
- (void)_goWithMessagesIfNeeded:(id)arg1;
- (BOOL)_shouldContinueSyncingWithGateway;
- (BOOL)_shouldContinueSyncingWithMonitor:(id)arg1;
- (BOOL)_unlockIfProcessedResponsesWithMonitor:(id)arg1;
- (BOOL)_unlockIfGotNewMessageSkeletonsWithMonitor:(id)arg1;
- (id)_lockedCreateOperationFromUIDsNeedingSkeletons:(unsigned long long)arg1;
- (BOOL)_unlockIfHandledRoutedUidsWithMonitor:(id)arg1;
- (BOOL)_unlockIfFetchedUidsAndFlagsWithMonitor:(id)arg1;
- (BOOL)_unlockIfSyncedWithLibraryWithMonitor:(id)arg1 messages:(id)arg2;
- (BOOL)_unlockIfDidCacheMessagesWithMonitor:(id)arg1;
- (BOOL)_unlockIfDidCacheAttachmentsWithMonitor:(id)arg1;
- (BOOL)_recoverFromErrorInDownload:(id)arg1 uid:(unsigned int)arg2 cacheList:(id)arg3 atIndex:(unsigned long long)arg4 downloadCache:(id)arg5;
- (BOOL)_unlockIfHandledInvitationMessagesWithMonitor:(id)arg1;
- (int)_cachePolicyForAccount:(id)arg1;
- (id)description;
- (BOOL)handleResponse:(id)arg1 forOperation:(id)arg2;
- (void)_setupFakeResponseToOperation:(id)arg1 messageNumber:(unsigned long long)arg2;
- (BOOL)_handleFailedFetchResponse:(id)arg1 forOperation:(id)arg2;
- (BOOL)connectionSupportsUIDPLUS;
- (void)setConnectionSupportsUIDPLUS:(BOOL)arg1;
- (unsigned int)uidNext;
- (void)setUidNext:(unsigned int)arg1;
- (unsigned long long)numMessagesOnServer;
- (void)setNumMessagesOnServer:(unsigned long long)arg1;
- (BOOL)messageListIsSynchronized;
- (void)setMessageListIsSynchronized:(BOOL)arg1;

@end

