/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPClientMailboxOperation.h>

@class ActivityMonitor, NSArray, NSData, NSDate, NSDictionary;

@interface IMAPClientAppendOperation : IMAPClientMailboxOperation
{
    NSDate *_dateReceived;
    NSArray *_serverFlags;
    NSData *_data;
    NSDictionary *_newMessageInfo;
    BOOL _shouldTryCreate;
    ActivityMonitor *_progressMonitor;
}

@property(retain) ActivityMonitor *progressMonitor; // @synthesize progressMonitor=_progressMonitor;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"ActivityMonitor",&,V_progressMonitor,P

@property BOOL shouldTryCreate; // @synthesize shouldTryCreate=_shouldTryCreate;
@property(retain) NSDictionary *newMessageInfo; // @synthesize newMessageInfo=_newMessageInfo;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSDictionary",&,V_newMessageInfo,P

@property(retain) NSData *data; // @synthesize data=_data;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSData",&,V_data,P

@property(retain) NSArray *serverFlags; // @synthesize serverFlags=_serverFlags;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSArray",&,V_serverFlags,P

@property(retain) NSDate *dateReceived; // @synthesize dateReceived=_dateReceived;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSDate",&,V_dateReceived,P


- (void)dealloc;
- (id)initWithMailboxName:(id)arg1 flags:(id)arg2 dateReceived:(id)arg3 data:(id)arg4;
- (id)commandTypeString;
- (id)detailsString;
- (id)createCommandDataForLiteralPlus:(BOOL)arg1;
- (BOOL)executeOnConnection:(id)arg1;
- (id)progressMonitor;
- (void)setProgressMonitor:(id)arg1;
- (BOOL)shouldTryCreate;
- (void)setShouldTryCreate:(BOOL)arg1;
- (id)newMessageInfo;
- (void)setNewMessageInfo:(id)arg1;
- (id)data;
- (void)setData:(id)arg1;
- (id)serverFlags;
- (void)setServerFlags:(id)arg1;
- (id)dateReceived;
- (void)setDateReceived:(id)arg1;

@end

