/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class MFError, NSString;

@interface IMAPResponse
{
    unsigned int _responseType:8;
    NSString *_tag;
    union _IMAPResponseData _data;
    MFError *_error;
    BOOL _wasHandled;
}

@property BOOL wasHandled; // @synthesize wasHandled=_wasHandled;

- (int)responseType;
- (void)setResponseType:(int)arg1;
- (BOOL)isUntagged;
- (BOOL)isAlertResponse;
- (id)tag;
- (void)setTag:(id)arg1;
- (void)dealloc;
- (void)finalize;
- (int)responseCode;
- (id)responseInfo;
- (id)userData;
- (id)userString;
- (void)setUserData:(id)arg1 responseCode:(int)arg2 responseInfo:(id)arg3;
- (id)capabilities;
- (void)setCapabilities:(id)arg1;
- (unsigned long long)number;
- (void)setNumber:(unsigned long long)arg1;
- (id)flags;
- (void)setFlags:(id)arg1;
- (id)mailboxName;
- (id)statusEntries;
- (void)setMailboxName:(id)arg1 statusEntries:(id)arg2;
- (id)searchResults;
- (void)setSearchResults:(id)arg1;
- (unsigned long long)mailboxAttributes;
- (id)separator;
- (void)setMailboxAttributes:(unsigned long long)arg1 separator:(id)arg2 mailboxName:(id)arg3;
- (id)fetchResultWithType:(int)arg1;
- (id)fetchResults;
- (void)setFetchResults:(id)arg1;
- (BOOL)isValid;
- (void)setIsValid:(BOOL)arg1;
- (id)quotaRootNames;
- (void)setMailboxName:(id)arg1 quotaRootNames:(id)arg2;
- (id)quotaRootName;
- (id)quotas;
- (void)setQuotaRootName:(id)arg1 quotas:(id)arg2;
- (int)uidFlagsChange;
- (void)setUidFlagsChange:(int)arg1;
- (id)uids;
- (void)setUids:(id)arg1;
- (id)flagsFetchResult;
- (void)setFlagsFetchResult:(id)arg1;
- (id)responseName;
- (id)parameters;
- (void)setResponseName:(id)arg1 parameters:(id)arg2;
- (id)description;
- (id)initWithConnection:(id)arg1 error:(id *)arg2;
- (void)setError:(id)arg1;
- (id)error;
- (BOOL)wasHandled;
- (void)setWasHandled:(BOOL)arg1;

@end

