/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class IMAPGateway, MailboxUid, NSArray, NSMutableArray, NSString;

@interface IMAPMailbox
{
    id <IMAPMailboxDelegate> _delegate;
    MailboxUid *_mailboxUid;
    unsigned long long _permanentFlags;
    NSString *_referenceName;
    BOOL _readOnly;
    BOOL _uidNotSticky;
    IMAPGateway *_selectedGateway;
    NSArray *_quotaRoots;
    unsigned long long _exists;
    CDAnonymousStruct6 _quotaUsage;
    unsigned int _uidNext;
    unsigned int _uidValidity;
    unsigned int _unseenCount;
    NSMutableArray *_unprocessedResponses;
    BOOL _hasNewResponses;
}

@property BOOL hasNewResponses; // @synthesize hasNewResponses=_hasNewResponses;
@property(retain) NSMutableArray *unprocessedResponses; // @synthesize unprocessedResponses=_unprocessedResponses;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSMutableArray",&,V_unprocessedResponses,P

@property unsigned int unseenCount; // @synthesize unseenCount=_unseenCount;
@property unsigned int uidValidity; // @synthesize uidValidity=_uidValidity;
@property unsigned int uidNext; // @synthesize uidNext=_uidNext;
@property CDAnonymousStruct6 quotaUsage; // @synthesize quotaUsage=_quotaUsage;
@property unsigned long long exists; // @synthesize exists=_exists;
@property(retain) NSArray *quotaRoots; // @synthesize quotaRoots=_quotaRoots;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSArray",&,V_quotaRoots,P

@property(retain) IMAPGateway *selectedGateway; // @synthesize selectedGateway=_selectedGateway;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"IMAPGateway",&,V_selectedGateway,P

@property BOOL uidNotSticky; // @synthesize uidNotSticky=_uidNotSticky;
@property BOOL readOnly; // @synthesize readOnly=_readOnly;
@property(copy) NSString *referenceName; // @synthesize referenceName=_referenceName;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,V_referenceName,P

@property unsigned long long permanentFlags; // @synthesize permanentFlags=_permanentFlags;
@property(retain) MailboxUid *mailboxUid; // @synthesize mailboxUid=_mailboxUid;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"MailboxUid",&,V_mailboxUid,P


+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
- (void)dealloc;
- (id)initWithMailboxName:(id)arg1;
- (id)init;
- (void)setDelegate:(id)arg1;
- (void)clearDelegate:(id)arg1;
- (id)selectedGateway;
- (void)setSelectedGateway:(id)arg1;
- (void)setExists:(unsigned long long)arg1;
- (void)setUidValidity:(unsigned int)arg1;
- (void)setHasNewResponses:(BOOL)arg1;
- (void)setTotalSize:(unsigned long long)arg1 forQuotaMessageCount:(long long)arg2;
- (void)setPermanentFlags:(unsigned long long)arg1;
- (void)addResponse:(id)arg1;
- (id)removeResponse;
- (id)description;
- (BOOL)hasNewResponses;
- (id)unprocessedResponses;
- (void)setUnprocessedResponses:(id)arg1;
- (unsigned int)unseenCount;
- (void)setUnseenCount:(unsigned int)arg1;
- (unsigned int)uidValidity;
- (unsigned int)uidNext;
- (void)setUidNext:(unsigned int)arg1;
- (CDAnonymousStruct6)quotaUsage;
- (void)setQuotaUsage:(CDAnonymousStruct6)arg1;
- (unsigned long long)exists;
- (id)quotaRoots;
- (void)setQuotaRoots:(id)arg1;
- (BOOL)uidNotSticky;
- (void)setUidNotSticky:(BOOL)arg1;
- (BOOL)readOnly;
- (void)setReadOnly:(BOOL)arg1;
- (id)referenceName;
- (void)setReferenceName:(id)arg1;
- (unsigned long long)permanentFlags;
- (id)mailboxUid;
- (void)setMailboxUid:(id)arg1;

@end

