/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPCompoundDownload.h>

@class MimePart;

@interface IMAPMessageDownload : IMAPCompoundDownload
{
    id <IMAPObject> _message;
    MimePart *_topLevelPart;
    BOOL _allowsPartialDownloads;
    BOOL _writesCacheFile;
    unsigned int _usingPartialDownloads:1;
    unsigned int _startedFetch:1;
    unsigned int _fetchingBodyText:1;
    unsigned int _doneAddingSubdownloads:1;
}

@property(retain) id <IMAPObject> message;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"<IMAPObject>",&,P

@property BOOL writesCacheFile; // @synthesize writesCacheFile=_writesCacheFile;
@property BOOL allowsPartialDownloads; // @synthesize allowsPartialDownloads=_allowsPartialDownloads;
@property(retain) MimePart *topLevelPart; // @synthesize topLevelPart=_topLevelPart;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"MimePart",&,V_topLevelPart,P


- (void)dealloc;
- (id)initWithMessage:(id)arg1;
- (id)createClone;
- (id)message;
- (void)setMessage:(id)arg1;
- (id)data;
- (BOOL)isComplete;
- (void)handleFetchResult:(id)arg1;
- (void)processResults;
- (void)_addMimeSubdownloadsToPipeline:(id)arg1 withCache:(id)arg2;
- (void)addCommandsToPipeline:(id)arg1 withCache:(id)arg2;
- (BOOL)writesCacheFile;
- (void)setWritesCacheFile:(BOOL)arg1;
- (BOOL)allowsPartialDownloads;
- (void)setAllowsPartialDownloads:(BOOL)arg1;
- (id)topLevelPart;
- (void)setTopLevelPart:(id)arg1;

@end

