/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPCompoundDownload.h>

@interface IMAPAttachmentsDownload : IMAPCompoundDownload
{
    id <IMAPObject> _message;
}

@property(retain) id <IMAPObject> message; // @synthesize message=_message;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"<IMAPObject>",&,V_message,P


- (void)dealloc;
- (id)initWithLibraryMessage:(id)arg1;
- (id)createClone;
- (void)saveCompletedDownloads;
- (id)message;
- (void)setMessage:(id)arg1;

@end

