/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSString;

@interface IMAPClientFetchDataItem
{
    NSString *_commandString;
}

@property(copy) NSString *commandString; // @synthesize commandString=_commandString;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,V_commandString,P


+ (id)flagsDataItem;
+ (id)UIDDataItem;
+ (id)bodyStructureDataItem;
+ (id)internalDateDataItem;
+ (id)sizeDataItem;
- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)commandString;
- (void)setCommandString:(id)arg1;

@end

