/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/ToDoStoreReconciliationAgent.h>

@class LibraryToDoIMAPStore;

@interface IMAPToDoStoreReconciliationAgent : ToDoStoreReconciliationAgent
{
    LibraryToDoIMAPStore *_agentStore;
}

- (void)dealloc;
- (void)startAtomicReconciliationProcessForMailboxID:(long long)arg1;
- (void)finishAtomicReconciliationProcessForMailboxID:(long long)arg1;
- (void)prepareToReconcileForMailboxID:(long long)arg1;
- (void)startToReconcileForMailboxID:(long long)arg1;
- (void)applyReconcilerChangesForMailboxID:(long long)arg1;
- (void)finishReconciliationForMailboxID:(long long)arg1;
- (id)snapshotForMailboxID:(long long)arg1;
- (id)todoWithUID:(id)arg1 remoteID:(id)arg2 mailboxID:(long long)arg3;
- (void)readyToReconcile;
- (void)requestReconciliation;

@end

