/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPClientUIDOperation.h>

@class NSArray;

@interface IMAPClientUIDStoreOperation : IMAPClientUIDOperation
{
    BOOL _addFlags;
    NSArray *_serverFlags;
}

@property(retain) NSArray *serverFlags; // @synthesize serverFlags=_serverFlags;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSArray",&,V_serverFlags,P

@property BOOL addFlags; // @synthesize addFlags=_addFlags;

- (void)dealloc;
- (id)initWithMailboxName:(id)arg1 UIDs:(id)arg2 add:(BOOL)arg3 flags:(id)arg4;
- (id)initWithMailboxName:(id)arg1 range:(CDAnonymousStruct11)arg2 add:(BOOL)arg3 flags:(id)arg4;
- (id)commandTypeString;
- (id)createCommandDataForLiteralPlus:(BOOL)arg1;
- (BOOL)executeOnConnection:(id)arg1;
- (id)serverFlags;
- (void)setServerFlags:(id)arg1;
- (BOOL)addFlags;
- (void)setAddFlags:(BOOL)arg1;

@end

