/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface IMAPCommandPipeline : NSObject
{
    unsigned int _chunkSize;
    unsigned int _expectedSize;
    unsigned int _full:1;
    unsigned int _sending:1;
    NSMutableArray *_fetchUnits;
}

- (void)dealloc;
- (void)addFetchCommandForUid:(unsigned long)fp8 fetchItem:(id)fp12 expectedLength:(unsigned long)fp16;
- (unsigned long)expectedSize;
- (void)setChunkSize:(unsigned long)fp8;
- (unsigned long)chunkSize;
- (void)setFull:(BOOL)fp8;
- (BOOL)isFull;
- (void)_removeFetchUnitMatchingResponse:(id)fp8;
- (id)failureResponsesFromSendingCommandsWithConnection:(id)fp8;
- (BOOL)isSending;

@end

