/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class ActivityMonitor, IMAPClientDoneOperation, IMAPClientSelectOperation, IMAPClientSuspendOperation, IMAPGateway, NSRecursiveLock, NSString;

@interface IMAPClientOperationQueue
{
    IMAPClientDoneOperation *_doneOperation;
    IMAPClientSelectOperation *_selectOperation;
    IMAPClientSuspendOperation *_suspendOperation;
    NSRecursiveLock *_addOperationLock;
    IMAPGateway *_gateway;
    NSString *_activityName;
    ActivityMonitor *_activityMonitor;
    NSRecursiveLock *_activityMonitorLock;
    struct dispatch_source_s *_activityFinishTimer;
    BOOL _activityMonitorIsActive;
}

@property(retain) IMAPClientDoneOperation *doneOperation;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"IMAPClientDoneOperation",&,P

@property(retain) IMAPClientSelectOperation *selectOperation;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"IMAPClientSelectOperation",&,P

@property(retain) IMAPClientSuspendOperation *suspendOperation;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"IMAPClientSuspendOperation",&,P

@property(readonly, retain) ActivityMonitor *activityMonitor; // @synthesize activityMonitor=_activityMonitor;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"ActivityMonitor",R,&,V_activityMonitor,P

@property(retain) NSString *activityName; // @synthesize activityName=_activityName;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",&,V_activityName,P

@property(retain) IMAPGateway *gateway; // @synthesize gateway=_gateway;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"IMAPGateway",&,V_gateway,P

@property(retain) NSRecursiveLock *addOperationLock; // @synthesize addOperationLock=_addOperationLock;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"NSRecursiveLock",&,N,V_addOperationLock,P


- (void)dealloc;
- (id)init;
- (void)activityDidStart:(id)arg1;
- (void)_clearActivityFinishTimer;
- (void)_postDelayedActivityFinished;
- (void)activityDidFinish:(id)arg1;
- (id)selectedMailboxName;
- (id)doneOperation;
- (void)setDoneOperation:(id)arg1;
- (id)selectOperation;
- (void)setSelectOperation:(id)arg1;
- (BOOL)addClientOperation:(id)arg1 outUpdatedOperation:(id *)arg2;
- (BOOL)waitUntilOperationIsFinished:(id)arg1;
- (id)createSelectOperationForResumingIfNeeded;
- (void)changeSelectDependenciesTo:(id)arg1;
- (void)updateDoneReadiness;
- (BOOL)refreshDoneWithGateway:(id)arg1 operation:(id)arg2;
- (void)_setupDependeciesOnDone;
- (void)clearDoneWithOperation:(id)arg1;
- (BOOL)isIdle;
- (BOOL)shouldAllowIdleToExecute:(id)arg1;
- (BOOL)setupDependenciesOnSuspendCreatingIfNeeded;
- (void)suspendIfNeededAndClear:(BOOL)arg1;
- (void)setSuspendOperation:(id)arg1;
- (id)suspendOperation;
- (void)finishIdling;
- (void)refreshIdle;
- (void)_logErrorAndAbort:(id)arg1;
- (id)description;
- (id)activityMonitor;
- (id)activityName;
- (void)setActivityName:(id)arg1;
- (id)gateway;
- (void)setGateway:(id)arg1;
- (id)addOperationLock;
- (void)setAddOperationLock:(id)arg1;

@end

