/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPClientFetchOperation.h>

@class NSIndexSet;

@interface IMAPClientFetchUIDOperation : IMAPClientFetchOperation
{
    NSIndexSet *_UIDs;
}

@property(retain) NSIndexSet *UIDs; // @synthesize UIDs=_UIDs;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSIndexSet",&,V_UIDs,P


- (void)dealloc;
- (id)init;
- (id)initWithUIDs:(id)arg1;
- (id)commandTypeString;
- (id)_createMessageSetCommandString;
- (id)UIDs;
- (void)setUIDs:(id)arg1;

@end

