/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPClientMailboxOperation.h>

@class NSIndexSet;

@interface IMAPClientUIDOperation : IMAPClientMailboxOperation
{
    NSIndexSet *_UIDs;
    CDAnonymousStruct11 _range;
}

@property CDAnonymousStruct11 range; // @synthesize range=_range;
@property(retain) NSIndexSet *UIDs; // @synthesize UIDs=_UIDs;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSIndexSet",&,V_UIDs,P


+ (id)createMessageSetForRange:(CDAnonymousStruct11)arg1;
+ (id)createMessageSetForNumbers:(id)arg1 range:(struct _NSRange)arg2;
+ (id)createMessageSetForIndexSet:(id)arg1;
- (void)dealloc;
- (id)initWithMailboxName:(id)arg1 UIDs:(id)arg2;
- (id)_initWithCommandType:(int)arg1 mailboxName:(id)arg2 range:(CDAnonymousStruct11)arg3;
- (id)_initWithCommandType:(int)arg1 mailboxName:(id)arg2 UIDs:(id)arg3;
- (id)_initWithCommandType:(int)arg1 mailboxName:(id)arg2 UIDs:(id)arg3 range:(CDAnonymousStruct11)arg4;
- (id)createCommandDataForLiteralPlus:(BOOL)arg1;
- (CDAnonymousStruct11)range;
- (void)setRange:(CDAnonymousStruct11)arg1;
- (id)UIDs;
- (void)setUIDs:(id)arg1;

@end

