/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPClientUIDOperation.h>

@class NSDictionary, NSString;

@interface IMAPClientUIDCopyOperation : IMAPClientUIDOperation
{
    NSString *_copyMailboxName;
    NSString *_copyMailboxArgumentName;
    NSDictionary *_newMessageInfo;
    BOOL _shouldTryCreate;
}

@property BOOL shouldTryCreate; // @synthesize shouldTryCreate=_shouldTryCreate;
@property(retain) NSDictionary *newMessageInfo; // @synthesize newMessageInfo=_newMessageInfo;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSDictionary",&,V_newMessageInfo,P

@property(copy) NSString *copyMailboxArgumentName; // @synthesize copyMailboxArgumentName=_copyMailboxArgumentName;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,V_copyMailboxArgumentName,P

@property(copy) NSString *copyMailboxName; // @synthesize copyMailboxName=_copyMailboxName;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,V_copyMailboxName,P


- (void)dealloc;
- (id)initWithMailboxName:(id)arg1 UIDs:(id)arg2 destinationMailboxName:(id)arg3;
- (id)commandTypeString;
- (id)detailsString;
- (id)createCommandDataForLiteralPlus:(BOOL)arg1;
- (BOOL)executeOnConnection:(id)arg1;
- (BOOL)shouldTryCreate;
- (void)setShouldTryCreate:(BOOL)arg1;
- (id)newMessageInfo;
- (void)setNewMessageInfo:(id)arg1;
- (id)copyMailboxArgumentName;
- (void)setCopyMailboxArgumentName:(id)arg1;
- (id)copyMailboxName;
- (void)setCopyMailboxName:(id)arg1;

@end

