/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPConnection.h>

@interface IMAPConnection (MFPrivate)
- (BOOL)_readDataOfLength:(long long)arg1 intoData:(id)arg2 error:(id *)arg3;
- (BOOL)_isFetchResponseValid:(id)arg1;
- (BOOL)_correctMailboxIsSelectedForOperation:(id)arg1;
- (id)_responseFromSendingOperation:(id)arg1;
- (BOOL)_commandShouldBeSentAgainOnError:(int)arg1;
- (BOOL)_isTemporaryError:(id)arg1;
- (void)_setError:(id)arg1 forCommand:(id)arg2;
- (BOOL)_recordUntaggedResponse:(id)arg1 forOperation:(id)arg2;
- (BOOL)_recordUntaggedResponse:(id)arg1 forOperation:(id)arg2 exists:(unsigned long long *)arg3;
- (void)_recordResponse:(id)arg1 forOperation:(id)arg2;
- (BOOL)_recordMailboxResponse:(id)arg1 forOperation:(id)arg2;
- (BOOL)_recordMailboxResponse:(id)arg1 forOperation:(id)arg2 exists:(unsigned long long *)arg3;
@end

