/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSString, QuotaUsage;

@interface IMAPQuotaRoot
{
    NSString *_name;
    QuotaUsage *_usage;
}

@property(retain) QuotaUsage *usage; // @synthesize usage=_usage;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"QuotaUsage",&,V_usage,P

@property(copy) NSString *name; // @synthesize name=_name;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,V_name,P


- (void)dealloc;
- (id)initWithName:(id)arg1;
- (id)init;
- (void)setUsageFromResponse:(id)arg1;
- (id)description;
- (id)usage;
- (void)setUsage:(id)arg1;
- (id)name;
- (void)setName:(id)arg1;

@end

