/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPClientMailboxOperation.h>

@class NSString;

@interface IMAPClientRenameOperation : IMAPClientMailboxOperation
{
    NSString *_newMailboxName;
    NSString *_newMailboxArgumentName;
}

@property(copy) NSString *newMailboxArgumentName; // @synthesize newMailboxArgumentName=_newMailboxArgumentName;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,V_newMailboxArgumentName,P

@property(copy) NSString *newMailboxName; // @synthesize newMailboxName=_newMailboxName;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,V_newMailboxName,P


- (void)dealloc;
- (id)initWithMailboxName:(id)arg1 newMailboxName:(id)arg2;
- (id)commandTypeString;
- (id)detailsString;
- (id)createCommandDataForLiteralPlus:(BOOL)arg1;
- (id)newMailboxArgumentName;
- (void)setNewMailboxArgumentName:(id)arg1;
- (id)newMailboxName;
- (void)setNewMailboxName:(id)arg1;

@end

