/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPClientUIDOperation.h>

@class NSArray, NSMutableIndexSet;

@interface IMAPClientUIDSearchOperation : IMAPClientUIDOperation
{
    NSArray *_terms;
    NSMutableIndexSet *_matchingUIDs;
}

@property(retain) NSMutableIndexSet *matchingUIDs; // @synthesize matchingUIDs=_matchingUIDs;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSMutableIndexSet",&,V_matchingUIDs,P

@property(retain) NSArray *terms; // @synthesize terms=_terms;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSArray",&,V_terms,P


- (void)dealloc;
- (id)initWithMailboxName:(id)arg1 range:(CDAnonymousStruct11)arg2 terms:(id)arg3;
- (id)commandTypeString;
- (id)createCommandDataForLiteralPlus:(BOOL)arg1;
- (id)_createArgumentForSearchTerm:(id)arg1 isLiteral:(char *)arg2;
- (BOOL)executeOnConnection:(id)arg1;
- (id)matchingUIDs;
- (void)setMatchingUIDs:(id)arg1;
- (id)terms;
- (void)setTerms:(id)arg1;

@end

