/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPClientMailboxOperation.h>

@class NSDictionary, NSString;

@interface IMAPClientStatusOperation : IMAPClientMailboxOperation
{
    unsigned long long _dataItems;
    NSString *_dataItemsString;
    NSDictionary *_statusEntries;
}

@property(retain) NSDictionary *statusEntries; // @synthesize statusEntries=_statusEntries;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSDictionary",&,V_statusEntries,P

@property(copy) NSString *dataItemsString; // @synthesize dataItemsString=_dataItemsString;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,V_dataItemsString,P

@property unsigned long long dataItems; // @synthesize dataItems=_dataItems;

+ (id)createStringForDataItems:(unsigned long long)arg1;
- (void)dealloc;
- (id)initWithMailboxName:(id)arg1 dataItems:(unsigned long long)arg2;
- (id)commandTypeString;
- (id)createCommandDataForLiteralPlus:(BOOL)arg1;
- (BOOL)executeOnConnection:(id)arg1;
- (id)statusEntries;
- (void)setStatusEntries:(id)arg1;
- (id)dataItemsString;
- (void)setDataItemsString:(id)arg1;
- (unsigned long long)dataItems;
- (void)setDataItems:(unsigned long long)arg1;

@end

