/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPDownload.h>

@class MFError, NSMutableData, NSString;

@interface IMAPSimpleDownload : IMAPDownload
{
    NSMutableData *_mdata;
    MFError *_error;
    unsigned int _length:32;
    BOOL _knownLength;
    BOOL _complete;
    unsigned int _bytesFetched;
    NSString *_partSectionSpecifier;
    int _textSectionSpecifier;
}

@property int textSectionSpecifier; // @synthesize textSectionSpecifier=_textSectionSpecifier;
@property(retain) NSString *partSectionSpecifier; // @synthesize partSectionSpecifier=_partSectionSpecifier;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",&,V_partSectionSpecifier,P


- (id)initWithUid:(unsigned int)arg1 partSectionSpecifier:(id)arg2 textSectionSpecifier:(int)arg3 estimatedLength:(unsigned int)arg4;
- (id)initWithUid:(unsigned int)arg1 partSectionSpecifier:(id)arg2 textSectionSpecifier:(int)arg3 length:(unsigned int)arg4;
- (id)initWithUid:(unsigned int)arg1;
- (id)createClone;
- (void)dealloc;
- (unsigned int)bytesFetched;
- (unsigned int)expectedLength;
- (void)handleFetchResult:(id)arg1;
- (void)processResults;
- (void)addCommandsToPipeline:(id)arg1 withCache:(id)arg2;
- (BOOL)isComplete;
- (id)data;
- (id)error;
- (void)setError:(id)arg1;
- (int)textSectionSpecifier;
- (void)setTextSectionSpecifier:(int)arg1;
- (id)partSectionSpecifier;
- (void)setPartSectionSpecifier:(id)arg1;

@end

