/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPClientFetchOperation.h>

@interface IMAPClientFetchOperation (Internal)
+ (id)_headersToFetch;
+ (id)_fetchDataItemsForMessageSkeletonsWithHeaders:(id)arg1;
- (id)_createMessageSetCommandString;
- (id)_fetchDataItemsForMessageSkeletonsWithAdditionalHeaderFields:(id)arg1;
@end

