/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSPort;

@interface InvocationQueue
{
    NSPort *_runLoopCancelPort;
}

+ (void)cancelAllMonitoredItems;
- (id)initWithMaxConcurrentOperationCount:(long long)arg1;
- (void)dealloc;
- (void)finalize;
- (void)addInvocation:(id)arg1;
- (void)runInvocationOnQueueSynchronously:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@end

