/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/IMAPAccount.h>

@class ISS_MMMemberAccount, ISS_MMTransaction, NSDate;

@interface iToolsAccount : IMAPAccount
{
    ISS_MMMemberAccount *_dmAccount;
    ISS_MMTransaction *_primaryAddressesTransaction;
    ISS_MMTransaction *_aliasesTransaction;
    NSDate *_aliasesUpdateRequestDate;
}

@property(retain) NSDate *aliasesUpdateRequestDate; // @synthesize aliasesUpdateRequestDate=_aliasesUpdateRequestDate;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSDate",&,V_aliasesUpdateRequestDate,P

@property(retain) ISS_MMTransaction *aliasesTransaction; // @synthesize aliasesTransaction=_aliasesTransaction;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"ISS_MMTransaction",&,V_aliasesTransaction,P

@property(retain) ISS_MMTransaction *primaryAddressesTransaction; // @synthesize primaryAddressesTransaction=_primaryAddressesTransaction;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"ISS_MMTransaction",&,V_primaryAddressesTransaction,P

@property(retain) ISS_MMMemberAccount *dmAccount; // @synthesize dmAccount=_dmAccount;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"ISS_MMMemberAccount",&,V_dmAccount,P


+ (void)_initMobileMeAccount;
+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (id)createAccountWithDictionary:(id)arg1;
+ (BOOL)defaultsToSSL;
+ (id)defaultPathNameForAccountWithHostname:(id)arg1 username:(id)arg2;
+ (void)_primaryUsernameChanged:(id)arg1;
+ (id)primaryUsername;
+ (BOOL)_primaryUsernameExists;
+ (id)iToolsMailHostname;
+ (id)iToolsSMTPHostname;
- (void)dealloc;
- (void)finalize;
- (BOOL)isActive;
- (id)hostname;
- (void)setHostname:(id)arg1;
- (unsigned int)portNumber;
- (void)setPortNumber:(unsigned int)arg1;
- (id)username;
- (void)setUsername:(id)arg1;
- (id)defaultsDictionary;
- (void)setPassword:(id)arg1;
- (id)permanentPassword;
- (void)setPermanentPassword:(id)arg1;
- (id)displayName;
- (id)accountTypeString;
- (BOOL)isSyncable;
- (id)supportURLLabel;
- (id)_URLPersistenceHostname;
- (id)rawEmailAddresses;
- (id)emailAddresses;
- (id)_emailAliasesLastUpdateDate;
- (void)_setEmailAliases:(id)arg1;
- (id)deliveryAccount;
- (void)setDeliveryAccount:(id)arg1;
- (id)_replacementDeliveryAccountForDeliveryAccount:(id)arg1;
- (BOOL)_isReallyPrimaryiToolsAccount;
- (BOOL)isPrimaryiToolsAccount;
- (void)setIsPrimaryiToolsAccount:(BOOL)arg1;
- (void)_updateDMAccountAndUpdateAliases:(BOOL)arg1;
- (void)addPrimaryEmailAddresses;
- (void)updateEmailAliases;
- (void)transactionSuccessful:(id)arg1;
- (id)aliasesUpdateRequestDate;
- (void)setAliasesUpdateRequestDate:(id)arg1;
- (id)aliasesTransaction;
- (void)setAliasesTransaction:(id)arg1;
- (id)primaryAddressesTransaction;
- (void)setPrimaryAddressesTransaction:(id)arg1;
- (id)dmAccount;
- (void)setDmAccount:(id)arg1;

@end

