/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSMutableDictionary;

@interface JunkRecorder
{
    BOOL _isShort;
    BOOL _isSigned;
    long long _imageCount;
    long long _characterCount;
    double _imageToTextRatio;
    NSMutableDictionary *_imageInfos;
    double _lsmScore;
}

@property double lsmScore; // @synthesize lsmScore=_lsmScore;
@property BOOL isShort; // @synthesize isShort=_isShort;
@property BOOL isSigned; // @synthesize isSigned=_isSigned;
@property(retain) NSMutableDictionary *imageInfos; // @synthesize imageInfos=_imageInfos;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSMutableDictionary",&,V_imageInfos,P

@property double imageToTextRatio; // @synthesize imageToTextRatio=_imageToTextRatio;
@property long long characterCount; // @synthesize characterCount=_characterCount;
@property long long imageCount; // @synthesize imageCount=_imageCount;

- (id)init;
- (void)dealloc;
- (id)description;
- (double)lsmScore;
- (void)setLsmScore:(double)arg1;
- (BOOL)isShort;
- (void)setIsShort:(BOOL)arg1;
- (BOOL)isSigned;
- (void)setIsSigned:(BOOL)arg1;
- (id)imageInfos;
- (void)setImageInfos:(id)arg1;
- (double)imageToTextRatio;
- (void)setImageToTextRatio:(double)arg1;
- (long long)characterCount;
- (void)setCharacterCount:(long long)arg1;
- (long long)imageCount;
- (void)setImageCount:(long long)arg1;

@end

