/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol LibraryInterface <NSObject>
+ (long long)mailboxIDForMailboxUid:(id)arg1;
+ (id)urlForMailboxID:(long long)arg1;
+ (BOOL)addToDos:(id)arg1;
+ (BOOL)deleteToDos:(id)arg1;
+ (BOOL)updateToDos:(id)arg1;
+ (id)allToDos;
+ (id)allToDosForMailboxID:(long long)arg1;
+ (id)allToDosForDocumentID:(id)arg1;
+ (BOOL)updateToDo:(id)arg1 toRemoteID:(id)arg2;
+ (long long)toDoMailboxIdForMailAccount:(id)arg1;
+ (BOOL)addCalendars:(id)arg1;
+ (BOOL)updateCalendars:(id)arg1;
+ (BOOL)deleteCalendars:(id)arg1;
+ (id)allToDoCalendars;
+ (id)todoIDsMatchingCriterion:(id)arg1;
@end

