/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/LibraryIMAPStore.h>

@class IMAPToDoStoreReconciliationAgent, NSCondition, NSRecursiveLock;

@interface LibraryToDoIMAPStore : LibraryIMAPStore
{
    Class _libraryClass;
    IMAPToDoStoreReconciliationAgent *_reconciliationAgent;
    BOOL _isReconciling;
    NSCondition *_libraryIsUpToDateCondition;
    long long _pendingLibraryOperations;
    NSRecursiveLock *_storeIsBusy;
}

- (id)initWithCriterion:(id)arg1 mailboxUid:(id)arg2 readOnly:(BOOL)arg3 libraryClass:(Class)arg4;
- (id)initWithCriterion:(id)arg1 mailbox:(id)arg2 readOnly:(BOOL)arg3;
- (id)initWithMailboxUid:(id)arg1 readOnly:(BOOL)arg2 libraryClass:(Class)arg3;
- (void)dealloc;
- (id)mailboxUid;
- (id)messageForMessageID:(id)arg1;
- (id)messageWithLibraryID:(long long)arg1 options:(unsigned int)arg2;
- (id)lastMessageWithMessageID:(id)arg1 inMailbox:(id)arg2;
- (void)compactMessages:(id)arg1;
- (void)compactMessagesFromSyncEngine:(id)arg1;
- (unsigned int)maximumRemoteIDForMailbox:(id)arg1;
- (id)getDetailsForMessagesWithRemoteIDs:(id)arg1 fromMailbox:(id)arg2;
- (BOOL)hasCacheFileForMessage:(id)arg1 part:(id)arg2 directoryContents:(id)arg3;
- (BOOL)hasCacheFileForMessage:(id)arg1 directoryContents:(id)arg2;
- (void)compactMailbox:(id)arg1;
- (id)messagesForMailbox:(id)arg1 olderThanNumberOfDays:(long long)arg2;
- (id)messagesForMailbox:(id)arg1 where:(id)arg2 sortedBy:(id)arg3 ascending:(BOOL)arg4 options:(unsigned int)arg5;
- (id)duplicateMessages:(id)arg1 newRemoteIDs:(id)arg2 newDocumentIDs:(id)arg3 forMailbox:(id)arg4 setFlags:(unsigned long long)arg5 clearFlags:(unsigned long long)arg6 messageFlagsForMessages:(id)arg7 createNewCacheFiles:(BOOL)arg8;
- (id)duplicateMessages:(id)arg1 newRemoteIDs:(id)arg2 newDocumentIDs:(id)arg3 forMailbox:(id)arg4 setFlags:(unsigned long long)arg5 clearFlags:(unsigned long long)arg6 createNewCacheFiles:(BOOL)arg7;
- (id)messageWithRemoteID:(id)arg1 inRemoteMailbox:(id)arg2;
- (id)addMessages:(id)arg1 withMailbox:(id)arg2 fetchBodies:(BOOL)arg3 oldMessagesByNewMessage:(id)arg4;
- (id)addMessages:(id)arg1 withMailbox:(id)arg2 fetchBodies:(BOOL)arg3 isInitialImport:(BOOL)arg4 oldMessagesByNewMessage:(id)arg5 remoteIDs:(id)arg6 setFlags:(unsigned long long)arg7 clearFlags:(unsigned long long)arg8 messageFlagsForMessages:(id)arg9 copyFiles:(BOOL)arg10;
- (unsigned long long)unreadCountForMailbox:(id)arg1;
- (unsigned long long)deletedCountForMailbox:(id)arg1;
- (void)setBackgroundColorForMessages:(id)arg1 textColorForMessages:(id)arg2;
- (void)setFlagsForMessages:(id)arg1 mask:(unsigned int)arg2;
- (void)setFlagsAndColorForMessages:(id)arg1;
- (void)propagateMessagesWereAdded:(id)arg1 forIncrementalLoading:(BOOL)arg2;
- (BOOL)canSetMessageColors;
- (BOOL)messageHasBeenDeleted:(id)arg1;
- (void)deleteMessages:(id)arg1 moveToTrash:(BOOL)arg2;
- (id)setFlagsFromDictionary:(id)arg1 forMessages:(id)arg2;
- (void)addToDos:(id)arg1;
- (void)updateToDos:(id)arg1;
- (void)deleteToDos:(id)arg1;
- (void)waitForLibraryOperationsToFinish;
- (void)signalCanAcceptNewOperations;
- (void)signalEndOfLibraryOperation;
- (void)willAddMessages;
- (void)didAddMessages;
- (void)willRemoveMessages;
- (void)didRemoveMessages;
- (void)enqueuedMessageChangesInExistingRequest;
- (void)waitUntilStoreIsFree;
- (void)setStoreFree;
- (void)abandonProcessingStore;
- (void)downloadChangesFromIMAP;
- (BOOL)supportsReconciliation;
- (void)reconcile;
- (void)reconciliationFinished;
- (BOOL)isReconciling;
- (id)todoWithUID:(id)arg1 remoteID:(id)arg2 mailboxID:(long long)arg3;
- (id)libraryToDoWithRemoteID:(long long)arg1 inMailbox:(long long)arg2;
- (void)updateServerSnapshotForMailboxID:(long long)arg1;
- (id)snapshotForMailboxID:(long long)arg1;

@end

