/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/Library.h>

@interface Library (ToDoServerSnapshot)
+ (BOOL)todoUIDExists:(id)arg1 forMailboxID:(long long)arg2;
+ (id)todoUIDForRemoteID:(id)arg1 forMailboxID:(long long)arg2;
+ (id)addToDoUID:(id)arg1 withRemoteID:(id)arg2 forMailboxID:(long long)arg3;
+ (id)removeToDoUID:(id)arg1;
+ (id)removeToDoUID:(id)arg1 forMailboxID:(long long)arg2;
+ (id)setStateUsingSnapshot:(id)arg1 forMailboxID:(long long)arg2;
+ (id)snapshotForMailboxID:(long long)arg1;
+ (id)outdatedDuplicateToDosForMailboxID:(long long)arg1;
@end

