/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/ToDoAlarm.h>

#import "NSCopying-Protocol.h"

@interface LibraryToDoAlarm : ToDoAlarm <NSCopying>
{
    long long _alarmLibraryID;
    long long _todoLibraryID;
}

- (id)initWithAlarm:(id)arg1 todoLibraryID:(long long)arg2;
- (id)initWithCalAlarm:(id)arg1 todoLibraryID:(long long)arg2;
- (id)calAlarmFromToDoAlarm;
- (long long)libraryID;
- (void)setLibraryID:(long long)arg1;
- (long long)todoLibraryID;
- (void)setToDoLibraryID:(long long)arg1;
- (id)argument;
- (void)setArgument:(id)arg1;
- (unsigned int)libraryFlags;
- (void)setLibraryFlags:(unsigned int)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

