/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/LibraryToDoIMAPStore.h>

@interface LibraryToDoIMAPStore (Internal)
- (void)messagesWereRemoved:(id)arg1;
- (void)addToDosInMessages:(id)arg1;
- (id)messageFromToDo:(id)arg1;
- (void)saveToDosToIMAPServer:(id)arg1;
- (void)deleteToDosFromIMAPServer:(id)arg1;
- (void)deleteToDoWithRemoteID:(id)arg1 inMailbox:(long long)arg2;
@end

