/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/ToDo.h>

#import "LibraryObject-Protocol.h"
#import "NSCopying-Protocol.h"

@class MailboxUid, NSConditionLock, NSString;

@interface LibraryToDo : ToDo <LibraryObject, NSCopying>
{
    MailboxUid *_mailboxUid;
    int _changedLibraryProperties;
    long long _libraryID;
    long long _mailboxID;
    NSString *_remoteID;
    unsigned int _uid;
    unsigned long long _size;
    CDAnonymousStruct15 _remoteFlags;
    BOOL _imapUpdateInProgress;
    BOOL _isObservingKeyPaths;
    BOOL _isBeingChanged;
    NSConditionLock *_mailboxIDLock;
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithTitle:(id)arg1 inAccount:(id)arg2;
- (id)initWithCalTask:(id)arg1 inAccount:(id)arg2;
- (id)initWithData:(id)arg1 inAccount:(id)arg2;
- (void)_libraryToDoCommonInitWithAccount:(id)arg1;
- (id)initWithTitle:(id)arg1;
- (id)initWithCalTask:(id)arg1;
- (id)initWithData:(id)arg1;
- (unsigned long long)hash;
- (id)messageReference;
- (void)updateWithCalTask:(id)arg1;
- (id)calTaskFromToDo;
- (void)updateNonCalTaskInformationFrom:(id)arg1;
- (void)dealloc;
- (BOOL)hasChanged;
- (void)setHasNotChanged;
- (unsigned int)libraryFlags;
- (void)setLibraryFlags:(unsigned int)arg1;
- (void)setLibraryID:(long long)arg1;
- (id)account;
- (id)todoStore;
- (long long)mailboxID;
- (id)mailboxUid;
- (void)setMailboxUid:(id)arg1;
- (void)setMailboxUid:(id)arg1 mailboxID:(long long)arg2;
- (void)lockedSetMailboxID:(long long)arg1;
- (void)setCalendarID:(id)arg1;
- (id)description;
- (id)debugDescription;
- (id)richDescription;
- (id)shortDescriptionWithRemoteID;
- (unsigned long long)messageSize;
- (id)messageID;
- (BOOL)isPartial;
- (void)setIsPartial:(BOOL)arg1;
- (BOOL)partsHaveBeenCached;
- (void)setPartsHaveBeenCached:(BOOL)arg1;
- (BOOL)hasTemporaryUid;
- (void)setHasTemporaryUid:(BOOL)arg1;
- (BOOL)imapUpdateInProgress;
- (void)setIMAPUpdateInProgress:(BOOL)arg1;
- (void)mergeFromToDo:(id)arg1 overwriteDirtyProperties:(BOOL)arg2 usingCondition:(void *)arg3;
- (CDAnonymousStruct15)remoteFlags;
- (id)subject;
- (void)postToDoInfoChangedNotification:(unsigned int)arg1;
- (long long)libraryID;
- (unsigned int)uid;
- (void)setUid:(unsigned int)arg1;
- (id)remoteID;
- (void)setRemoteID:(id)arg1;
- (void)setRemoteIDFromUTF8String:(const char *)arg1;
- (int)changedLibraryProperties;
- (id)initForCopy;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)beginChanging;
- (BOOL)endChanging:(BOOL)arg1;
- (BOOL)endChanging:(BOOL)arg1 immediately:(BOOL)arg2;
- (id)mailboxName;
- (id)initForUnitTest;

@end

