/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class ActivityMonitor, NSMutableArray;

@interface LibraryThread
{
    NSMutableArray *_requests;
    ActivityMonitor *_monitor;
    struct __CFDictionary *_storeReqCounts;
}

+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (id)retain;
- (unsigned long long)retainCount;
- (void)release;
- (id)autorelease;
- (void)dealloc;
- (void)_runThread;
- (void)_routeMessagesRemovingThoseRouted:(id)arg1 fromStore:(id)arg2;
- (void)addMessages:(id)arg1 toStore:(id)arg2;
- (id)messagesBeingAddedToStore:(id)arg1;
- (BOOL)isAddingMessagesToStore:(id)arg1;

@end

