/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MailAccount.h>

@interface MailAccount (Internal)
+ (void)setAllEmailAddresses:(id)arg1 withFullUserNames:(id)arg2;
+ (BOOL)_mailboxListingNotificationAreEnabled;
+ (void)_disableMailboxListingNotifications;
+ (void)_enableMailboxListingNotifications:(BOOL)arg1;
+ (id)_accountWithPath:(id)arg1;
+ (void)_postMailAccountsHaveChanged;
+ (void)resetAccountExistsForSigning;
+ (void)_setOutboxMailboxUid:(id)arg1;
+ (id)_outboxMailboxUid;
+ (id)keyPathsForValuesAffecting_URLPersistenceHostname;
- (BOOL)_setPath:(id)arg1;
- (void)setIsActive:(BOOL)arg1;
- (void)_postMailAccountsHaveChangedIfNeeded;
- (id)_pathComponentForUidName:(id)arg1;
- (id)_uidNameForPathComponent:(id)arg1;
- (void)_readCustomInfoFromMailboxCache:(id)arg1;
- (void)_writeCustomInfoToMailboxCache:(id)arg1;
- (id)_copyMailboxUidWithParent:(id)arg1 name:(id)arg2 attributes:(unsigned long long)arg3 existingMailboxUid:(id)arg4;
- (void)_synchronouslyLoadListingForParent:(id)arg1;
- (void)_loadMailboxListingIntoCache:(id)arg1 attributes:(unsigned long long)arg2 parent:(id)arg3;
- (void)_mailboxesWereRemovedFromTree:(id)arg1 withFileSystemPaths:(id)arg2;
- (BOOL)_usesMailboxCache;
- (BOOL)_readMailboxCache;
- (void)_synchronizeMailboxListWithFileSystemBeforeImport:(BOOL)arg1;
- (void)_synchronizeMailboxListWithFileSystem;
- (void)_synchronizeMailboxListWithFileSystemBeforeImport;
- (void)_finishSynchronizingMailboxesAfterImport;
- (void)_loadEntriesFromFileSystemPath:(id)arg1 parent:(id)arg2;
- (void)_writeMailboxCache;
- (id)_insertMailbox:(id)arg1 intoParent:(id)arg2 withName:(id)arg3;
- (BOOL)_setChildren:(id)arg1 forMailboxUid:(id)arg2;
- (BOOL)_setChildren:(id)arg1 addedChild:(id)arg2 forMailboxUid:(id)arg3;
- (BOOL)_deleteMailbox:(id)arg1;
- (id)description;
- (void)_fetchSynchronouslyIfNeeded;
- (void)_backgroundFetchCompletedCount:(unsigned long long)arg1;
- (void)_backgroundFetchCompleted;
- (void)_emptySpecialMailboxesIfNeeded;
- (void)_emptySpecialMailboxesIfNeededForQuit:(BOOL)arg1;
- (void)_clearAllPathBasedCachesAndDelete:(BOOL)arg1;
- (id)_defaultSpecialMailboxNameForType:(int)arg1;
- (BOOL)_assignSpecialMailboxToAppropriateIvar:(id)arg1 forType:(int)arg2;
- (void)_setSpecialMailboxName:(id)arg1 forType:(int)arg2;
- (void)_setSpecialMailbox:(id)arg1 forType:(int)arg2;
- (id)_specialMailboxNameForType:(int)arg1;
- (id)_specialMailboxUidWithType:(int)arg1 create:(BOOL)arg2;
- (BOOL)_canEmptyMessagesFromMailboxUid:(id)arg1;
- (BOOL)_shouldLogDeleteActivity;
- (id)_infoForMatchingURL:(id)arg1;
- (id)_URLPersistenceScheme;
- (id)_URLInternalConnectionScheme;
- (id)_URLExternalConnectionScheme;
- (id)_URLPersistenceHostname;
- (id)_URLForInfo:(id)arg1;
- (id)_mailboxPathPrefix;
- (id)rootMailboxUidEvenIfInactive:(BOOL)arg1;
- (id)allMailboxUidsEvenIfInactive:(BOOL)arg1;
@end

