/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MailboxUid.h>

@interface MailboxUid (ScriptingSupport)
- (id)objectSpecifier;
- (id)applescriptContainer;
- (id)applescriptChildren;
- (id)messages;
- (void)removeFromMessagesAtIndex:(unsigned long long)arg1;
- (id)mailboxName;
- (void)setMailboxName:(id)arg1;
- (id)valueInMessagesWithUniqueID:(id)arg1;
@end

