/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class MailboxUid;

@interface MailboxUidWrapper
{
    MailboxUid *_wrappedMailbox;
    BOOL _hasAlternateParent;
}

- (id)initWithMailboxUid:(id)arg1;
- (void)dealloc;
- (void)setRepresentedMailbox:(id)arg1;
- (id)representedMailbox;
- (BOOL)hasAlternateParent;
- (void)setHasAlternateParent:(BOOL)arg1;
- (void)_unreadCountChanged:(id)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (id)tildeAbbreviatedPath;

@end

