/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MailAccount.h>

@class NSString;

@interface MailCalDAVAccount : MailAccount
{
    NSString *_title;
    BOOL _isBeingDeleted;
}

+ (id)defaultPathNameForAccount;
+ (id)accountTypeString;
- (void)cleanupCalDAVAccountTitleForURLAndPath:(id)arg1;
- (id)initWithTitle:(id)arg1 groupID:(id)arg2;
- (void)dealloc;
- (BOOL)isActive;
- (BOOL)isSyncable;
- (id)uniqueId;
- (Class)storeClass;
- (Class)todoStoreClass;
- (BOOL)supportsNotes;
- (BOOL)supportsToDos;
- (BOOL)shouldShowNotesInInbox;
- (id)mailboxPathExtension;
- (BOOL)synchronizesDataWithServer;
- (BOOL)allowsCalendarCreation;
- (BOOL)isEditableByUser;
- (BOOL)canParticipateInRules;
- (BOOL)providesAccountInformation;
- (BOOL)isZeroConfiguration;
- (BOOL)isRemoteAccount;
- (BOOL)hasTrashMailbox;
- (BOOL)supportsAppleScript;
- (BOOL)canMailboxBeDeleted:(id)arg1;
- (BOOL)canCreateNewMailboxes;
- (id)hostname;
- (BOOL)canFetch;
- (BOOL)shouldAutoFetch;
- (BOOL)isOffline;
- (BOOL)canGoOffline;
- (BOOL)shouldMoveDeletedMessagesToTrash;
- (BOOL)canMoveDeletedMessagesToTrash;
- (id)path;
- (void)setIsOffline:(BOOL)arg1;
- (BOOL)rootChildrenCanBePromoted;
- (id)trashMailboxUidCreateIfNeeded:(BOOL)arg1;
- (id)_URLPersistenceScheme;
- (id)_specialMailboxNameForType:(int)arg1;
- (BOOL)deleteMailbox:(id)arg1;
- (id)_infoForMatchingURL:(id)arg1;
- (void)deleteAccount;
- (BOOL)isBeingDeleted;

@end

