/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MailAccount.h>

@interface MailAccount (ScriptingSupport)
- (id)indicesOfObjectsByEvaluatingObjectSpecifier:(id)arg1;
- (id)mailboxes;
- (void)replaceInMailboxes:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)insertInMailboxes:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)insertInMailboxes:(id)arg1;
- (void)removeFromMailboxesAtIndex:(unsigned long long)arg1;
- (BOOL)emptyTrashOnQuit;
- (void)setEmptyTrashOnQuit:(BOOL)arg1;
- (BOOL)emptySentMessagesOnQuit;
- (void)setEmptySentMessagesOnQuit:(BOOL)arg1;
- (BOOL)emptyJunkOnQuit;
- (void)setEmptyJunkOnQuit:(BOOL)arg1;
@end

