/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/PerformanceLogger.h>

@class NSMutableArray;

@interface MainPerformanceLogger : PerformanceLogger
{
    NSMutableArray *_subtests;
}

@property(retain) NSMutableArray *subtests; // @synthesize subtests=_subtests;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSMutableArray",&,V_subtests,P


+ (void)startLoggingForArea:(id)arg1 test:(id)arg2;
+ (void)stopLoggingForArea:(id)arg1 test:(id)arg2;
+ (void)logMarker:(id)arg1;
- (void)dealloc;
- (id)addLoggerForSubtest:(id)arg1;
- (id)description;
- (id)subtests;
- (void)setSubtests:(id)arg1;

@end

