/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class MessageCriterion, NSMutableSet;

@interface MatadorResultCollector : NSObject
{
    MessageCriterion *criterion;
    MessageCriterion *resultParent;
    id target;
    struct __MDQuery *query;
    NSMutableSet *seenItems;
    unsigned int options;
}

- (id)initWithCriterion:(id)fp8 resultParentCriterion:(id)fp12 target:(id)fp16 query:(struct __MDQuery *)fp20;
- (void)dealloc;
- (void)finalize;

@end

