/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSObject.h"

@class MessageStore;

@interface MboxIndex : NSObject
{
    MessageStore *_store;
    struct __SKIndex *_skIndex;
    struct __SKDocument *_bodyParent;
    struct __SKDocument *_headerParent;
    struct {
        unsigned int isValid:1;
        unsigned int hasWriteAccess:1;
        unsigned int hasUnsavedChanges:1;
        unsigned int reserved:29;
    } _flags;
}

+ (BOOL)indexForMailboxIsValid:(id)fp8;
+ (void)setIndexForMailbox:(id)fp8 isValid:(BOOL)fp12;
+ (void)deleteIndexFilesForMailbox:(id)fp8;
+ (id)flagFilePathForMailbox:(id)fp8;
+ (id)indexFilePathForMailbox:(id)fp8;
+ (void)removeLeftoverIndexFilesForMailbox:(id)fp8;
- (id)_openVersionOfIndexPath:(id)fp8;
- (id)_validFlagFilePath;
- (void)_updateValidFlagFile;
- (BOOL)_validFlagFileState;
- (id)initWithStore:(id)fp8 writeAccess:(BOOL)fp12;
- (BOOL)isValid;
- (void)setIsValid:(BOOL)fp8;
- (BOOL)hasWriteAccess;
- (void)dealloc;
- (BOOL)update;
- (BOOL)_shouldCompact;
- (BOOL)flushToDisk;
- (BOOL)_indexString:(id)fp8 underParent:(struct __SKDocument *)fp12 forMessageId:(id)fp16;
- (void)addMessage:(id)fp8;
- (void)_removeMessageByID:(id)fp8;
- (void)removeMessage:(id)fp8;
- (unsigned int)count;
- (id)_sanitizeBooleanSearchString:(id)fp8;
- (id)messagesMatchingQuery:(id)fp8 ranks:(id *)fp12 errorString:(id *)fp16;
- (id)messageIDsMatchingQuery:(id)fp8 ranks:(id *)fp12 errorString:(id *)fp16;

@end

