/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "MessageConsumer-Protocol.h"

@class NSMutableArray;

@interface MessageCollector <MessageConsumer>
{
    NSMutableArray *messages;
    long long accessNumber;
    BOOL didCancel;
}

- (id)init;
- (void)dealloc;
- (id)messages;
- (void)newMessagesAvailable:(id)arg1;
- (void)newMessagesAvailable:(id)arg1 ranks:(id)arg2;
- (BOOL)shouldCancel;
- (BOOL)didCancel;

@end

