/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSArray;

@interface MessageSigner
{
    int _verificationStatus;
    NSArray *_certificates;
    struct OpaqueSecTrustRef *_trust;
    unsigned int _trustResult;
}

- (void)dealloc;
- (id)initWithCmsSignerInfo:(struct SecCmsSignerInfoStr *)arg1 trust:(struct OpaqueSecTrustRef *)arg2;
- (id)description;
- (id)label;
- (id)commonName;
- (id)emailAddress;
- (struct OpaqueSecTrustRef *)trust;
- (struct OpaqueSecCertificateRef *)signingCertificate;
- (id)certificates;
- (id)signingError;

@end

