/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MessageCriterion.h>

@interface MessageCriterion (ApplescriptRuleCriterion)
- (int)ruleType;
- (void)setRuleType:(int)arg1;
- (id)ruleHeader;
- (void)setRuleHeader:(id)arg1;
- (int)ruleQualifier;
- (void)setRuleQualifier:(int)arg1;
- (id)ruleExpression;
- (void)setRuleExpression:(id)arg1;
@end

