/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MessageStore.h>

@interface MessageStore (MessageFrameworkOnly)
+ (void)_autosaveMessageStore:(void *)arg1;
- (void)_cancelAutosave;
- (void)_setNeedsAutosave;
- (id)_fetchHeaderDataForMessage:(id)arg1 fetchIfNotAvailable:(BOOL)arg2;
- (id)_fetchBodyDataForMessage:(id)arg1 andHeaderDataIfReadilyAvailable:(id *)arg2 fetchIfNotAvailable:(BOOL)arg3;
- (id)_fetchBodyForMessage:(id)arg1 updateFlags:(BOOL)arg2;
- (BOOL)_shouldCallCompactWhenClosing;
- (BOOL)_isReadyToBeInvalidated;
- (void)_saveChanges;
- (BOOL)setStoreState:(int)arg1 fromState:(int)arg2;
- (int)storeState;
- (void)_invalidate;
- (void)_invalidateInBackground;
- (void)_countUnreadAndDeletedInMessages:(id)arg1;
- (id)_lockFilePath;
- (BOOL)_acquireLockFile;
- (void)_removeLockFile;
- (void)_flushAllCaches;
- (void)_flushAllMessageData;
- (void)_rebuildTableOfContentsSynchronously;
- (void)updateBodyFlagsForMessage:(id)arg1 body:(id)arg2;
- (id)_setOrGetBody:(id)arg1 forMessage:(id)arg2 updateFlags:(BOOL)arg3;
- (void)_invalidateObjectCachesForKey:(id)arg1;
- (id)_setOrGetValue:(id)arg1 forKey:(id)arg2 inCache:(id *)arg3;
- (id)_cachedBodyForMessage:(id)arg1 valueIfNotPresent:(id)arg2;
- (id)_cachedHeadersForMessage:(id)arg1 valueIfNotPresent:(id)arg2;
- (id)_cachedBodyDataForMessage:(id)arg1 valueIfNotPresent:(id)arg2;
- (id)_cachedHeaderDataForMessage:(id)arg1 valueIfNotPresent:(id)arg2;
- (void)updateMessageColorsSynchronouslyForMessages:(id)arg1 postingNotification:(BOOL)arg2;
- (void)updateMessages:(id)arg1 updateColor:(BOOL)arg2 updateNumberOfAttachments:(BOOL)arg3;
- (void)_setBackgroundColorForMessages:(id)arg1 textColorForMessages:(id)arg2;
- (void)_invalidateColorForAllMessages;
- (void)_setFlagsForMessages:(id)arg1 mask:(unsigned int)arg2;
- (void)_setFlagsAndColorForMessages:(id)arg1;
- (void)messagesWereAdded:(id)arg1 forIncrementalLoading:(BOOL)arg2;
- (BOOL)_updateFlagForMessage:(id)arg1 key:(id)arg2 value:(BOOL)arg3;
@end

