/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class Message;

@interface MessageBody
{
    BOOL _hideCalendarMimePart;
    Message *_message;
    long long _messageID;
}

@property Message *message;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"Message",P

@property(readonly) BOOL isSignedByMe;
@property BOOL hideCalendarMimePart; // @synthesize hideCalendarMimePart=_hideCalendarMimePart;
@property Message *actualMessage; // @synthesize actualMessage=_message;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"Message",V_message,P

@property long long messageID; // @synthesize messageID=_messageID;

- (id)init;
- (void)setMessage:(id)arg1;
- (id)message;
- (id)attributedString;
- (BOOL)isHTML;
- (BOOL)isRich;
- (BOOL)isSignedByMe;
- (void)calculateNumberOfAttachmentsIfNeeded;
- (void)calculateNumberOfAttachmentsDecodeIfNeeded;
- (unsigned int)numberOfAttachmentsSigned:(char *)arg1 encrypted:(char *)arg2;
- (id)attachments;
- (id)attachmentViewControllers;
- (id)attachmentFilenames;
- (id)textHtmlPart;
- (id)webArchive;
- (void)dealloc;
- (BOOL)hideCalendarMimePart;
- (void)setHideCalendarMimePart:(BOOL)arg1;
- (id)actualMessage;
- (void)setActualMessage:(id)arg1;
- (long long)messageID;
- (void)setMessageID:(long long)arg1;

@end

