/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSString;

@interface MessageCriterion : NSObject
{
    NSString *_uniqueId;
    NSString *_criterionIdentifier;
    NSString *_expression;
    int _qualifier;
    NSString *_groupUniqueId;
    NSArray *_criteria;
    int _dateUnitType;
    int specialMailboxType;
    NSString *_name;
    unsigned int _allCriteriaMustBeSatisfied:1;
    unsigned int _dateIsRelative:1;
    NSString *_cachedAccountURLForSyncConflictResolution;
}

+ (void)initialize;
+ (id)criteriaFromDefaultsArray:(id)fp8;
+ (id)criteriaFromDefaultsArray:(id)fp8 removingRecognizedKeys:(BOOL)fp12;
+ (id)defaultsArrayFromCriteria:(id)fp8;
+ (void)_updateAddressComments:(id)fp8;
+ (int)criterionTypeForString:(id)fp8;
+ (id)stringForCriterionType:(int)fp8;
- (id)init;
- (id)initWithCriterion:(id)fp8 expression:(id)fp12;
- (id)initWithDictionary:(id)fp8;
- (id)initWithDictionary:(id)fp8 andRemoveRecognizedKeysIfMutable:(BOOL)fp12;
- (void)dealloc;
- (void)finalize;
- (BOOL)isEqual:(id)fp8;
- (id)descriptionWithDepth:(unsigned int)fp8;
- (id)description;
- (id)dictionaryRepresentation;
- (int)criterionType;
- (void)setCriterionType:(int)fp8;
- (id)criterionIdentifier;
- (void)setCriterionIdentifier:(id)fp8;
- (id)_qualifierString;
- (int)qualifier;
- (void)setQualifier:(int)fp8;
- (id)expression;
- (void)setExpression:(id)fp8;
- (id)groupUniqueId;
- (void)setGroupUniqueId:(id)fp8;
- (id)recursiveGroupUniqueIds;
- (id)name;
- (void)setName:(id)fp8;
- (id)_headersRequiredForEvaluation;
- (void)addHeadersRequiredForRoutingToArray:(id)fp8;
- (BOOL)_evaluateDateCriterion:(id)fp8;
- (BOOL)_evaluateHeaderCriterion:(id)fp8;
- (BOOL)_evaluateBodyCriterion:(id)fp8;
- (BOOL)_evaluateAddressBookCriterion:(id)fp8;
- (BOOL)_doesGroup:(id)fp8 containSender:(id)fp12;
- (BOOL)_evaluateMemberOfGroupCriterion:(id)fp8;
- (BOOL)_evaluateAccountCriterion:(id)fp8;
- (BOOL)_evaluateAddressHistoryCriterion:(id)fp8;
- (BOOL)_evaluateFullNameCriterion:(id)fp8;
- (BOOL)_evaluateIsDigitallySignedCriterion:(id)fp8;
- (BOOL)_evaluateIsEncryptedCriterion:(id)fp8;
- (BOOL)_evaluatePriorityIsNormalCriterion:(id)fp8;
- (BOOL)_evaluatePriorityIsHighCriterion:(id)fp8;
- (BOOL)_evaluatePriorityIsLowCriterion:(id)fp8;
- (BOOL)_evaluateJunkMailCriterion:(id)fp8;
- (BOOL)_evaluateAttachmentCriterion:(id)fp8;
- (BOOL)doesMessageSatisfyCriterion:(id)fp8;
- (int)messageRuleQualifierForString:(id)fp8;
- (id)stringForMessageRuleQualifier:(int)fp8;
- (BOOL)hasExpression;
- (BOOL)hasQualifier;
- (BOOL)isValid:(id *)fp8;
- (id)criteria;
- (void)setCriteria:(id)fp8;
- (BOOL)allCriteriaMustBeSatisfied;
- (void)setAllCriteriaMustBeSatisfied:(BOOL)fp8;
- (int)dateUnits;
- (void)setDateUnits:(int)fp8;
- (BOOL)dateIsRelative;
- (void)setDateIsRelative:(BOOL)fp8;
- (int)specialMailboxType;
- (void)setSpecialMailboxType:(int)fp8;
- (BOOL)containsBodyCriterion;

@end

