/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MessageRule.h>

@interface MessageRule (Applescript)
- (void)updateIsActive;
- (int)actionColorMessage;
- (void)setActionColorMessage:(int)arg1;
- (int)highlightColorValue:(id)arg1;
- (BOOL)actionDeleteMessage;
- (void)setActionDeleteMessage:(BOOL)arg1;
- (id)actionForwardToAddress;
- (void)setActionForwardToAddress:(id)arg1;
- (id)actionForwardText;
- (void)setActionForwardText:(id)arg1;
- (BOOL)actionMarkAsFlagged;
- (void)setActionMarkAsFlagged:(BOOL)arg1;
- (BOOL)actionMarkAsRead;
- (void)setActionMarkAsRead:(BOOL)arg1;
- (id)actionPlaySound;
- (void)setActionPlaySound:(id)arg1;
- (id)actionRedirectToAddress;
- (void)setActionRedirectToAddress:(id)arg1;
- (id)actionReplyText;
- (void)setActionReplyText:(id)arg1;
- (id)actionRunApplescript;
- (void)setActionRunApplescript:(id)arg1;
- (id)ruleDescription;
- (void)setRuleDescription:(id)arg1;
- (void)insertInCriteria:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)insertInCriteria:(id)arg1;
- (void)removeFromCriteriaAtIndex:(unsigned long long)arg1;
- (void)setAddress:(id)arg1 forResponseType:(int)arg2;
@end

