/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class MessageAttachment, NSArray, NSImage, NSMutableArray;

@interface MessageAttachmentViewController
{
    MessageAttachment *_attachment;
    NSMutableArray *_attachmentViews;
    BOOL _canBeDisplayedInline;
    BOOL _canBeDisplayedInRegisteredViewer;
    struct CGSize _originalImageSize;
    BOOL _originalImageSizeHasBeenComputed;
    NSImage *_inlineImage;
    BOOL _isBeingDisplayedInline;
    long long _domNodeWidth;
    long long _domNodeHeight;
    struct CGSize _targetImageSize;
    struct CGSize _previousTargetImageSize;
    BOOL _isImageBeingResized;
}

@property(readonly) NSArray *attachmentViews;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSArray",R,P

@property BOOL isBeingDisplayedInline;
@property(readonly) struct CGSize targetImageSize; // @synthesize targetImageSize=_targetImageSize;
@property long long domNodeHeight; // @synthesize domNodeHeight=_domNodeHeight;
@property long long domNodeWidth; // @synthesize domNodeWidth=_domNodeWidth;
@property(readonly, retain) MessageAttachment *attachment; // @synthesize attachment=_attachment;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"MessageAttachment",R,&,V_attachment,P


+ (void)initialize;
+ (void)registerViewingClass:(Class)arg1 forMimeTypes:(id)arg2;
+ (Class)_viewProviderClassForMimeType:(id)arg1;
- (id)init;
- (id)initWithMessageAttachment:(id)arg1;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)attachmentViews;
- (void)addAttachmentView:(id)arg1;
- (BOOL)isBeingDisplayedInline;
- (void)setIsBeingDisplayedInline:(BOOL)arg1;
- (void)setCanBeDisplayedInline:(BOOL)arg1;
- (BOOL)canBeDisplayedInline;
- (BOOL)shouldBeDisplayedInlineByDefault;
- (BOOL)shouldDownloadAttachmentOnDisplay;
- (struct CGSize)originalImageSizeWithOriginalImage:(id)arg1;
- (struct CGSize)targetImageSize;
- (void)resizingStarted:(struct CGSize)arg1;
- (void)resizingFinished:(id)arg1 imageSize:(struct CGSize)arg2 fileExtension:(id)arg3 fileType:(unsigned int)arg4 maxImageSize:(struct CGSize)arg5;
- (id)inlineImage;
- (id)iconImage;
- (void)imageDataDidChange:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)description;
- (long long)domNodeHeight;
- (void)setDomNodeHeight:(long long)arg1;
- (long long)domNodeWidth;
- (void)setDomNodeWidth:(long long)arg1;
- (id)attachment;

@end

