/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSCoding-Protocol.h"

@interface MessageFlags <NSCoding>
{
    unsigned int realFlags;
}

@property unsigned int realFlags; // @synthesize realFlags;
// Preceeding property had unknown attributes: N
// Original attribute string: TI,N,VrealFlags


- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (unsigned int)realFlags;
- (void)setRealFlags:(unsigned int)arg1;

@end

