/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

//#import <Message/MessageStore.h>
#import <MessageStore.h>

@interface MessageStore (Indexing)
- (BOOL)allowsIndexing;
- (BOOL)isIndexed;
- (BOOL)indexIsValid;
- (void)updateIndex;
- (id)_index;
- (void)openIndexWithWriteAccess:(BOOL)fp8;
- (void)checkForValidIndex;
- (void)closeIndex;
- (void)_fullUpdateIndexAsynchronously;
- (void)_setNeedsToUpdateIndex;
- (void)_addMessagesToIndex:(id)fp8;
- (void)_removeMessagesFromIndex:(id)fp8;
- (void)stopUpdatingIndex;
- (void)handleUpdatingFinished;
- (void)_prepareIndexForUpdate;
- (void)_updateIndex;
- (void)_fullUpdateOfIndex;
- (void)_writeUpdatedIndexToDisk;
- (id)indexedSearchFor:(id)fp8 ranks:(id *)fp12 errorString:(id *)fp16;
- (id)cheapIndexedSearchFor:(id)fp8 ranks:(id *)fp12 errorString:(id *)fp16;
- (void)invalidateIndex;
- (void)_invalidateIndex;
- (BOOL)_isUpdatingIndex;
@end

