/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "ReconciliationAgent-Protocol.h"
#import "ToDosCacheListener-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet, NSRecursiveLock, NSTimer, ToDoCalendars, ToDoChangesQueue, ToDosCache;

@interface MetadataManager <ToDosCacheListener, ReconciliationAgent>
{
    id <CalendarStoreConduit> _calendarStore;
    Class _libraryClass;
    NSMutableArray *_searchStores;
    NSMutableArray *_reconcilingIDs;
    NSRecursiveLock *_lock;
    ToDoChangesQueue *_localChangesQueue;
    ToDoChangesQueue *_calendarStoreChangesQueue;
    NSTimer *_changesTimer;
    ToDosCache *_todosCache;
    ToDoCalendars *_todoCalendars;
    NSMutableDictionary *_reconciliationAddsByMailboxID;
    NSMutableDictionary *_reconciliationUpdatesByMailboxID;
    NSMutableDictionary *_reconciliationDeletesByMailboxID;
    NSMutableSet *_updatedToDoIDSForReconciler;
    NSMutableSet *_todosToNotUpdate;
}

+ (void)initialize;
+ (id)sharedInstance;
+ (BOOL)isReady;
- (id)metadataInvocationQueue;
- (void)_addInvocationToQueue:(id)arg1;
- (id)initWithCalendarStoreConduitClass:(Class)arg1 libraryClass:(Class)arg2 todoCalendars:(id)arg3;
- (void)dealloc;
- (void)finalize;
- (BOOL)canSyncWithIMAP;
- (BOOL)canSyncWithCalendarStore;
- (void)todoAddedToCache:(id)arg1;
- (void)todoRemovedFromCache:(id)arg1;
- (BOOL)isReconcilingMailboxID:(long long)arg1;
- (BOOL)setReconcilingFlag:(BOOL)arg1 forMailboxID:(long long)arg2;
- (void)startAtomicReconciliationProcessForMailboxID:(long long)arg1;
- (void)finishAtomicReconciliationProcessForMailboxID:(long long)arg1;
- (void)prepareToReconcileForMailboxID:(long long)arg1;
- (void)startToReconcileForMailboxID:(long long)arg1;
- (void)applyReconcilerChangesForMailboxID:(long long)arg1;
- (void)finishReconciliationForMailboxID:(long long)arg1;
- (id)snapshotForMailboxID:(long long)arg1;
- (id)todoWithUID:(id)arg1 remoteID:(id)arg2 mailboxID:(long long)arg3;
- (void)processAdds:(id)arg1 updates:(id)arg2 deletes:(id)arg3 mailboxID:(long long)arg4;

@end

