/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MetadataManager.h>

@interface MetadataManager (ToDoManagerInternal)
- (void)updateRegisteredSearchStores;
- (void)disableUpdatesForToDoID:(id)arg1;
- (void)enableUpdatesForToDoID:(id)arg1;
- (BOOL)shouldUpdateToDoWithID:(id)arg1;
- (void)mergeToDo:(id)arg1 intoCachedToDo:(id)arg2;
- (void)processPendingCommits:(id)arg1;
- (id)changesTimer;
- (void)setChangesTimer:(id)arg1;
- (void)scheduleChangesTimer;
- (void)commitAddedToDos:(id)arg1;
- (void)addToDos:(id)arg1 reflectToCalendarStore:(BOOL)arg2 fromReconciliation:(BOOL)arg3;
- (void)commitDeletedToDos:(id)arg1;
- (void)deleteToDos:(id)arg1 reflectToCalendarStore:(BOOL)arg2 fromReconciliation:(BOOL)arg3;
- (void)deleteToDosWithIDs:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)deleteToDosInCalendarsWithIDs:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)commitUpdatedToDos:(id)arg1;
- (void)updateToDos:(id)arg1 reflectToCalendarStore:(BOOL)arg2 fromReconciliation:(BOOL)arg3;
- (void)todosChangedInCalendarStore:(id)arg1;
- (void)commitDateStampUpdatedInToDos:(id)arg1;
- (void)todosDateStampUpdatedInCalendarStore:(id)arg1;
- (void)calendarsChangedInCalendarStore:(id)arg1;
- (void)groupsChangedInCalendarStore:(id)arg1;
- (void)deleteGroupsAndTheirContents:(id)arg1;
- (void)addToDosToCalendarStore:(id)arg1;
- (void)updateToDosInCalendarStore:(id)arg1;
- (void)removeToDosFromCalendarStore:(id)arg1;
- (void)addCalendarsToCalendarStore:(id)arg1;
- (void)updateCalendarsInCalendarStore:(id)arg1;
- (void)deleteCalendarsFromCalendarStore:(id)arg1;
- (void)commitAddedCalendars:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)addCalendars:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)commitUpdatedCalendars:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)updateCalendars:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)commitDeletedCalendars:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)deleteCalendars:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)setCalendarInNewToDo:(id)arg1;
- (id)findCorrectCalendar:(id)arg1 forAccount:(id)arg2;
- (void)getAllCalendarStoreData;
- (void)todoDidChange:(id)arg1;
- (void)inconsistentCalendarFoundByCalendarStore:(id)arg1;
- (void)inconsistentToDoFoundByCalendarStore:(id)arg1;
- (void)_cleanupInconsistencies;
- (void)_cleanupAllInformationForAccount:(id)arg1 mailbox:(id)arg2;
@end

