/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSArray;

@interface MetadataLogger
{
    BOOL _logiCalToDoSync;
    BOOL _logStoresToDoSync;
    BOOL _logInternal;
    BOOL _logCommits;
    BOOL _logReconciler;
    NSArray *_logToDoActivityOnHost;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)logToDos:(id)arg1;
- (void)logCalendars:(id)arg1;
- (void)addingToDos:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)deletingToDos:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)updatingToDos:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)commitAddingToDos:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)commitDeletingToDos:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)commitUpdatingToDos:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)toDosFromIMAP:(id)arg1;
- (void)toDosFromiCal:(id)arg1;
- (void)messageNotToDo:(id)arg1;
- (void)updatingToDoWithID:(id)arg1 newRemoteID:(id)arg2;
- (void)imapToDosToInsert:(id)arg1 imapToDosToUpdate:(id)arg2;
- (void)libraryToDoStore:(id)arg1 isAddingToDos:(id)arg2;
- (void)libraryToDoStore:(id)arg1 isUpdatingToDos:(id)arg2;
- (void)libraryToDoStore:(id)arg1 isDeletingToDos:(id)arg2;
- (void)libraryToDoIMAPStore:(id)arg1 isAddingToDos:(id)arg2;
- (void)libraryToDoIMAPStore:(id)arg1 isUpdatingToDos:(id)arg2;
- (void)libraryToDoIMAPStore:(id)arg1 isDeletingToDos:(id)arg2;
- (void)startingReconciliationForMailbox:(long long)arg1 requester:(id)arg2;
- (void)finishedReconciliationForMailbox:(long long)arg1 requester:(id)arg2;
- (void)storeWithMailboxID:(long long)arg1 hasAdds:(id)arg2 updates:(id)arg3 deletes:(id)arg4;
- (void)cacheWithMailboxID:(long long)arg1 hasAdds:(id)arg2 updates:(id)arg3 deletes:(id)arg4;
- (void)analyzerWorkingWithStoreSnapshot:(id)arg1 referenceSnapshot:(id)arg2 cacheSnapshot:(id)arg3;
- (void)aboutToAnalyzeDifferenceTable:(id)arg1;
- (void)processedDifferenceTableExpression:(id)arg1 result:(id)arg2;
- (void)calendarsFromiCal:(id)arg1;
- (void)addingCalendars:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)updatingCalendars:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (void)deletingCalendars:(id)arg1 reflectToCalendarStore:(BOOL)arg2;
- (unsigned long long)nextCommandNumber;

@end

