/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MetadataManager.h>

@interface MetadataManager (AccountStatus)
- (void)_accountInfoDidChange:(id)arg1;
- (void)_accountWillBeDeleted:(id)arg1;
- (void)_accountWillBeDisabled:(id)arg1;
- (void)_accountWillBeEnabled:(id)arg1;
@end

