/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <Message/IMAPAccount.h>

@class MFAosSmtpAccount;

@interface MFAosImapAccount : IMAPAccount
{
    id _aoskitLock;
    struct AOSAccount *_aoskitAccount;
    struct AOSTransaction *_mailPropertiesTransaction;
    struct AOSTransaction *_primaryAddressesTransaction;
    struct AOSTransaction *_aliasesTransaction;
    struct AOSTransaction *_editAliasesURLTransaction;
    MFAosSmtpAccount *_aosSmtpAccount;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
+ (id)newAccountFromMobileMeSystemPreferences;
+ (BOOL)defaultsToSSL;
+ (id)defaultPathNameForAccount;
+ (id)defaultPathNameForAccountWithHostname:(id)arg1 username:(id)arg2;
+ (void)updateAllEmailAliases:(BOOL)arg1;
- (id)initWithAccountInfo:(id)arg1;
- (void)dealloc;
- (void)finalize;
- (void)_setAccountInfo:(id)arg1;
- (void)completeDeferredInitialization;
- (id)hostname;
- (void)setHostname:(id)arg1;
- (void)setUsername:(id)arg1;
- (id)defaultsDictionary;
- (id)permanentPassword;
- (void)setPermanentPassword:(id)arg1;
- (void)setSessionPassword:(id)arg1;
- (id)applePersonID;
- (id)appleAuthenticationToken;
- (BOOL)isSyncable;
- (void)setIsOffline:(BOOL)arg1;
- (id)_URLPersistenceHostname;
- (id)rawEmailAddresses;
- (id)emailAddresses;
- (void)_setEmailAliases:(id)arg1;
- (id)deliveryAccount;
- (void)setDeliveryAccount:(id)arg1;
- (id)_replacementDeliveryAccountForDeliveryAccount:(id)arg1;
- (id)dynamicDeliveryAccount;
- (void)presentOverQuotaAlert;
- (void)handleAlertResponse:(id)arg1;
- (struct AOSAccount *)_aoskitAccount;
- (void)_setAoskitAccount:(struct AOSAccount *)arg1;
- (struct AOSTransaction *)_mailPropertiesTransaction;
- (void)_setMailPropertiesTransaction:(struct AOSTransaction *)arg1;
- (struct AOSTransaction *)_primaryAddressesTransaction;
- (void)_setPrimaryAddressesTransaction:(struct AOSTransaction *)arg1;
- (struct AOSTransaction *)_aliasesTransaction;
- (void)_setAliasesTransaction:(struct AOSTransaction *)arg1;
- (struct AOSTransaction *)_editAliasesURLTransaction;
- (void)_setEditAliasesURLTransaction:(struct AOSTransaction *)arg1;
- (void)_updateAoskitAccount:(BOOL)arg1;
- (void)_updateAliases:(BOOL)arg1;
- (void)_updateMailPropertiesBypassingCache:(BOOL)arg1;
- (void)addPrimaryEmailAddresses;
- (void)updateEmailAliases;
- (void)openEditEmailAliasesURL;
- (void)migrateToNewAOSService;
- (id)aoskitPropertyForKey:(struct __CFString *)arg1;
- (unsigned int)lastSuccessfulAosSmtpPortNumber;
- (void)setLastSuccessfulAosSmtpPortNumber:(unsigned int)arg1;

@end

