/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class MimePart;

@interface MimePartEnumerator
{
    BOOL _onlyAttachments;
    BOOL _isFirstIteration;
    MimePart *_currentPart;
}

- (void)_setCurrentPart:(id)arg1;
- (id)initWithMimeBody:(id)arg1 onlyAttachments:(BOOL)arg2;
- (void)dealloc;
- (id)nextObject;

@end

