/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class Message, MessageBody, MessageStore, NSMutableDictionary, NSString;

@interface MimePart
{
    int _typeCode;
    int _subtypeCode;
    NSString *_type;
    NSString *_subtype;
    NSMutableDictionary *_bodyParameters;
    NSString *_contentTransferEncoding;
    id _encryptSignLock;
    BOOL _isMimeEncrypted;
    BOOL _isMimeSigned;
    MessageBody *_decryptedMessageBody;
    Message *_decryptedMessage;
    MessageStore *_decryptedMessageStore;
    NSMutableDictionary *_otherIvars;
    struct _NSRange _range;
    id _parentOrBody;
    MimePart *_nextPart;
}

@property(readonly) NSString *contentIDURLString;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",R,P

@property(readonly) BOOL isImage;
@property(readonly) BOOL isSigned;
@property(readonly) BOOL isEncrypted;
//@property(retain) MessageStore *decryptedMessageStore; // @synthesize decryptedMessageStore=_decryptedMessageStore;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"MessageStore",&,N,V_decryptedMessageStore,P

//@property(retain) Message *decryptedMessage; // @synthesize decryptedMessage=_decryptedMessage;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"Message",&,N,V_decryptedMessage,P

//@property(retain) MessageBody *decryptedMessageBody; // @synthesize decryptedMessageBody=_decryptedMessageBody;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"MessageBody",&,N,V_decryptedMessageBody,P

//@property BOOL isMimeSigned; // @synthesize isMimeSigned=_isMimeSigned;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,V_isMimeSigned

//@property BOOL isMimeEncrypted; // @synthesize isMimeEncrypted=_isMimeEncrypted;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,V_isMimeEncrypted

//@property(copy) NSString *contentTransferEncoding; // @synthesize contentTransferEncoding=_contentTransferEncoding;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,V_contentTransferEncoding,P


- (void)dealloc;
- (void)finalize;
- (id)init;
- (int)typeCode;
- (id)type;
- (void)setType:(id)arg1;
- (int)subtypeCode;
- (id)subtype;
- (void)setSubtype:(id)arg1;
- (BOOL)isType:(id)arg1 subtype:(id)arg2;
- (BOOL)isTypeCode:(int)arg1 subtypeCode:(int)arg2;
- (id)bodyParameterForKey:(id)arg1;
- (void)setBodyParameter:(id)arg1 forKey:(id)arg2;
- (id)bodyParameterKeys;
- (id)disposition;
- (void)setDisposition:(id)arg1;
- (id)dispositionParameterForKey:(id)arg1;
- (void)setDispositionParameter:(id)arg1 forKey:(id)arg2;
- (id)dispositionParameterKeys;
- (id)contentDescription;
- (void)setContentDescription:(id)arg1;
- (id)contentID;
- (void)setContentID:(id)arg1;
- (id)contentIDURLString;
- (id)contentLocation;
- (void)setContentLocation:(id)arg1;
- (id)languages;
- (void)setLanguages:(id)arg1;
- (id)parentPart;
- (id)firstChildPart;
- (id)nextSiblingPart;
- (id)subparts;
- (id)subpartAtIndex:(long long)arg1;
- (void)setSubparts:(id)arg1;
- (void)addSubpart:(id)arg1;
- (struct _NSRange)range;
- (void)setRange:(struct _NSRange)arg1;
- (id)bodyData;
- (id)bodyConvertedFromFlowedText;
- (id)mimeBody;
- (void)setMimeBody:(id)arg1;
- (id)description;
- (id)attachmentFilenameWithHiddenExtension:(char *)arg1;
- (id)attachmentFilename;
- (BOOL)isSigned;
- (BOOL)isEncrypted;
- (BOOL)hasCachedDataInStore;
- (unsigned int)numberOfAttachments;
- (void)getNumberOfAttachments:(unsigned int *)arg1 isSigned:(char *)arg2 isEncrypted:(char *)arg3;
- (id)attachments;
- (id)attachmentFilenames;
- (unsigned int)textEncoding;
- (unsigned long long)approximateRawSize;
- (unsigned long long)approximateDecodedSize;
- (BOOL)isReadableText;
- (BOOL)isImage;
- (BOOL)isCalendar;
- (BOOL)isToDo;
- (BOOL)isStationeryImage;
- (void)markAsStationeryImage;
- (id)_partThatIsAttachment;
- (BOOL)isMessageExternalBodyWithURL;
- (BOOL)shouldConsiderInlineOverridingExchangeServer;
- (BOOL)isAttachment;
- (BOOL)isRich;
- (BOOL)isHTML;
- (BOOL)usesKnownSignatureProtocol;
- (id)_createAttachment;
- (id)_createFileWrapper;
- (id)_getMessageAttachment:(unsigned long long)arg1;
- (id)attributedString;
- (id)fileWrapper;
- (id)_remoteFileWrapper;
- (void)download:(id)arg1 didReceiveResponse:(id)arg2;
- (void)download:(id)arg1 didReceiveDataOfLength:(unsigned long long)arg2;
- (void)download:(id)arg1 didFailWithError:(id)arg2;
- (void)downloadDidFinish:(id)arg1;
- (void)configureFileWrapper:(id)arg1;
- (id)startPart;
- (long long)numberOfAlternatives;
- (id)alternativeAtIndex:(long long)arg1;
- (id)signedData;
- (id)textPart;
- (id)textHtmlPart;
- (void)htmlString:(id *)arg1 createWebResource:(id *)arg2 forFileWrapper:(id)arg3 partNumber:(id)arg4;
- (id)htmlStringForMimePart:(id)arg1 attachment:(id)arg2;
- (id)decodedContent;
- (id)_archiveForData:(id)arg1 URL:(id)arg2 MIMEType:(id)arg3 textEncodingName:(id)arg4 frameName:(id)arg5 subresources:(id)arg6 subframeArchives:(id)arg7;
- (id)_archiveForData:(id)arg1 URL:(id)arg2 MIMEType:(id)arg3 textEncodingName:(id)arg4 frameName:(id)arg5;
- (id)_archiveForString:(id)arg1 URL:(id)arg2 needsPlainTextBodyClass:(BOOL)arg3;
- (id)_archiveForFileWrapper:(id)arg1 URL:(id)arg2;
- (id)_createArchiveWithConvertedPlainTextBodyClassFromArchive:(id)arg1;
- (id)parsedMessage;
- (id)webArchive;
- (id)decryptedMessageBodyIsEncrypted:(char *)arg1 isSigned:(char *)arg2;
- (id)todoPart;
- (void)clearCachedDecryptedMessageBody;
- (void)_setDecryptedMessageBody:(id)arg1 isEncrypted:(BOOL)arg2 isSigned:(BOOL)arg3;
- (id)decryptedMessageStore;
- (void)setDecryptedMessageStore:(id)arg1;
- (id)decryptedMessage;
- (void)setDecryptedMessage:(id)arg1;
- (id)decryptedMessageBody;
- (void)setDecryptedMessageBody:(id)arg1;
- (BOOL)isMimeSigned;
- (void)setIsMimeSigned:(BOOL)arg1;
- (BOOL)isMimeEncrypted;
- (void)setIsMimeEncrypted:(BOOL)arg1;
- (id)contentTransferEncoding;
- (void)setContentTransferEncoding:(id)arg1;

@end

