/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MimePart.h>

@interface MimePart (SMIMEExtensions)
- (void)verifySignature:(id *)arg1;
- (id)decodeMultipartSigned;
- (id)_decodeApplicationPkcs7_mime:(id *)arg1;
- (id)decodeApplicationPkcs7_mime;
- (id)copyMessageSigners;
- (id)copySigningCertificates;
- (id)copySignerLabels;
- (id)createSignedPartWithData:(id)arg1 sender:(id)arg2 signatureData:(id *)arg3;
- (id)createEncryptedPartWithData:(id)arg1 recipients:(id)arg2 encryptedData:(id *)arg3;
@end

