/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/NetworkController.h>

@interface NetworkController (Private)
- (void)_postNotification:(id)arg1;
- (void)_postNetworkChangeNotification:(id)arg1;
- (void)_triggerDialForHostname:(id)arg1;
- (void)_registerForNotificationKeys:(id)arg1 patterns:(id)arg2;
@end

