/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSMutableDictionary.h"

@interface NSMutableDictionary (Goodies)
- (void)setBool:(BOOL)fp8 forKey:(id)fp12;
- (void)setInteger:(int)fp8 forKey:(id)fp12;
- (void)addObject:(id)fp8 forKey:(id)fp12;
@end

