/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSMutableString.h"

@interface NSMutableString (convenience)
- (void)replaceString:(id)fp8 withString:(id)fp12;
@end

