/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSScanner.h"

@interface NSScanner (MimePart)
- (id)scanMimeTokenUsingSeparatorType:(unsigned int)fp8;
@end

