/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSTask.h"

@interface NSTask (NSTaskAdditions)
+ (BOOL)runPipe:(id)fp8 withInputFrom:(id)fp12 andOutputTo:(id)fp16;
+ (BOOL)runPipe:(id)fp8 withInputFrom:(id)fp12;
+ (BOOL)runPipe:(id)fp8 withOutputTo:(id)fp12;
@end

