/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/Message.h>

@class MessageBody, MutableMessageHeaders, NSData, NSString;

@interface OutgoingMessage : Message
{
    NSData *rawData;
    NSString *remoteID;
    NSString *existingRemoteID;
    unsigned long long bodyOffset;
    unsigned long long localAttachmentsSize;
    MessageBody *messageBody;
    MutableMessageHeaders *messageHeaders;
}

@property(retain) NSString *existingRemoteID; // @synthesize existingRemoteID;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"NSString",&,N,VexistingRemoteID,P

@property(retain) MessageBody *messageBody; // @synthesize messageBody;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@"MessageBody",&,N,VmessageBody,P


- (void)dealloc;
- (id)bodyData;
- (id)messageStore;
- (id)messageBodyIfAvailable;
- (id)messageDataIncludingFromSpace:(BOOL)arg1 newDocumentID:(id)arg2;
- (id)messageDataIncludingFromSpace:(BOOL)arg1;
- (id)mutableHeaders;
- (void)setMutableHeaders:(id)arg1;
- (id)headers;
- (id)headersIfAvailable;
- (unsigned long long)messageSize;
- (void)setRawData:(id)arg1 offsetOfBody:(unsigned long long)arg2;
- (void)setLocalAttachmentsSize:(unsigned long long)arg1;
- (void)setRemoteID:(id)arg1;
- (id)remoteID;
- (id)existingRemoteID;
- (void)setExistingRemoteID:(id)arg1;
- (id)messageBody;
- (void)setMessageBody:(id)arg1;

@end

