/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface ParentalControlSettings
{
}

+ (void)initialize;
+ (id)sharedInstance;
+ (BOOL)isEmail:(id)arg1 inEmailList:(id)arg2;
- (void)_updateCachedDataForEnabledState:(BOOL)arg1 approvedList:(BOOL)arg2 postNotification:(BOOL)arg3;
- (void)_reallyHandleDefaultsChange;
- (void)_defaultsDidChange;
- (void)_approveEmailListChanged:(id)arg1;
- (void)dealloc;
- (void)finalize;
- (BOOL)isInSpamProtectionMode;
- (id)parentEmails;
- (BOOL)isParentEmail:(id)arg1;
- (BOOL)_isSelfEmail:(id)arg1;
- (id)_approvedEmails;
- (BOOL)hasEmailBeenApproved:(id)arg1;
- (BOOL)haveEmailsBeenApproved:(id)arg1 unapprovedOnes:(id)arg2;
- (id)_dictionaryFromEmail:(id)arg1;
- (BOOL)_approveEmail:(id)arg1;
- (id)approveEmails:(id)arg1;
- (BOOL)_rejectEmail:(id)arg1;
- (id)rejectEmails:(id)arg1;
- (double)parentalControlEnabledTimeIntervalSince1970;

@end

