/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSXMLParserDelegate-Protocol.h"

@class NSArray, NSDictionary, NSString, NSURL;

@interface ParsedMessage <NSXMLParserDelegate>
{
    NSString *_html;
    NSString *_mimeType;
    NSURL *_baseURL;
    NSDictionary *_attachmentsByURL;
    NSArray *_stationeryBackgroundImageURLs;
    BOOL _isPlainText;
}

@property(retain) NSString *html;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",&,P

@property BOOL isPlainText; // @synthesize isPlainText=_isPlainText;
@property(retain) NSArray *stationeryBackgroundImageURLs; // @synthesize stationeryBackgroundImageURLs=_stationeryBackgroundImageURLs;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSArray",&,V_stationeryBackgroundImageURLs,P

@property(retain) NSDictionary *attachmentsByURL; // @synthesize attachmentsByURL=_attachmentsByURL;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSDictionary",&,V_attachmentsByURL,P

@property(retain) NSURL *baseURL; // @synthesize baseURL=_baseURL;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSURL",&,V_baseURL,P

@property(retain) NSString *mimeType; // @synthesize mimeType=_mimeType;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",&,V_mimeType,P


+ (id)parsedMessageWithWebArchive:(id)arg1 archiveIsMailInternal:(BOOL)arg2;
- (id)initWithWebArchive:(id)arg1;
- (id)initWithWebArchive:(id)arg1 archiveIsMailInternal:(BOOL)arg2;
- (void)dealloc;
- (void)addAttachment:(id)arg1 forURL:(id)arg2;
- (id)description;
- (void)setHtml:(id)arg1;
- (id)html;
- (void)_addWebArchiveDataToArray:(id)arg1;
- (id)attributedString;
- (void)setBaseURLFromHtml;
- (BOOL)isPlainText;
- (void)setIsPlainText:(BOOL)arg1;
- (id)stationeryBackgroundImageURLs;
- (void)setStationeryBackgroundImageURLs:(id)arg1;
- (id)attachmentsByURL;
- (void)setAttachmentsByURL:(id)arg1;
- (id)baseURL;
- (void)setBaseURL:(id)arg1;
- (id)mimeType;
- (void)setMimeType:(id)arg1;

@end

