/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/Connection.h>

@class NSData, NSMutableData;

@interface POP3Connection : Connection
{
    NSMutableData *_sendBuffer;
    struct __CFDictionary *_listResults;
    struct __CFDictionary *_serverMessageIdsByNumber;
    NSData *_apopTimeStamp;
    id <POP3ConnectionDelegate> _delegate;
    unsigned long long _numberOfMessagesAvailable;
    id _context;
    unsigned long long _numberOfMessagesToFetch;
    unsigned long long _numberOfMessagesFetched;
    unsigned long long _totalBytesToFetch;
    unsigned long long _totalBytesReceived;
    BOOL _connectionShouldPrefetchMessages;
    BOOL _hidingPassword;
    BOOL _currentlyFetchingMessage;
    long long _activityMonitorKey;
}

@property long long activityMonitorKey; // @synthesize activityMonitorKey=_activityMonitorKey;
// Preceeding property had unknown attributes: N
// Original attribute string: Tq,N,V_activityMonitorKey

@property BOOL currentlyFetchingMessage; // @synthesize currentlyFetchingMessage=_currentlyFetchingMessage;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,V_currentlyFetchingMessage

@property unsigned long long totalBytesReceived; // @synthesize totalBytesReceived=_totalBytesReceived;
// Preceeding property had unknown attributes: N
// Original attribute string: TQ,N,V_totalBytesReceived

@property unsigned long long totalBytesToFetch; // @synthesize totalBytesToFetch=_totalBytesToFetch;
// Preceeding property had unknown attributes: N
// Original attribute string: TQ,N,V_totalBytesToFetch

@property unsigned long long numberOfMessagesFetched; // @synthesize numberOfMessagesFetched=_numberOfMessagesFetched;
// Preceeding property had unknown attributes: N
// Original attribute string: TQ,N,V_numberOfMessagesFetched

@property unsigned long long numberOfMessagesToFetch; // @synthesize numberOfMessagesToFetch=_numberOfMessagesToFetch;
// Preceeding property had unknown attributes: N
// Original attribute string: TQ,N,V_numberOfMessagesToFetch

@property(retain) id context; // @synthesize context=_context;
// Preceeding property had unknown attributes: N,P
// Original attribute string: T@,&,N,V_context,P


- (id)init;
- (void)dealloc;
- (id)capabilities;
- (id)authenticationMechanisms;
- (BOOL)_teardownConnectionWithResult:(BOOL)arg1;
- (BOOL)authenticateUsingAccount:(id)arg1;
- (BOOL)_authenticateUsingAccount:(id)arg1 authenticator:(id)arg2;
- (int)_authenticateUsingHostname:(id)arg1 username:(id)arg2 password:(id)arg3 authenticator:(id)arg4;
- (int)_authenticateWithUsername:(id)arg1 password:(id)arg2;
- (int)quit;
- (BOOL)supportsAPOP;
- (int)doStat;
- (int)list:(unsigned long long)arg1;
- (int)_getListResults;
- (int)getMessageNumbers:(const struct __CFArray **)arg1 andMessageIdsByNumber:(const struct __CFDictionary **)arg2;
- (id)messageIDForMessageNumber:(unsigned long long)arg1;
- (void)setMessageID:(id)arg1 forMessageNumber:(unsigned long long)arg2;
- (id)_retrieveMessage:(unsigned long long)arg1 ofSize:(unsigned long long)arg2 informDelegate:(BOOL)arg3;
- (int)_retr:(unsigned long long)arg1;
- (int)dele:(unsigned long long)arg1;
- (id)retainedMessageHeaderForMessageNumber:(unsigned long long)arg1;
- (void)getTopOfMessageNumber:(unsigned long long)arg1 intoMutableData:(id)arg2;
- (unsigned long long)sizeOfMessageNumber:(unsigned long long)arg1;
- (BOOL)messagesAvailable;
- (unsigned long long)numberOfMessagesAvailable;
- (int)fetchMessages:(struct __CFArray *)arg1 totalBytes:(unsigned long long)arg2;
- (int)deleteMessagesOnServer:(struct __CFArray *)arg1;
- (void)setDelegate:(id)arg1 context:(id)arg2;
- (int)_startTLSForSecurityLayerType:(int)arg1;
- (int)_readMultilineResponseWithMaxSize:(unsigned long long)arg1 intoMutableData:(id)arg2 informDelegate:(BOOL)arg3;
- (int)_sendCommand:(const char *)arg1 withArguments:(id)arg2;
- (id)_copyReplyLineDataWithError:(id *)arg1;
- (id)_copyReplyLineData;
- (void)_parsePOPErrorFromData:(id)arg1 error:(id)arg2;
- (int)_getStatusFromReply;
- (int)_apopWithUsername:(id)arg1 password:(id)arg2;
- (int)_user:(id)arg1;
- (int)_pass:(id)arg1;
- (long long)activityMonitorKey;
- (void)setActivityMonitorKey:(long long)arg1;
- (BOOL)currentlyFetchingMessage;
- (void)setCurrentlyFetchingMessage:(BOOL)arg1;
- (unsigned long long)totalBytesReceived;
- (void)setTotalBytesReceived:(unsigned long long)arg1;
- (unsigned long long)totalBytesToFetch;
- (void)setTotalBytesToFetch:(unsigned long long)arg1;
- (unsigned long long)numberOfMessagesFetched;
- (void)setNumberOfMessagesFetched:(unsigned long long)arg1;
- (unsigned long long)numberOfMessagesToFetch;
- (void)setNumberOfMessagesToFetch:(unsigned long long)arg1;
- (id)context;
- (void)setContext:(id)arg1;

@end

