/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/POPAccount.h>

@interface POPAccount (Applescript)
- (BOOL)deleteMessagesWhenMovedFromInbox;
- (void)setDeleteMessagesWhenMovedFromInbox:(BOOL)arg1;
- (BOOL)deleteMessagesOnServer;
- (void)setDeleteMessagesOnServer:(BOOL)arg1;
- (id)mailboxes;
- (id)objectSpecifierForMailboxUid:(id)arg1;
- (id)valueInMailboxesWithName:(id)arg1;
@end

