/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSCacheDelegate-Protocol.h"

@class NSMutableDictionary;

@interface PreparedStatementManager <NSCacheDelegate>
{
    NSMutableDictionary *_statementCachesByDB;
    BOOL _forceFinalize;
}

+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
- (id)retain;
- (unsigned long long)retainCount;
- (void)release;
- (id)autorelease;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (void)dealloc;
- (id)_statementsForDB:(id)arg1;
- (id)_extraStatementsForThread;
- (void)_addToCache:(id)arg1 inDBKey:(id)arg2 forPatternString:(id)arg3;
- (id)checkOutPreparedStatement:(struct sqlite3 *)arg1 withPattern:(const char *)arg2;
- (void)checkInPreparedStatement:(id)arg1;
- (void)removeStatementCacheEntriesForDB:(struct sqlite3 *)arg1;
- (void)cache:(id)arg1 willEvictObject:(id)arg2;

@end

