/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/Message.h>

@class MessageHeaders, NSData, NSString;

@interface RecoveredMessage : Message
{
    NSString *_path;
    NSString *_remoteID;
    NSString *_remoteMailboxURL;
    NSString *_originalMailboxURL;
    MessageHeaders *_headers;
    unsigned long long _size;
    CDAnonymousStruct15 _remoteFlags;
    NSData *_data;
    NSData *_allData;
    BOOL _loadedFileData;
}

- (void)_loadFileDataIfNeeded;
- (id)initWithPath:(id)arg1;
- (id)messageID;
- (id)remoteMailboxURL;
- (id)originalMailboxURL;
- (id)headerData;
- (id)headers;
- (id)messageDataIncludingFromSpace:(BOOL)arg1 newDocumentID:(id)arg2;
- (id)bodyData;
- (id)dataForMimePart:(id)arg1;
- (BOOL)hasCachedDataForMimePart:(id)arg1;
- (id)messageBody;
- (id)messageBodyUpdatingFlags:(BOOL)arg1;
- (id)messageBodyIfAvailableUpdatingFlags:(BOOL)arg1;
- (CDAnonymousStruct15)remoteFlags;
- (unsigned int)messageFlags;
- (CDAnonymousStruct10)moreMessageFlags;
- (void)dealloc;
- (void)flushCachedData;
- (BOOL)setMessageID:(long long)arg1 directory:(id)arg2;

@end

