/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface ReconcilerAgentData
{
    id <ReconciliationAgent> _agent;
    int _state;
}

- (id)init;
- (id)initWithAgent:(id)arg1 state:(int)arg2;
- (void)dealloc;
- (id)agent;
- (int)state;
- (void)setState:(int)arg1;
- (id)description;

@end

