/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "ReconciliationMechanism-Protocol.h"

@interface ReconcilerMechanism <ReconciliationMechanism>
{
    int _conflictMode;
}

- (id)init;
- (id)initWithConflictMode:(int)arg1;
- (void)performReconciliationForMailboxID:(long long)arg1 usingAgents:(id)arg2;
- (BOOL)areAgentsValid:(id)arg1;

@end

