/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSObject.h"

@interface ReconcilerAgentData : NSObject
{
    id <ReconciliationAgent> _agent;
    int _state;
}

- (id)init;
- (id)initWithAgent:(id)fp8 state:(int)fp12;
- (void)dealloc;
- (id)agent;
- (int)state;
- (void)setState:(int)fp8;
- (id)description;

@end

