/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/RemoteStoreSizeEngine.h>

@interface RemoteStoreSizeEngine (Internal)
- (void)_getSizeForMailboxUid:(id)arg1;
- (BOOL)_changeUsageInfo:(CDAnonymousStruct6 *)arg1 forMailboxUid:(id)arg2 refetchQuotas:(BOOL)arg3;
- (void)_sizeChangedForMailboxUid:(id)arg1;
- (void)_mailboxSizeChanged:(id)arg1;
- (void)_mailboxBecameInvalid:(id)arg1;
@end

