/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface SafeValueCache
{
    id _value;
    long long _state;
    id _target;
    SEL _selector;
}

@property(retain) id value;
// Preceeding property had unknown attributes: P
// Original attribute string: T@,&,P


- (id)initWithUpdateTarget:(id)arg1 selector:(SEL)arg2;
- (void)dealloc;
- (void)clearTarget;
- (id)value;
- (void)setValue:(id)arg1;
- (id)retainedValue;
- (void)invalidate;

@end

