/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SASLSecurityLayer <NSObject>
- (unsigned int)encryptionBufferSize;
- (id)createDecryptedDataForBytes:(const char *)arg1 length:(unsigned long long)arg2;
- (id)createEncryptedDataForBytes:(const char *)arg1 length:(unsigned long long)arg2;
@end

