/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSManagedObjectContext;

@interface SeenMessagesManager
{
    NSManagedObjectContext *_managedObjectContext;
    id _account;
}

@property(retain) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSManagedObjectContext",&,V_managedObjectContext,P

@property(retain) id account; // @synthesize account=_account;
// Preceeding property had unknown attributes: P
// Original attribute string: T@,&,V_account,P


- (id)initWithAccountID:(id)arg1 createAccount:(BOOL)arg2;
- (void)dealloc;
- (id)_accountForAccountID:(id)arg1;
- (id)_addAccountWithID:(id)arg1;
- (id)seenMessageForMessageID:(id)arg1;
- (unsigned long long)countOfSeenMessages;
- (id)addMessageID:(id)arg1 dateSeen:(id)arg2;
- (void)removeMessageIDs:(id)arg1;
- (id)seenMessages;
- (id)messagesToBeDeletedFromServer;
- (void)removeServerDeletedMessages;
- (void)removeMessagesNotOnServer:(id)arg1;
- (void)saveChanges;
- (void)_configureManagedObjectContext;
- (id)managedObjectContext;
- (void)setManagedObjectContext:(id)arg1;
- (id)account;
- (void)setAccount:(id)arg1;

@end

