/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/SMTPConnection.h>

@interface SMTPConnection (PrivateCommands)
- (int)_sendCommand:(const char *)arg1 length:(unsigned long long)arg2 argument:(id)arg3 trailer:(unsigned char)arg4;
- (int)_getReply;
- (void)_readResponseRange:(struct _NSRange *)arg1 isContinuation:(char *)arg2;
- (id)_getValidDomain;
- (int)_doHandshakeWithSecurityLayerType:(int)arg1 tryHELOIfEHLOFails:(BOOL)arg2;
- (int)_sendEHLOWithClientDomainName:(id)arg1;
- (int)_sendHELOWithClientDomainName:(id)arg1;
- (BOOL)_hasParameter:(id)arg1 forKeyword:(id)arg2;
@end

