/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/DeliveryAccount.h>

@class NSTimer, SMTPConnection;

@interface SMTPAccount : DeliveryAccount
{
    SMTPConnection *_connection;
    id _smtpAccountLock;
    NSTimer *_timer;
    long long _lastTimerSetTime;
    unsigned int _lastUsedPort;
}

@property BOOL shouldTryDefaultPorts;

+ (id)accountTypeString;
+ (id)newDefaultInstance;
- (id)init;
- (void)dealloc;
- (Class)deliveryClass;
- (unsigned int)defaultPortNumber;
- (id)serviceName;
- (id)saslProfileName;
- (unsigned int)secondaryDefaultPortNumber;
- (unsigned int)tertiaryDefaultPortNumber;
- (BOOL)_portNumberIsADefaultPortNumber;
- (unsigned int)portNumber;
- (void)setPortNumber:(unsigned int)arg1;
- (BOOL)shouldTryDefaultPorts;
- (void)setShouldTryDefaultPorts:(BOOL)arg1;
- (Class)connectionClass;
- (id)preferredAuthScheme;
- (void)setPreferredAuthScheme:(id)arg1;
- (BOOL)isSyncable;
- (void)_setStandardPortsConnectionErrorMessage;
- (id)createConnectedConnection;
- (id)authenticatedConnection;
- (void)checkInConnection:(id)arg1;
- (void)setTimer;
- (void)connectionExpired:(id)arg1;
- (void)disconnect:(id)arg1;
- (BOOL)_shouldTryDirectSSLConnectionOnPort:(unsigned int)arg1;
- (void)releaseAllConnections;
- (void)setPermanentPassword:(id)arg1;
- (id)permanentPassword;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;

@end

