/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSMenuItem;

@interface SoundMenu
{
    long long _insertionIndex;
    NSMenuItem *_otherItem;
}

- (id)_addItemWithTitle:(id)arg1;
- (id)initAndLoadSounds;
- (void)dealloc;
- (void)playSoundForItemAtIndex:(long long)arg1;
- (long long)addSoundPath:(id)arg1;
- (void)performActionForItemAtIndex:(long long)arg1;
- (id)otherMenuItem;
- (void)_soundMenuDidAddItem:(id)arg1;

@end

