/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import <Message/MailboxUid.h>

@interface SpecialMailboxUid : MailboxUid
{
}

+ (id)specialMailboxWithIdentifier:(id)fp8;
+ (id)specialMailboxUidForMailboxUid:(id)fp8;
+ (id)inboxMailboxUid;
+ (id)sentMessagesMailboxUid;
+ (id)draftsMailboxUid;
+ (id)junkMailboxUid;
+ (id)outboxMailboxUid;
+ (id)trashMailboxUid;
- (id)displayName;
- (id)name;
- (id)account;
- (id)children;
- (id)mutableCopyOfChildren;
- (id)childAtIndex:(unsigned int)fp8;
- (unsigned int)numberOfChildren;
- (unsigned int)numberOfGenericChildren;
- (unsigned int)unreadCount;
- (id)tildeAbbreviatedPath;
- (id)_viewerAttributesKey;
- (id)_loadUserInfo;
- (void)saveUserInfo;

@end

