/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/SpecialMailboxUid.h>

@interface SpecialMailboxUid (AppleScript)
+ (id)appleScriptNameForMailboxType:(int)arg1;
- (id)appleScriptKey;
- (id)objectSpecifier;
- (id)messages;
@end

