/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSData;

@interface Subdata
{
    struct _NSRange subrange;
    NSData *parentData;
}

- (unsigned long long)length;
- (const void *)bytes;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithParent:(id)arg1 range:(struct _NSRange)arg2;
- (void)dealloc;

@end

