/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "ToDoConsumer-Protocol.h"

@class MailboxUid, NSConditionLock, NSMutableSet, ToDoCriterion;

@interface ToDoStore <ToDoConsumer>
{
    NSMutableSet *_todos;
    MailboxUid *_mailboxUid;
    unsigned long long _incompleteCount;
    long long _mallsWatchingStore;
    id <ReconciliationAgent> _reconciliationAgent;
    long long _mailboxID;
    NSConditionLock *_mailboxIDLock;
}

@property(readonly) ToDoCriterion *criterion;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"ToDoCriterion",R,P

@property(readonly) MailboxUid *mailboxUid;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"MailboxUid",R,P

@property long long mallsWatchingStore;
@property unsigned long long incompleteCount; // @synthesize incompleteCount=_incompleteCount;

+ (void)initialize;
+ (id)toDoStoreForMailbox:(id)arg1;
+ (id)searchStoreForCriterion:(id)arg1;
+ (void)removeToDoStoreForMailbox:(id)arg1;
+ (void)addToDosToStores:(id)arg1;
+ (void)deleteToDosFromStores:(id)arg1;
+ (id)allStores;
+ (id)allToDosInStores;
+ (id)cachesDescription;
- (id)initWithMailboxUid:(id)arg1;
- (id)init;
- (void)setReconciliationAgent:(id)arg1;
- (id)reconciliationAgent;
- (void)addWatchingMall;
- (void)removeWatchingMall;
- (long long)mallsWatchingStore;
- (id)criterion;
- (void)setMallsWatchingStore:(long long)arg1;
- (void)setIncompleteCount:(unsigned long long)arg1;
- (void)dealloc;
- (void)setMailboxID:(id)arg1;
- (id)todos;
- (void)newToDosAvailable:(id)arg1;
- (BOOL)shouldCancel;
- (void)addToDos:(id)arg1;
- (void)deleteToDos:(id)arg1;
- (void)handleUpdatedToDo:(id)arg1;
- (id)mailboxUid;
- (unsigned long long)incompleteCount;

@end

