/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class CalGroup, MailAccount, NSString;

@interface ToDoCalendarGroup
{
    MailAccount *_account;
    NSString *_groupID;
    NSString *_title;
    int _type;
    CalGroup *_calGroup;
}

- (id)initIMAPGroupWithTitle:(id)arg1 groupID:(id)arg2 account:(id)arg3;
- (id)initWithCalGroup:(id)arg1;
- (void)dealloc;
- (id)calGroupFromToDoCalendarGroup;
- (void)updateWithCalGroup:(id)arg1;
- (BOOL)isIdenticalToCalGroup:(id)arg1;
- (id)title;
- (void)setTitle:(id)arg1;
- (id)groupID;
- (void)setGroupID:(id)arg1;
- (id)account;
- (int)type;
- (void)setType:(int)arg1;
- (int)typeFromCalGroupType:(id)arg1;
- (void)setTypeFromCalGroupType:(id)arg1;
- (id)calGroupType;
- (id)calGroup;
- (void)setCalGroup:(id)arg1;
- (id)description;
- (id)shortDescription;

@end

