/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface ToDoUtilities
{
}

+ (BOOL)stringIsDifferent:(id)arg1 fromString:(id)arg2;
+ (BOOL)dateIsDifferent:(id)arg1 fromDate:(id)arg2;
+ (BOOL)urlIsDifferent:(id)arg1 fromUrl:(id)arg2;
+ (BOOL)dataAreDifferent:(id)arg1 fromData:(id)arg2;
+ (BOOL)splitToDosForMessages:(id)arg1 intoMessageToDos:(id *)arg2 noteToDos:(id *)arg3;

@end

