/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSString;

@interface ToDoDifferenceExpressionResult
{
    int _operation;
    int _provider;
    NSString *_todoUID;
    NSString *_remoteID;
}

- (id)init;
- (id)initWithOperation:(int)arg1 provider:(int)arg2 todoUID:(id)arg3 remoteID:(id)arg4;
- (void)dealloc;
- (int)operation;
- (void)setOperation:(int)arg1;
- (int)provider;
- (void)setProvider:(int)arg1;
- (id)todoUID;
- (void)setToDoUID:(id)arg1;
- (id)remoteID;
- (void)setRemoteID:(id)arg1;
- (void)setOperation:(int)arg1 provider:(int)arg2 todoUID:(id)arg3 remoteID:(id)arg4;
- (BOOL)isAddDeleteOrUpdate;
- (BOOL)isAddDeleteUpdateOrOddity;
- (BOOL)isAdd;
- (BOOL)isDelete;
- (BOOL)isUpdate;
- (BOOL)isConflict;
- (BOOL)isInvalid;
- (BOOL)hasStoreSource;
- (BOOL)hasCacheSource;

@end

