/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/MessageWriter.h>

@interface ToDoWriter : MessageWriter
{
}

- (id)init;
- (Class)messageClass;
- (id)createToDoMessageWithToDo:(id)arg1 headers:(id)arg2 forMessage:(id)arg3;

@end

