/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/ToDoAlarm.h>

@interface ToDoAlarm (Internal)
- (int)offsetTypeFromCalAlarm:(id)arg1;
- (int)offsetTypeFromAbsoluteTrigger:(id)arg1 andRelativeTrigger:(double)arg2;
- (long long)timeAndSetReminderDateFromCalAlarm:(id)arg1;
- (long long)timeAndSetReminderDateFromAbsoluteTrigger:(id)arg1 andRelativeTrigger:(double)arg2;
- (unsigned long long)offsetDaysFromRelativeTrigger:(double)arg1;
- (int)previousOffsetType;
- (void)setPreviousOffsetType:(int)arg1;
- (int)previousType;
- (void)setPreviousType:(int)arg1;
- (id)delegate;
- (void)setHasChanged:(BOOL)arg1;
- (void)setChangedProperties:(int)arg1;
- (id)calAlarm;
- (void)setCalAlarm:(id)arg1;
- (id)lock;
@end

