/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface ToDoUndoCenter
{
}

+ (void)initialize;
+ (id)sharedInstance;
+ (void)setDefaultCalendarFromToDo:(id)arg1 key:(id)arg2;
- (void)setValue:(id)arg1 forKey:(id)arg2 inToDo:(id)arg3 withUndoManager:(id)arg4;
- (void)setValue:(id)arg1 forKey:(id)arg2 inAlarm:(id)arg3 withUndoManager:(id)arg4;
- (void)addToDo:(id)arg1 withUndoManager:(id)arg2;
- (void)addToDos:(id)arg1 withUndoManager:(id)arg2;
- (void)deleteToDos:(id)arg1 withUndoManager:(id)arg2;
- (void)addAlarm:(id)arg1 toAlarms:(id)arg2 withUndoManager:(id)arg3;
- (void)insertAlarm:(id)arg1 atIndex:(unsigned long long)arg2 intoAlarms:(id)arg3 withUndoManager:(id)arg4;
- (void)removeAlarmAtIndex:(unsigned long long)arg1 fromAlarms:(id)arg2 withUndoManager:(id)arg3;
- (void)removeAlarm:(id)arg1 fromAlarms:(id)arg2 withUndoManager:(id)arg3;

@end

