/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSMutableArray, NSMutableDictionary;

@interface ToDosCache
{
    NSMutableDictionary *_todosByGUID;
    NSMutableDictionary *_deletedToDoIDsByDocumentID;
    BOOL _checkConsistency;
    Class _libraryClass;
    NSMutableArray *_listeners;
    id <CalendarStoreConduit> _calendarStoreConduit;
}

- (id)initWithLibraryClass:(Class)arg1 checkingConsistency:(BOOL)arg2;
- (void)dealloc;
- (void)addListener:(id)arg1;
- (void)removeListener:(id)arg1;
- (void)addToDo:(id)arg1;
- (void)updateToDo:(id)arg1;
- (void)removeToDo:(id)arg1;
- (id)cachedToDoWithID:(id)arg1;
- (id)todoWithID:(id)arg1;
- (id)todoWithPreviousID:(id)arg1;
- (BOOL)hasToDoWithIDBeenDeleted:(id)arg1;
- (id)allDeletedToDoIDsForDocumentID:(id)arg1;
- (id)libraryToDoFromCalTask:(id)arg1;
- (id)libraryToDoFromNewCalTask:(id)arg1;
- (id)allToDosForMailboxID:(long long)arg1;
- (id)loadAndCacheToDosInDisabledAccount:(id)arg1;
- (id)todosByIDForDocumentID:(id)arg1 byPreviousID:(id *)arg2;
- (id)allToDosForDocumentID:(id)arg1;
- (id)allToDosForMessage:(id)arg1;
- (id)lastToDoWithID:(id)arg1 inMailbox:(id)arg2;
- (id)allToDosInActiveAccounts;
- (id)listOfToDoIDsInCalendarWithID:(id)arg1;
- (id)todosMatchingCriterion:(id)arg1;
- (id)todosInActiveAccountsMatchingCriterion:(id)arg1;

@end

