/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSMutableDictionary;

@interface ToDoChangesQueue
{
    NSMutableDictionary *_todosToAdd;
    NSMutableDictionary *_todosToUpdate;
    NSMutableDictionary *_todosToDelete;
}

- (id)init;
- (void)dealloc;
- (void)queueToDosToAdd:(id)arg1;
- (void)queueToDosToUpdate:(id)arg1;
- (void)queueToDosToDelete:(id)arg1;
- (id)todosToAdd;
- (id)todosToUpdate;
- (id)todosToDelete;
- (void)clearQueue;

@end

