/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSCopying-Protocol.h"

@class CalCalendar, MailAccount, NSColor, NSString, NSURL;

@interface ToDoCalendar <NSCopying>
{
    NSString *_calendarID;
    NSString *_title;
    NSColor *_color;
    BOOL _editable;
    NSURL *_url;
    MailAccount *_account;
    int _type;
    NSString *_groupID;
    CalCalendar *_calCalendar;
    BOOL _hasChanged;
    int _changedProperties;
}

- (id)initWithCalCalendar:(id)arg1 account:(id)arg2;
- (id)calCalendarFromToDoCalendar;
- (void)updateWithCalCalendar:(id)arg1;
- (void)dealloc;
- (BOOL)isIdenticalToCalCalendar:(id)arg1;
- (int)changedProperties;
- (id)title;
- (void)setTitle:(id)arg1;
- (id)color;
- (void)setColor:(id)arg1;
- (BOOL)isEditable;
- (void)setEditable:(BOOL)arg1;
- (BOOL)isToDoContainer;
- (int)type;
- (void)setType:(int)arg1;
- (int)typeFromCalCalendarType:(id)arg1;
- (void)setTypeFromCalCalendarType:(id)arg1;
- (id)calCalendarType;
- (id)calendarID;
- (void)setCalendarID:(id)arg1;
- (id)url;
- (void)setUrl:(id)arg1;
- (BOOL)hasChanged;
- (void)setHasNotChanged;
- (id)description;
- (id)shortDescription;
- (long long)compare:(id)arg1;
- (id)initWithData:(id)arg1;
- (id)data;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)calCalendar;
- (void)setCalCalendar:(id)arg1;
- (id)account;
- (void)mergeIn:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)groupID;
- (void)setGroupID:(id)arg1;

@end

