/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/ToDoAlarm.h>

@interface ToDoAlarm (Private)
- (int)changedProperties;
- (void)_alarmChangedProperties:(unsigned int)arg1;
- (id)syncToDoID;
- (void)setSyncToDoID:(id)arg1;
@end

