/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Message/ToDoCriterion.h>

@interface ToDoCriterion (PrivateLibraryAdditions)
- (BOOL)isExpressibleInTigerSchema;
- (id)SQLExpressionWithContext:(CDAnonymousStruct12 *)arg1 depth:(unsigned long long)arg2 enclosingSmartMailboxes:(id)arg3;
@end

