/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSString;

@interface ToDoLibraryAndStoreConsistencyChecker
{
    unsigned long long _todoCount;
    unsigned long long _totalCountBefore;
    NSString *_callingMethodDescription;
    int _actionType;
    NSString *_actionDescription;
}

+ (unsigned long long)_verifyStateOfAllTodos:(id)arg1;
- (id)initWithToDos:(id)arg1 actionType:(int)arg2 callingMethodDescription:(id)arg3;
- (void)dealloc;
- (void)finish;
- (void)logInconsistenciesInToDos:(id)arg1;
- (id)_actionDescriptionForType:(int)arg1;
- (BOOL)_countsMatch:(long long)arg1;

@end

