/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSString;

@interface URLMatch
{
    struct _NSRange _range;
    NSString *_url;
}

@property(copy) NSString *url; // @synthesize url=_url;
// Preceeding property had unknown attributes: P
// Original attribute string: T@"NSString",C,V_url,P

@property struct _NSRange range; // @synthesize range=_range;

- (id)initWithRange:(struct _NSRange)arg1 url:(id)arg2;
- (id)init;
- (void)dealloc;
- (id)description;
- (id)url;
- (void)setUrl:(id)arg1;
- (struct _NSRange)range;
- (void)setRange:(struct _NSRange)arg1;

@end

