/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class MimeBody, MimePart, NSData, NSDictionary, NSURL;

@interface WebMessageDocument : NSObject
{
    NSDictionary *_partsByURL;
    NSURL *_baseURL;
    MimeBody *_mimeBody;
    MimePart *_htmlPart;
    NSData *_htmlData;
    unsigned int _preferredCharset;
    unsigned int _uniqueId:30;
    unsigned int _downloadRemoteURLs:1;
    unsigned int _containsRemoteContent:1;
    BOOL _messageIsFromEntourage;
}

+ (id)openDocuments;
+ (id)invalidBaseURL;
+ (id)documentWithUniqueIdentifier:(unsigned int)fp8;
- (void)dealloc;
- (void)finalize;
- (id)init;
- (id)initWithMimeBody:(id)fp8;
- (id)initWithMimePart:(id)fp8;
- (id)mimePartForURL:(id)fp8;
- (id)mimeBody;
- (id)baseURL;
- (void)setPreferredEncoding:(unsigned long)fp8;
- (id)preferredCharacterSet;
- (unsigned int)uniqueIdentifier;
- (id)htmlData;
- (id)fileWrapper;
- (void)setDownloadRemoteURLs:(BOOL)fp8;
- (BOOL)downloadRemoteURLs;
- (void)setContainsRemoteContent:(BOOL)fp8;
- (BOOL)containsRemoteContent;
- (void)setMessageIsFromEntourage:(BOOL)fp8;
- (BOOL)messageIsFromEntourage;

@end

