/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface (null) (Shuffle)
- (void)shuffle;
- (void)shuffleWithSeed:(unsigned int)arg1;
@end

