/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface (null) (ToDoUIPasteboardSupport)
- (void)addUniqueToDo:(id)arg1 inCalendar:(id)arg2 mailboxUid:(id)arg3 oldToNewId:(id)arg4;
@end

