/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface (null) (SizingExtras)
- (void)_setSize:(struct CGSize)arg1 ofElement:(id)arg2;
- (void)adjustToDocumentView;
- (void)adjustAttachmentView:(id)arg1;
- (void)selectAttachmentView:(id)arg1;
@end

