/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSEnumerator.h"

#import "DOMNodeFilterProtocol.h"

@class DOMNodeIterator, DOMRange, EditableWebMessageDocument;

@interface _ComposeAttachmentEnumerator : NSEnumerator <DOMNodeFilter>
{
    EditableWebMessageDocument *document;
    DOMRange *range;
    DOMNodeIterator *iterator;
    unsigned int acceptDeleted:1;
    unsigned int acceptNonDeleted:1;
    unsigned int createdIterator:1;
}

- (void)dealloc;
- (id)nextObject;
- (short)acceptNode:(id)fp8;

@end

