/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class DOMNode, EditableWebMessageDocument;

@interface _ComposeAttachmentEnumerator
{
    DOMNode *_currentNode;
    DOMNode *_containerNode;
    DOMNode *_endNode;
    EditableWebMessageDocument *_document;
    unsigned int acceptDeleted:1;
    unsigned int acceptNonDeleted:1;
}

@property(retain) EditableWebMessageDocument *document; // @synthesize document=_document;
@property(retain) DOMNode *endNode; // @synthesize endNode=_endNode;
@property(retain) DOMNode *containerNode; // @synthesize containerNode=_containerNode;
@property(retain) DOMNode *currentNode; // @synthesize currentNode=_currentNode;

- (id)initWithDocument:(id)arg1 options:(int)arg2 range:(id)arg3;
- (void)dealloc;
- (short)acceptNode:(id)arg1;
- (id)nextObject;
- (id)document;
- (void)setDocument:(id)arg1;
- (id)endNode;
- (void)setEndNode:(id)arg1;
- (id)containerNode;
- (void)setContainerNode:(id)arg1;
- (id)currentNode;
- (void)setCurrentNode:(id)arg1;

@end

