/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@protocol AccountSetupValidatorDelegate

@optional
- (void)validator:(id)arg1 didChangeState:(long long)arg2;
- (void)validatorDidFail:(id)arg1;
- (void)validatorDidFinish:(id)arg1;
@end

