/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class ActivityMonitor, NSArray, NSDictionary, NSError, NSString;

@interface AccountAutoconfigurator
{
    id <AccountAutoconfiguratorDelegate> _delegate;
    ActivityMonitor *_autoconfigurationActivity;
    long long _state;
    NSString *_emailAddress;
    NSString *_password;
    NSString *_userName;
    NSString *_domain;
    NSDictionary *_receivingAccountInfo;
    NSArray *_deliveryAccountInfos;
    BOOL _authenticationFailed;
    NSError *_authenticationError;
}

@property(copy) NSError *authenticationError; // @synthesize authenticationError=_authenticationError;
@property(copy) NSArray *deliveryAccountInfos; // @synthesize deliveryAccountInfos=_deliveryAccountInfos;
@property(copy) NSDictionary *receivingAccountInfo; // @synthesize receivingAccountInfo=_receivingAccountInfo;
@property BOOL authenticationFailed; // @synthesize authenticationFailed=_authenticationFailed;
@property(copy) NSString *domain; // @synthesize domain=_domain;
// Preceeding property had unknown attributes: N
// Original attribute string: T@"NSString",C,N,V_domain

@property(copy) NSString *userName; // @synthesize userName=_userName;
// Preceeding property had unknown attributes: N
// Original attribute string: T@"NSString",C,N,V_userName

@property(copy) NSString *password; // @synthesize password=_password;
// Preceeding property had unknown attributes: N
// Original attribute string: T@"NSString",C,N,V_password

@property(copy) NSString *emailAddress; // @synthesize emailAddress=_emailAddress;
// Preceeding property had unknown attributes: N
// Original attribute string: T@"NSString",C,N,V_emailAddress

@property(retain) ActivityMonitor *autoconfigurationActivity; // @synthesize autoconfigurationActivity=_autoconfigurationActivity;
@property id <AccountAutoconfiguratorDelegate> delegate; // @synthesize delegate=_delegate;

- (id)init;
- (id)initWithEmailAddress:(id)arg1 userName:(id)arg2 password:(id)arg3 delegate:(id)arg4;
- (void)dealloc;
- (void)execute;
- (void)cancel;
- (void)_sendAutoconfiguratorDidChangeState:(id)arg1;
- (void)_sendAutoconfiguratorDidFail;
- (void)_sendAutoconfiguratorDidFinish;
- (void)_setState:(long long)arg1;
- (BOOL)_shouldCancel;
- (void)_autoconfigure;
- (id)authenticationError;
- (void)setAuthenticationError:(id)arg1;
- (id)deliveryAccountInfos;
- (void)setDeliveryAccountInfos:(id)arg1;
- (id)receivingAccountInfo;
- (void)setReceivingAccountInfo:(id)arg1;
- (BOOL)authenticationFailed;
- (void)setAuthenticationFailed:(BOOL)arg1;
- (id)domain;
- (void)setDomain:(id)arg1;
- (id)userName;
- (void)setUserName:(id)arg1;
- (id)password;
- (void)setPassword:(id)arg1;
- (id)emailAddress;
- (void)setEmailAddress:(id)arg1;
- (id)autoconfigurationActivity;
- (void)setAutoconfigurationActivity:(id)arg1;
- (id)delegate;
- (void)setDelegate:(id)arg1;

@end

