/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class HelpButton, NSButton, NSView;

@interface Assistant : NSObject
{
    NSView *_parentView;
    NSButton *_backButton;
    NSButton *_forwardButton;
    NSButton *_cancelButton;
    HelpButton *_helpButton;
    id _delegate;
}

- (id)initWithAssistentManager:(id)fp8;
- (void)dealloc;
- (void)setDelegate:(id)fp8;
- (void)start;
- (void)stop;
- (void)goForward;
- (void)goBackward;
- (void)weAreDone;
- (id)windowTitle;
- (void)setupKeyViewLoop;

@end

