/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSImage;

@interface BorderlessButton
{
    NSImage *activeImage;
    NSImage *inactiveImage;
}

@property(retain) NSImage *inactiveImage; // @synthesize inactiveImage;
@property(retain) NSImage *activeImage; // @synthesize activeImage;

- (BOOL)isOpaque;
- (void)dealloc;
- (void)setEnabled:(BOOL)arg1;
- (id)inactiveImage;
- (void)setInactiveImage:(id)arg1;
- (id)activeImage;
- (void)setActiveImage:(id)arg1;

@end

