/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSButton, NSPanel, NSScrollView, NSTextField, SFCertificateView;

@interface CertificatePanelController : NSObject
{
    NSPanel *panel;
    SFCertificateView *certificateView;
    NSTextField *titleField;
    NSTextField *messageField;
    NSButton *rememberChanges;
    NSScrollView *scrollView;
    struct _NSRect lastScrollViewFrame;
    struct _NSRect lastPanelFrame;
    struct _NSSize minSizeWithDetail;
    struct _NSSize minSizeWithoutDetail;
}

- (void)orderOutPanel:(id)fp8;
- (void)toggleCertificateView:(id)fp8;
- (id)_findButtonInViews:(id)fp8 withAction:(SEL)fp12;
- (BOOL)runModalForError:(id)fp8 certificate:(struct OpaqueSecCertificateRef *)fp12 rememberDecision:(char *)fp16;

@end

