/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSArray, NSColor, NSImage;

@interface ColorBackgroundView
{
    long long _tag;
    NSColor *_color;
    NSImage *_image;
    NSArray *_colors;
    BOOL _isFlipped;
    double _rowHeight;
    double _rowOffset;
}

@property(retain) NSColor *backgroundColor;
@property(retain) NSArray *backgroundColors;
@property(retain) NSImage *backgroundImage; // @synthesize backgroundImage=_image;
@property(setter=setFlipped:) BOOL isFlipped; // @synthesize isFlipped=_isFlipped;
@property double rowOffset; // @synthesize rowOffset=_rowOffset;
@property double rowHeight; // @synthesize rowHeight=_rowHeight;
@property long long tag; // @synthesize tag=_tag;

- (void)dealloc;
- (BOOL)isOpaque;
- (id)backgroundColor;
- (id)backgroundColors;
- (void)setBackgroundColors:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)colorForRow:(unsigned long long)arg1;
- (id)backgroundImage;
- (void)setBackgroundImage:(id)arg1;
- (BOOL)isFlipped;
- (void)setFlipped:(BOOL)arg1;
- (double)rowOffset;
- (void)setRowOffset:(double)arg1;
- (double)rowHeight;
- (void)setRowHeight:(double)arg1;
- (long long)tag;
- (void)setTag:(long long)arg1;

@end

