/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSView.h"

@class NSColor;

@interface ColorBackgroundView : NSView
{
    int _tag;
    NSColor *_color;
}

- (void)dealloc;
- (int)tag;
- (void)setTag:(int)fp8;
- (id)backgroundColor;
- (void)setBackgroundColor:(id)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (BOOL)isOpaque;

@end

