/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSView.h"

@class NSButton, NSMenu, NSPopUpButton, NSViewAnimation, OptionalView;

@interface ComposeHeaderView : NSView
{
    id _delegate;
    NSPopUpButton *_disclosureButton;
    NSMenu *_actionMenu;
    OptionalView *_toOptionalView;
    OptionalView *_ccOptionalView;
    OptionalView *_subjectOptionalView;
    OptionalView *_bccOptionalView;
    OptionalView *_replyToOptionalView;
    OptionalView *_accountOptionalView;
    OptionalView *_signatureOptionalView;
    OptionalView *_priorityOptionalView;
    OptionalView *_securityOptionalView;
    NSView *_messageContentView;
    NSPopUpButton *_signaturePopUp;
    NSPopUpButton *_accountPopUp;
    NSButton *_cancelButton;
    NSButton *_okButton;
    unsigned int _showCcView:1;
    unsigned int _showBccView:1;
    unsigned int _showReplyToView:1;
    unsigned int _showAccountView:1;
    unsigned int _showSignatureView:1;
    unsigned int _showPriorityView:1;
    unsigned int _showSecurityView:1;
    unsigned int _accountFieldEnabled:1;
    unsigned int _signatureFieldEnabled:1;
    unsigned int _securityFieldEnabled:1;
    unsigned int _resizingViews:1;
    unsigned int _customizing:1;
    unsigned int _changesCancelled:1;
    unsigned int _preCustomizeTile:1;
    NSViewAnimation *_animation;
    float _nextShownFrameOrigin;
    float _nextHiddenFrameOrigin;
    float _heightDelta;
    id _lastFirstResponder;
    float _signaturePopUpMaxWidth;
    float _accountPopUpMaxWidth;
    OptionalView *_togglingOptionalView;
}

- (id)messageContentView;
- (void)setMessageContentView:(id)fp8;
- (BOOL)isFlipped;
- (BOOL)isOpaque;
- (void)viewWillMoveToWindow:(id)fp8;
- (BOOL)isCustomizing;
- (void)dealloc;
- (void)_restoreFirstResponder;
- (void)_noteCurrentFirstResponder;
- (void)_popDisclosureButtonToFront;
- (void)_readVisibleStateFromOptionCheckboxes;
- (void)beginListeningForChildFrameChangeNotifications;
- (void)_setupMenuItemWithAction:(SEL)fp8 withState:(BOOL)fp12;
- (void)_setupActionMenuItemState;
- (void)awakeFromNib;
- (float)_positionView:(id)fp8 yOffset:(float)fp12;
- (BOOL)_shouldShowSecurityViewWhenNotCustomizing;
- (BOOL)_shouldShowSecurityViewWhenCustomizing;
- (BOOL)_shouldShowSecurityView;
- (BOOL)_shouldShowAccountViewWhenNotCustomizing;
- (BOOL)_shouldShowAccountViewWhenCustomizing;
- (BOOL)_shouldShowAccountView;
- (BOOL)_shouldShowSignatureViewWhenNotCustomizing;
- (BOOL)_shouldShowSignatureViewWhenCustomizing;
- (BOOL)_shouldShowSignatureView;
- (BOOL)_shouldShowPriorityViewWhenNotCustomizing;
- (BOOL)_shouldShowPriorityViewWhenCustomizing;
- (BOOL)_shouldShowPriorityView;
- (struct _NSRect)_calculatePriorityFrame:(struct _NSRect)fp8;
- (void)_calculateAccountFrame:(struct _NSRect *)fp8 signatureFrame:(struct _NSRect *)fp12;
- (void)subviewFrameDidChange:(id)fp8;
- (BOOL)isDisplayingBottomControls;
- (void)fixupTabRing;
- (void)tile;
- (void)_addView:(id)fp8 toList:(id)fp12 isVisible:(BOOL)fp16 adjustYOrigin:(BOOL)fp20;
- (void)_recordUserCustomization;
- (void)_customizeHeaders:(BOOL)fp8 duration:(float)fp12;
- (void)resizeWithOldSuperviewSize:(struct _NSSize)fp8;
- (void)_enableActionMenu:(BOOL)fp8;
- (void)sanityCheckHiddenessOfViewsInAnimationList:(id)fp8;
- (void)animationDidEnd:(id)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (void)_finishCustomizingSavingChanges:(BOOL)fp8;
- (void)toggleOptionCheckbox:(id)fp8;
- (void)done:(id)fp8;
- (void)_toggleBccOrReplyToField:(BOOL)fp8;
- (void)toggleBccFieldVisibility:(id)fp8;
- (void)toggleReplyToFieldVisibility:(id)fp8;
- (void)configureHeaders:(id)fp8;
- (void)configureAccountPopUpSize;
- (void)configureSignaturePopUpSize;
- (void)setCcFieldVisible:(BOOL)fp8;
- (void)setBccFieldVisible:(BOOL)fp8;
- (void)setReplyToFieldVisible:(BOOL)fp8;
- (void)setAccountFieldVisible:(BOOL)fp8;
- (void)setSignatureFieldVisible:(BOOL)fp8;
- (void)setPriorityFieldVisible:(BOOL)fp8;
- (BOOL)securityFieldVisible;
- (BOOL)showBccHeader;
- (BOOL)showReplyToHeader;
- (void)setAccountFieldEnabled:(BOOL)fp8;
- (void)setSignatureFieldEnabled:(BOOL)fp8;
- (void)setSecurityFieldEnabled:(BOOL)fp8;

@end

