/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSTextFieldCell.h"

@class NSFont, NSMutableDictionary, NSMutableParagraphStyle, NSMutableString, NSString;

@interface DateCell : NSTextFieldCell
{
    NSFont *_lastFont;
    NSString *_lastDateString;
    NSMutableDictionary *_lastDateAttributes;
    double _absoluteTime;
    int _lastDayInterval;
    NSMutableParagraphStyle *_paragraphStyle;
    NSMutableString *_drawingString;
    NSMutableDictionary *_drawingAttributes;
    unsigned int _underlinesText:1;
    unsigned int _dateDetailLevel:15;
    float _lastWidth;
}

+ (void)initialize;
+ (void)resetDateFormats;
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (float)_widthOfStringWithTimeFormat:(id)fp8 withDatePrefix:(id)fp12;
- (float)_widthOfLongestDateStringWithLevel:(int)fp8 format:(id)fp12;
- (void)_saveWidthsToDefaults;
- (BOOL)_readWidthsFromDefaults;
- (void)_updateDateColumnDetailLevelWidths;
- (BOOL)_updateDateColumnDetailLevels;
- (float)minimumWidth;
- (struct _NSRect)drawingRectForBounds:(struct _NSRect)fp8;
- (void)_generateLastDateStringForRect:(struct _NSRect)fp8;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)setTimeIntervalSince1970:(double)fp8;
- (void)setObjectValue:(id)fp8;
- (void)setFont:(id)fp8;
- (void)setNeedsDisplay:(BOOL)fp8;
- (BOOL)underlinesText;
- (void)setUnderlinesText:(BOOL)fp8;
- (id)accessibilityAttributeValue:(id)fp8;

@end

