/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "MessageDeletionTransfer-Protocol.h"

@class MonitoredInvocation;

@interface DeleteMailboxTransfer <MessageDeletionTransfer>
{
    MonitoredInvocation *invocation;
}

@property(retain) MonitoredInvocation *invocation; // @synthesize invocation;
// Preceeding property had unknown attributes: N
// Original attribute string: T@"MonitoredInvocation",&,N,Vinvocation


- (BOOL)canBeginTransfer;
- (void)beginTransfer;
- (void)dealloc;
- (id)invocation;
- (void)setInvocation:(id)arg1;

@end

