/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "DOMNode.h"

@interface DOMNode (MailExtras)
- (id)stringValue;
- (BOOL)isBlockLevelElement;
- (BOOL)hasNoContents;
- (int)quoteLevel;
- (int)quoteLevelDelta;
- (id)commonAncestorWithNode:(id)fp8;
- (BOOL)containsRichText;
- (BOOL)_isAppleStringAttachmentSpan;
- (void)recursivelyRemoveMailAttributesConvertingObjectsToImages:(BOOL)fp8;
- (void)recursivelyRemoveMailAttributes;
- (void)recursivelyFixParagraphs;
- (void)fixParagraphsAndQuotesFromMicrosoftNodesToRemove:(id)fp8;
- (void)fixParagraphsAndQuotesFromMicrosoft;
@end

