/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "DOMRange.h"

@interface DOMRange (MailExtras)
- (BOOL)isEquivalentToCollapsedRange;
- (id)stringValue;
- (void)getLineBoundaryParent:(id *)fp8 nextSibling:(id *)fp12 affinity:(int)fp16;
- (void)fixIfEndpointIsAtBeginningOfLine;
- (void)fixIfStartIsAtEndOfContainerNode;
- (BOOL)containsRichText;
- (id)attachmentsFromDocument:(id)fp8;
- (void)insertTextAtBeginning:(id)fp8 atEnd:(id)fp12;
@end

