/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSTableColumn.h"

@interface EditingTableColumn : NSTableColumn
{
    int rowBeingEdited;
}

- (void)awakeFromNib;
- (void)beginEditingRow:(int)fp8;
- (void)endEditing;
- (int)rowBeingEdited;
- (id)dataCellForRow:(int)fp8;

@end

