/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSView.h"

@class NSColor;

@interface FocusView : NSView
{
    struct _NSSize _inset;
    struct _NSSize _thickness;
    NSColor *_color;
    BOOL _alwaysVisible;
}

- (void)_setFocusNeedsDisplay;
- (void)setRepresentedView:(id)fp8;
- (void)dealloc;
- (void)removeFromSuperview;
- (id)initWithFrame:(struct _NSRect)fp8;
- (BOOL)isOpaque;
- (void)drawRect:(struct _NSRect)fp8;
- (void)setNeedsDisplayInRect:(struct _NSRect)fp8;
- (void)setInset:(struct _NSSize)fp8;
- (void)setThickness:(struct _NSSize)fp8;
- (void)setColor:(id)fp8;
- (void)setAlwaysVisible:(BOOL)fp8;
- (BOOL)isAlwaysVisible;
- (id)hitTest:(struct _NSPoint)fp8;

@end

