/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class FontPreferenceContainerView, NSArray, NSFont, NSMutableDictionary, NSPopUpButton, NSTextView;

@interface FontsAndColorsPreferences
{
    FontPreferenceContainerView *_mailboxListContainerView;
    FontPreferenceContainerView *_messageListContainerView;
    FontPreferenceContainerView *_messageTextContainerView;
    FontPreferenceContainerView *_noteTextContainerView;
    FontPreferenceContainerView *_fixedWidthContainerView;
    NSArray *_fontPrefContainerViews;
    double _containerSuperViewSpacingY;
    double _containerContainerSpacingY;
    int _changingFontPreference;
    NSMutableDictionary *_midYDict;
    NSFont *_mailboxListFont;
    NSFont *_messageListFont;
    NSFont *_messageFont;
    NSFont *_noteFont;
    NSFont *_fixedWidthFont;
    NSPopUpButton *colorPopupOne;
    NSPopUpButton *colorPopupTwo;
    NSPopUpButton *colorPopupThree;
    NSPopUpButton *lastColorPopupSelected;
    NSTextView *exampleTextView;
    NSArray *_colorList;
    BOOL _isQuotedTextColored;
    BOOL _isPlainTextOfFixedWidth;
}

@property(retain) NSArray *colorList; // @synthesize colorList=_colorList;
@property BOOL isPlainTextOfFixedWidth; // @synthesize isPlainTextOfFixedWidth=_isPlainTextOfFixedWidth;
@property BOOL isQuotedTextColored; // @synthesize isQuotedTextColored=_isQuotedTextColored;
@property(readonly) NSFont *fixedWidthSampleFont;
// Preceeding property had unknown attributes: D
// Original attribute string: T@"NSFont",R,D

@property(readonly) NSFont *noteSampleFont;
// Preceeding property had unknown attributes: D
// Original attribute string: T@"NSFont",R,D

@property(readonly) NSFont *messageSampleFont;
// Preceeding property had unknown attributes: D
// Original attribute string: T@"NSFont",R,D

@property(readonly) NSFont *messageListSampleFont;
// Preceeding property had unknown attributes: D
// Original attribute string: T@"NSFont",R,D

@property(readonly) NSFont *mailboxListSampleFont;
// Preceeding property had unknown attributes: D
// Original attribute string: T@"NSFont",R,D

@property(retain) NSFont *fixedWidthFont; // @synthesize fixedWidthFont=_fixedWidthFont;
@property(retain) NSFont *noteFont; // @synthesize noteFont=_noteFont;
@property(retain) NSFont *messageFont; // @synthesize messageFont=_messageFont;
@property(retain) NSFont *messageListFont; // @synthesize messageListFont=_messageListFont;
@property(retain) NSFont *mailboxListFont; // @synthesize mailboxListFont=_mailboxListFont;

+ (id)keyPathsForValuesAffectingMailboxListSampleFont;
+ (id)keyPathsForValuesAffectingMessageListSampleFont;
+ (id)keyPathsForValuesAffectingMessageSampleFont;
+ (id)keyPathsForValuesAffectingNoteSampleFont;
+ (id)keyPathsForValuesAffectingFixedWidthSampleFont;
- (void)awakeFromNib;
- (void)dealloc;
- (void)initializeFromDefaults;
- (void)growWindowVertically:(double)arg1 animate:(BOOL)arg2;
- (void)updateAutoresizeFlags:(int)arg1;
- (void)layoutFromFontPreference:(int)arg1;
- (BOOL)isResizable;
- (id)titleForIdentifier:(id)arg1;
- (id)windowTitle;
- (void)_replaceExampleTextView;
- (id)mailboxListSampleFont;
- (id)messageListSampleFont;
- (id)messageSampleFont;
- (id)noteSampleFont;
- (id)fixedWidthSampleFont;
- (id)_sampleFontForFont:(id)arg1;
- (void)populateFontPrefContainers;
- (void)moduleWillBeRemoved;
- (void)selectFont:(id)arg1;
- (void)toggleColorQuotedText:(id)arg1;
- (void)toggleUseFixedWidthFont:(id)arg1;
- (id)containerViewForFontPreference:(int)arg1;
- (double)sizeContainerView:(id)arg1;
- (void)changeFont:(id)arg1;
- (void)_setOtherColor:(id)arg1 forPopup:(id)arg2;
- (void)_setColor:(id)arg1 forPopup:(id)arg2;
- (void)_updateExampleTextView;
- (void)_updateColorList;
- (void)colorQuotesButtonClicked:(id)arg1;
- (void)colorPopupChanged:(id)arg1;
- (void)colorPicked:(id)arg1;
- (id)colorList;
- (void)setColorList:(id)arg1;
- (BOOL)isPlainTextOfFixedWidth;
- (void)setIsPlainTextOfFixedWidth:(BOOL)arg1;
- (BOOL)isQuotedTextColored;
- (void)setIsQuotedTextColored:(BOOL)arg1;
- (id)fixedWidthFont;
- (void)setFixedWidthFont:(id)arg1;
- (id)noteFont;
- (void)setNoteFont:(id)arg1;
- (id)messageFont;
- (void)setMessageFont:(id)arg1;
- (id)messageListFont;
- (void)setMessageListFont:(id)arg1;
- (id)mailboxListFont;
- (void)setMailboxListFont:(id)arg1;

@end

