/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSPreferencesModule.h"

@class NSArray, NSButton, NSComboBox, NSPopUpButton, NSTextView;

@interface FontsAndColorsPreferences : NSPreferencesModule
{
    NSPopUpButton *mailboxListFontPopup;
    NSComboBox *mailboxListFontSizePopup;
    NSPopUpButton *messageListFontPopup;
    NSComboBox *messageListFontSizePopup;
    NSPopUpButton *messageFontPopup;
    NSComboBox *messageFontSizePopup;
    NSPopUpButton *fixedPitchFontPopup;
    NSComboBox *fixedPitchFontSizePopup;
    NSButton *fixedPitchSwitch;
    NSPopUpButton *colorPopupOne;
    NSPopUpButton *colorPopupTwo;
    NSPopUpButton *colorPopupThree;
    NSPopUpButton *lastColorPopupSelected;
    NSButton *colorQuotesButton;
    NSTextView *exampleTextView;
    NSArray *colorList;
    BOOL colorizeIncomingMail;
}

- (void)initializeFromDefaults;
- (void)_setFontMenuForPopup:(id)fp8 fixedPitchOnly:(BOOL)fp12;
- (BOOL)isResizable;
- (id)titleForIdentifier:(id)fp8;
- (id)windowTitle;
- (void)awakeFromNib;
- (void)useFixedPitchFontClicked:(id)fp8;
- (void)_setOtherColor:(id)fp8 forPopup:(id)fp12;
- (void)_setColor:(id)fp8 forPopup:(id)fp12;
- (void)_updateExampleColors;
- (void)_updateColorList;
- (void)colorQuotesButtonClicked:(id)fp8;
- (void)colorPopupChanged:(id)fp8;
- (void)colorPicked:(id)fp8;
- (BOOL)_setTitle:(id)fp8 forPopup:(id)fp12;
- (void)_setTitle:(id)fp8 forComboBox:(id)fp12;
- (void)mailboxListFontChanged:(id)fp8;
- (void)mailboxListFontSizeChanged:(id)fp8;
- (void)messageListFontChanged:(id)fp8;
- (void)messageListFontSizeChanged:(id)fp8;
- (void)messageFontChanged:(id)fp8;
- (void)setMessageFont:(id)fp8 size:(float)fp12;
- (void)setFixedPitchFont:(id)fp8 size:(float)fp12;
- (void)fixedPitchFontChanged:(id)fp8;
- (void)fontPopupChanged:(id)fp8;

@end

