/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSPreferencesModule.h"

#import "SyncableDataInterestedPartyProtocol.h"

@interface JunkPreferences : NSPreferencesModule <SyncableDataInterestedParty>
{
    id _textLabel1;
    id _textLabel2;
    id _advancedButton;
    id _resetButton;
    id _junkMailMode;
    id _junkMailOnOffSwitch;
    id _junkMailWhitelist;
    id _useJunkMailHeaderFlags;
}

- (void)moduleWillBeRemoved;
- (void)moduleWasInstalled;
- (BOOL)isResizable;
- (void)_messageRuleChanged:(id)fp8;
- (id)titleForIdentifier:(id)fp8;
- (id)windowTitle;
- (id)imageForPreferenceNamed:(id)fp8;
- (BOOL)dataWillBeSynced;
- (void)dataWasSynced;
- (void)setAllEnabled:(BOOL)fp8;
- (void)initializeFromDefaults;
- (void)showJunkMailInfoPanel:(id)fp8;
- (void)junkMailToggled:(id)fp8;
- (void)whitelistChanged:(id)fp8;
- (void)setJunkMailBehavior:(int)fp8;
- (void)changeJunkMailBehavior:(id)fp8;
- (void)resetJunkMailMap:(id)fp8;
- (void)showCustomJunkMailSettings:(id)fp8;
- (void)useJunkMailHeaderFlagsToggled:(id)fp8;

@end

