/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class ActivityMonitor, NSProgressIndicator, NSString, NSTextField, NSView;

@interface LoadingOverlay
{
    NSView *_overlayView;
    NSProgressIndicator *_progressIndicator;
    NSTextField *_statusMessageField;
    ActivityMonitor *_monitor;
    id _modalDelegate;
}

@property(retain) NSString *statusMessage;
@property id modalDelegate; // @synthesize modalDelegate=_modalDelegate;
@property(readonly) NSView *overlayView; // @synthesize overlayView=_overlayView;
@property(retain) ActivityMonitor *activityMonitor; // @synthesize activityMonitor=_monitor;

- (id)initWithModalDelegate:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)displayInSuperview:(id)arg1;
- (void)displayInSuperviewAfterDelay:(id)arg1;
- (void)setActivityMonitor:(id)arg1;
- (void)setStatusMessage:(id)arg1;
- (id)statusMessage;
- (void)activityEnded:(id)arg1;
- (id)modalDelegate;
- (void)setModalDelegate:(id)arg1;
- (id)overlayView;
- (id)activityMonitor;

@end

