/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSImage, NSView, VerticalSplitViewHandle;

@interface MailboxPaneBottomView
{
    NSView *rightButton;
    VerticalSplitViewHandle *splitViewHandle;
    NSImage *buttonEdge;
    NSImage *filler;
}

- (void)awakeFromNib;
- (void)dealloc;
- (BOOL)isOpaque;
- (void)drawRect:(struct CGRect)arg1;

@end

