/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSView.h"

@class MailToolbarItem, NSSegmentedControl;

@interface MailToolbarItemView : NSView
{
    MailToolbarItem *_item;
    NSSegmentedControl *_button;
    NSSegmentedControl *_label;
    int _tag;
}

+ (void)initialize;
- (id)initWithItem:(id)fp8;
- (void)dealloc;
- (id)toolbarItem;
- (BOOL)_isInPaletteView;
- (BOOL)_isInMainToolbarView;
- (void)_layoutIconAndLabelForDisplayMode:(int)fp8;
- (float)_itemHeightForDisplayMode:(int)fp8;
- (void)configureForDisplayMode:(int)fp8 andSizeMode:(int)fp12;
- (void)setLabel:(id)fp8 forSegment:(int)fp12;
- (void)setImage:(id)fp8 forSegment:(int)fp12;
- (void)setToolTip:(id)fp8 forSegment:(int)fp12;
- (void)setEnabled:(BOOL)fp8 forSegment:(int)fp12;
- (BOOL)isEnabledForSegment:(int)fp8;
- (void)_performAction:(id)fp8;
- (void)setFrameOrigin:(struct _NSPoint)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (void)viewWillMoveToWindow:(id)fp8;
- (void)viewDidMoveToWindow;
- (int)tag;
- (void)setTag:(int)fp8;

@end

