/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface MailboxesOutlineView
{
    BOOL _allowsSelectAll;
    BOOL _acceptsFirstResponderOnMouseDown;
    BOOL _showsUnnecessaryDisclosureTriangles;
    BOOL _draggingIsBeingUpdated;
    BOOL _reloading;
}

@property BOOL draggingIsBeingUpdated; // @synthesize draggingIsBeingUpdated=_draggingIsBeingUpdated;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,V_draggingIsBeingUpdated

@property BOOL showsUnnecessaryDisclosureTriangles; // @synthesize showsUnnecessaryDisclosureTriangles=_showsUnnecessaryDisclosureTriangles;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,V_showsUnnecessaryDisclosureTriangles

@property BOOL acceptsFirstResponderOnMouseDown; // @synthesize acceptsFirstResponderOnMouseDown=_acceptsFirstResponderOnMouseDown;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,V_acceptsFirstResponderOnMouseDown

@property BOOL allowsSelectAll; // @synthesize allowsSelectAll=_allowsSelectAll;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,V_allowsSelectAll


- (id)initWithCoder:(id)arg1;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (struct CGRect)frameOfOutlineCellAtRow:(long long)arg1;
- (void)keyDown:(id)arg1;
- (BOOL)acceptsFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
- (void)mouseDown:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)selectAll:(id)arg1;
- (void)editColumn:(long long)arg1 row:(long long)arg2 withEvent:(id)arg3 select:(BOOL)arg4;
- (id)menuForEvent:(id)arg1;
- (BOOL)canFocusCell:(id)arg1 atTableColumn:(id)arg2 row:(long long)arg3;
- (BOOL)shouldCollapseAutoExpandedItemsForDeposited:(BOOL)arg1;
- (BOOL)inLiveResize;
- (void)_willReload;
- (void)_triggerReloadNotification;
- (void)_didReload;
- (void)noteNumberOfRowsChanged;
- (void)reloadData;
- (void)reloadItem:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (BOOL)draggingIsBeingUpdated;
- (void)setDraggingIsBeingUpdated:(BOOL)arg1;
- (BOOL)showsUnnecessaryDisclosureTriangles;
- (void)setShowsUnnecessaryDisclosureTriangles:(BOOL)arg1;
- (BOOL)acceptsFirstResponderOnMouseDown;
- (void)setAcceptsFirstResponderOnMouseDown:(BOOL)arg1;
- (BOOL)allowsSelectAll;
- (void)setAllowsSelectAll:(BOOL)arg1;

@end

