/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class MailboxUid, NSPopUpButton;

@interface MailboxesChooser : NSObject
{
    NSPopUpButton *popUpButton;
    MailboxUid *_selectedMailbox;
    MailboxUid *_targetMailboxForCycleChecks;
    BOOL includeSmartMailboxes;
    id _realTarget;
    SEL _realAction;
}

- (void)dealloc;
- (void)setShouldCheckCyclesToSmartMailbox:(id)fp8;
- (void)cellWillPopUp:(id)fp8;
- (void)disableCyclicItemsInMenu:(id)fp8;
- (void)disableCyclicMailboxesInItems:(id)fp8;
- (void)reset;
- (void)awakeFromNib;
- (void)_cancelMenuTracking:(id)fp8;
- (id)popUpButton;
- (void)setPopUpButton:(id)fp8;
- (void)_mailboxWasRenamed:(id)fp8;
- (void)_ensureSelectionIsValid:(id)fp8;
- (void)_popUpPressed:(id)fp8;
- (void)setSelectedMailbox:(id)fp8;
- (id)selectedMailbox;
- (void)setIncludesSmartMailboxes:(BOOL)fp8;

@end

