/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "MailApp.h"

@interface MailApp (AppleScriptFontsAndColorsPreferences)
- (BOOL)colorQuotedText;
- (void)setColorQuotedText:(BOOL)fp8;
- (id)mailboxListFont;
- (void)setMailboxListFont:(id)fp8;
- (float)mailboxListFontSize;
- (void)setMailboxListFontSize:(float)fp8;
- (id)messageListFont;
- (void)setMessageListFont:(id)fp8;
- (float)messageListFontSize;
- (void)setMessageListFontSize:(float)fp8;
- (id)messageFont;
- (void)setMessageFont:(id)fp8;
- (float)messageFontSize;
- (void)setMessageFontSize:(float)fp8;
- (BOOL)useFixedWidthFont;
- (void)setUseFixedWidthFont:(BOOL)fp8;
- (id)fixedWidthFont;
- (void)setFixedWidthFont:(id)fp8;
- (float)fixedWidthFontSize;
- (void)setFixedWidthFontSize:(float)fp8;
- (void)setQuotingColor:(int)fp8 forLevel:(int)fp12;
- (int)quotingColorForLevel:(int)fp8;
- (int)quotingColorValue:(id)fp8;
- (int)levelOneQuotingColor;
- (void)setLevelOneQuotingColor:(int)fp8;
- (int)levelTwoQuotingColor;
- (void)setLevelTwoQuotingColor:(int)fp8;
- (int)levelThreeQuotingColor;
- (void)setLevelThreeQuotingColor:(int)fp8;
@end

