/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSMenuDelegate-Protocol.h"

@class NSArray, NSMenu, NSMutableSet, NSPopUpButton;

@interface MailboxesChooser <NSMenuDelegate>
{
    NSMenu *_rootMenu;
    NSPopUpButton *_popUpButton;
    id _includeMailboxCondition;
    id _enableMailboxCondition;
    id _selectedItem;
    id _target;
    SEL _action;
    NSArray *_additionalItems;
    NSMutableSet *_updatedMenus;
}

@property(retain) NSArray *additionalItems; // @synthesize additionalItems=_additionalItems;
// Preceeding property had unknown attributes: N
// Original attribute string: T@"NSArray",&,N,V_additionalItems

@property SEL action; // @synthesize action=_action;
// Preceeding property had unknown attributes: N
// Original attribute string: T:,N,V_action

@property id target; // @synthesize target=_target;
// Preceeding property had unknown attributes: N
// Original attribute string: T@,N,V_target

@property(retain) id selectedItem; // @synthesize selectedItem=_selectedItem;
// Preceeding property had unknown attributes: N
// Original attribute string: T@,&,N,V_selectedItem

@property(copy) id enableMailboxCondition; // @synthesize enableMailboxCondition=_enableMailboxCondition;
// Preceeding property had unknown attributes: N
// Original attribute string: T@?,C,N,V_enableMailboxCondition

@property(copy) id includeMailboxCondition; // @synthesize includeMailboxCondition=_includeMailboxCondition;
// Preceeding property had unknown attributes: N
// Original attribute string: T@?,C,N,V_includeMailboxCondition

@property NSPopUpButton *popUpButton; // @synthesize popUpButton=_popUpButton;
// Preceeding property had unknown attributes: N
// Original attribute string: T@"NSPopUpButton",N,V_popUpButton

@property NSMenu *rootMenu; // @synthesize rootMenu=_rootMenu;
// Preceeding property had unknown attributes: N
// Original attribute string: T@"NSMenu",N,V_rootMenu


+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
- (id)init;
- (id)initWithSelection:(BOOL)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (void)_mailboxesChooserCommonInitWithSelection:(BOOL)arg1;
- (void)_setupPopUpButton;
- (void)setRootMenu:(id)arg1;
- (void)setPopUpButton:(id)arg1;
- (void)setSelectedItem:(id)arg1;
- (id)menuItemForItem:(id)arg1 indentationLevel:(long long)arg2;
- (void)addMenuItemsForItems:(id)arg1 toMenu:(id)arg2 withIndentationLevel:(long long)arg3;
- (void)_addMenuItemsForItems:(id)arg1 toMenu:(id)arg2 withIndentationLevel:(long long)arg3 initialSeparatorItem:(BOOL)arg4;
- (void)invalidateUpdatedMenus;
- (void)_invalidateUpdatedMenus:(id)arg1;
- (void)_outlineViewStateDidChange:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)refresh;
- (void)popUpAction:(id)arg1;
- (void)menuDidClose:(id)arg1;
- (id)additionalItems;
- (void)setAdditionalItems:(id)arg1;
- (SEL)action;
- (void)setAction:(SEL)arg1;
- (id)target;
- (void)setTarget:(id)arg1;
- (id)selectedItem;
- (id)enableMailboxCondition;
- (void)setEnableMailboxCondition:(id)arg1;
- (id)includeMailboxCondition;
- (void)setIncludeMailboxCondition:(id)arg1;
- (id)popUpButton;
- (id)rootMenu;

@end

