/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface MailPreferences
{
}

+ (void)configureFetchFrequencyPopUp:(id)arg1 forMessageType:(BOOL)arg2;
- (id)init;
- (id)windowTitle;
- (void)changeFont:(id)arg1;
- (unsigned long long)validModesForFontPanel:(id)arg1;
- (BOOL)fontManager:(id)arg1 willIncludeFont:(id)arg2;
- (void)windowWillClose:(id)arg1;

@end

