/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSImage;

@interface MailScroller
{
    NSImage *paddingImage;
    NSImage *hiddenImage;
    NSImage *slotStartImage;
    NSImage *slotMiddleImage;
    NSImage *slotEndImage;
    NSImage *knobStartImage;
    NSImage *knobMiddleImage;
    NSImage *knobEndImage;
    double startPadding;
    double endPadding;
    BOOL isVertical;
}

@property BOOL isVertical; // @synthesize isVertical;
@property double endPadding; // @synthesize endPadding;
@property double startPadding; // @synthesize startPadding;
@property(retain) NSImage *knobEndImage; // @synthesize knobEndImage;
@property(retain) NSImage *knobMiddleImage; // @synthesize knobMiddleImage;
@property(retain) NSImage *knobStartImage; // @synthesize knobStartImage;
@property(retain) NSImage *slotEndImage; // @synthesize slotEndImage;
@property(retain) NSImage *slotMiddleImage; // @synthesize slotMiddleImage;
@property(retain) NSImage *slotStartImage; // @synthesize slotStartImage;
@property(retain) NSImage *hiddenImage; // @synthesize hiddenImage;
@property(retain) NSImage *paddingImage; // @synthesize paddingImage;

- (id)initWithFrame:(struct CGRect)arg1 isVertical:(BOOL)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (struct CGRect)_rectWithRect:(struct CGRect)arg1 offset:(double)arg2 length:(double)arg3;
- (double)_getLengthFromSize:(struct CGSize)arg1;
- (double)_getLengthFromImage:(id)arg1;
- (struct CGRect)_drawingRectForCustomPart:(int)arg1;
- (struct CGRect)_drawingRectForPart:(unsigned long long)arg1;
- (struct CGRect)rectForPart:(unsigned long long)arg1;
- (BOOL)isUseful;
- (void)drawImage:(id)arg1 asPart:(int)arg2 withDirtyRect:(struct CGRect)arg3;
- (void)drawRect:(struct CGRect)arg1;
- (void)setImagesFlipped:(BOOL)arg1;
- (BOOL)isOpaque;
- (BOOL)isVertical;
- (void)setIsVertical:(BOOL)arg1;
- (double)endPadding;
- (void)setEndPadding:(double)arg1;
- (double)startPadding;
- (void)setStartPadding:(double)arg1;
- (id)knobEndImage;
- (void)setKnobEndImage:(id)arg1;
- (id)knobMiddleImage;
- (void)setKnobMiddleImage:(id)arg1;
- (id)knobStartImage;
- (void)setKnobStartImage:(id)arg1;
- (id)slotEndImage;
- (void)setSlotEndImage:(id)arg1;
- (id)slotMiddleImage;
- (void)setSlotMiddleImage:(id)arg1;
- (id)slotStartImage;
- (void)setSlotStartImage:(id)arg1;
- (id)hiddenImage;
- (void)setHiddenImage:(id)arg1;
- (id)paddingImage;
- (void)setPaddingImage:(id)arg1;

@end

