/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "MailAccessibilitySegment.h"

@interface MailToolbarLabelAccessibilitySegment : MailAccessibilitySegment
{
}

- (BOOL)_isAccessible;
- (BOOL)accessibilityIsIgnored;
- (id)accessibilityParentAttribute;
- (id)accessibilityHitTest:(struct _NSPoint)fp8;
- (id)accessibilityFocusedUIElement;

@end

