/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSActionCell.h"

@class NSMutableArray;

@interface MailSegmentedCell : NSActionCell
{
    NSMutableArray *_segmentItems;
    int _selectedSegment;
    int _keySegment;
    struct _NSRect _lastBounds;
    struct {
        unsigned int trackingMode:3;
        unsigned int trimmedLabels:1;
        unsigned int drawing:1;
        unsigned int recalcToolTips:1;
        unsigned int reserved:26;
    } _seFlags;
    unsigned int _reserved1;
    unsigned int _reserved2;
    unsigned int _reserved3;
    unsigned int _reserved4;
    int _highlightedSegment;
    unsigned int _showRollover:1;
    int _rolloverSegment;
    NSMutableArray *_trackingRectTags;
}

+ (void)initialize;
+ (id)menuIndicator:(int)fp8;
+ (id)leftButtonCap:(int)fp8 value:(int)fp12 tint:(int)fp16 controlSize:(int)fp20;
+ (id)rightButtonCap:(int)fp8 value:(int)fp12 tint:(int)fp16 controlSize:(int)fp20;
+ (id)buttonSeparator:(int)fp8 value:(int)fp12 tint:(int)fp16 controlSize:(int)fp20;
+ (id)buttonFillColorPattern:(int)fp8 value:(int)fp12 tint:(int)fp16 controlSize:(int)fp20;
+ (id)leftSeparator:(int)fp8 value:(int)fp12 tint:(int)fp16 controlSize:(int)fp20;
+ (id)rightSeparator:(int)fp8 value:(int)fp12 tint:(int)fp16 controlSize:(int)fp20;
+ (int)segmentedCellStyle;
+ (id)labelCell;
+ (const struct MailSegmentedCellMetrics *)metricsForControlSize:(int)fp8;
+ (id)disabledColor;
+ (BOOL)_performKeyEquivalentOnAllCells:(id)fp8;
+ (BOOL)prefersTrackingUntilMouseUp;
- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (void)setSegmentCount:(int)fp8;
- (int)segmentCount;
- (void)setSelectedSegment:(int)fp8;
- (int)_trackingSegment;
- (int)selectedSegment;
- (BOOL)selectSegmentWithTag:(int)fp8;
- (int)indexOfSelectedItem;
- (int)_keySegment;
- (void)_setKeySegment:(int)fp8;
- (void)makeNextSegmentKey;
- (void)makePreviousSegmentKey;
- (BOOL)acceptsFirstResponder;
- (void)setTrackingMode:(int)fp8;
- (int)trackingMode;
- (void)setObjectValue:(id)fp8;
- (id)objectValue;
- (void)setWidth:(float)fp8 forSegment:(int)fp12;
- (float)widthForSegment:(int)fp8;
- (void)setWidthForAllSegments:(float)fp8;
- (void)setImage:(id)fp8 forSegment:(int)fp12;
- (id)imageForSegment:(int)fp8;
- (void)setLabel:(id)fp8 forSegment:(int)fp12;
- (id)labelForSegment:(int)fp8;
- (void)setSelected:(BOOL)fp8 forSegment:(int)fp12;
- (BOOL)isSelectedForSegment:(int)fp8;
- (void)setEnabled:(BOOL)fp8 forSegment:(int)fp12;
- (BOOL)isEnabledForSegment:(int)fp8;
- (void)setMenu:(id)fp8 forSegment:(int)fp12;
- (id)menuForSegment:(int)fp8;
- (void)setToolTip:(id)fp8 forSegment:(int)fp12;
- (id)toolTipForSegment:(int)fp8;
- (void)setTag:(int)fp8 forSegment:(int)fp12;
- (int)tagForSegment:(int)fp8;
- (void)setMenuIndicatorShown:(BOOL)fp8 forSegment:(int)fp12;
- (BOOL)isMenuIndicatorShownForSegment:(int)fp8;
- (void)_focusDidChange:(id)fp8;
- (void)_clearMouseTracking;
- (void)_setMouseTrackingInRect:(struct _NSRect)fp8 ofView:(id)fp24 forSegment:(int)fp28;
- (void)_setMouseTrackingForSegment:(int)fp8;
- (void)resetTrackingRects;
- (void)removeTrackingRects;
- (void)setShowRollover:(BOOL)fp8;
- (BOOL)showRollover;
- (void)setFont:(id)fp8;
- (void)setControlSize:(int)fp8;
- (struct _NSSize)cellSizeForBounds:(struct _NSRect)fp8;
- (void)_makeEqualSizeSegments;
- (struct _NSRect)drawingRectForBounds:(struct _NSRect)fp8;
- (BOOL)isOpaque;
- (const struct MailSegmentedCellMetrics *)metrics;
- (struct _NSRect)_boundsForCellFrame:(struct _NSRect)fp8;
- (struct _NSRect)_rectForSegment:(int)fp8 inFrame:(struct _NSRect)fp12;
- (void)drawFocusRingForSegment:(int)fp8 inFrame:(struct _NSRect)fp12 withView:(id)fp28;
- (void)drawBackgroundWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)drawWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)drawInteriorWithFrame:(struct _NSRect)fp8 inView:(id)fp24;
- (void)drawLabelForSegment:(int)fp8 inFrame:(struct _NSRect)fp12 withView:(id)fp28;
- (void)drawImageForSegment:(int)fp8 inFrame:(struct _NSRect)fp12 withView:(id)fp28;
- (void)drawSegment:(int)fp8 inFrame:(struct _NSRect)fp12 withView:(id)fp28;
- (BOOL)_needRedrawOnWindowChangedKeyState;
- (BOOL)trackMouse:(id)fp8 inRect:(struct _NSRect)fp12 ofView:(id)fp28 untilMouseUp:(BOOL)fp32;
- (BOOL)startTrackingAt:(struct _NSPoint)fp8 inView:(id)fp16;
- (BOOL)continueTracking:(struct _NSPoint)fp8 at:(struct _NSPoint)fp16 inView:(id)fp24;
- (void)_selectHighlightedSegment;
- (void)stopTracking:(struct _NSPoint)fp8 at:(struct _NSPoint)fp16 inView:(id)fp24 mouseIsUp:(BOOL)fp28;
- (BOOL)_sendActionFrom:(id)fp8;
- (void)performClick:(id)fp8;
- (void)_calculateSelectedSegmentForPoint:(struct _NSPoint)fp8;
- (void)_trackSelectedItemMenu;
- (void)_displayDelayedMenu;
- (BOOL)_needsRedrawOnMouseInsideChange;
- (void)_mouseEnteredOrExitedSegment:(id)fp8;
- (void)mouseEntered:(id)fp8;
- (void)mouseExited:(id)fp8;
- (void)setControlView:(id)fp8;
- (BOOL)_needsToolTipRecalc;
- (void)_setNeedsToolTipRecalc:(BOOL)fp8;
- (BOOL)_hasItemTooltips;
- (void)_removeAllToolTips;

@end

