/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "MessageEditor.h"

@interface MessageEditor (MessageEditorToolbar)
- (BOOL)validateToolbarItem:(id)fp8 forSegment:(int)fp12;
- (void)_setupToolBarOnWindow:(id)fp8 messageType:(int)fp12;
- (void)_synchronizeChangeReplyItem:(id)fp8 messageType:(int)fp12;
- (void)toggleReplytype:(int)fp8;
- (void)_updateSendButtonStateInToolbar;
- (void)toolbarWillAddItem:(id)fp8;
- (id)toolbar:(id)fp8 itemForItemIdentifier:(id)fp12 willBeInsertedIntoToolbar:(BOOL)fp16;
- (id)toolbarDefaultItemIdentifiers:(id)fp8;
- (id)toolbarAllowedItemIdentifiers:(id)fp8;
@end

