/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "MessageViewer.h"

@interface MessageViewer (MessageViewerToolbar)
- (void)_setupToolBar;
- (BOOL)validateToolbarItem:(id)fp8 forSegment:(int)fp12;
- (id)toolbar:(id)fp8 itemForItemIdentifier:(id)fp12 willBeInsertedIntoToolbar:(BOOL)fp16;
- (void)setupSearchView:(BOOL)fp8;
- (void)_handleCancelSearchButton:(id)fp8;
- (id)toolbarDefaultItemIdentifiers:(id)fp8;
- (id)toolbarAllowedItemIdentifiers:(id)fp8;
- (void)_reallyUpdateToolbar:(BOOL)fp8;
- (void)_updateToolbarForResizing:(BOOL)fp8;
- (void)toolbarDidRemoveItem:(id)fp8;
- (void)toolbarWillAddItem:(id)fp8;
- (void)toolbarDidMoveItem:(id)fp8;
- (void)toolbarDidReplaceAllItems:(id)fp8;
- (void)_mailboxesViewFrameChanged;
- (void)_mailboxesViewDidEndLiveResize;
@end

