/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSFont.h"

@interface NSFont (MailAdditions)
+ (id)mailboxListFont;
+ (id)mailboxListFontName;
+ (void)setMailboxListFontName:(id)fp8;
+ (float)mailboxListFontSize;
+ (void)setMailboxListFontSize:(float)fp8;
+ (id)messageListFont;
+ (id)messageListFontName;
+ (void)setMessageListFontName:(id)fp8;
+ (float)messageListFontSize;
+ (void)setMessageListFontSize:(float)fp8;
+ (id)addressFieldFont;
+ (id)prefsAddressFieldFont;
+ (id)validFontName:(id)fp8 fixedPitchOnly:(BOOL)fp12;
@end

