/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

#import "NSView.h"

@interface NSView (LocatingFrameViews)
- (id)enclosingFrameView;
- (id)enclosingWebView;
- (id)enclosingScrollViewIgnoringWebScrollbars;
@end

