/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "NSObject.h"

@class NSImage, NSMutableDictionary;

@interface PresenceTracker : NSObject
{
    NSMutableDictionary *personIDToStatus;
    NSMutableDictionary *emailToPerson;
    BOOL isListening;
    NSImage *availableStatusImage;
}

+ (id)sharedInstance;
- (id)availableStatusImage;
- (id)init;
- (void)dealloc;
- (void)updatePersonInfo:(id)fp8 forService:(id)fp12;
- (void)updateBuddyInfo:(id)fp8 forService:(id)fp12;
- (void)startListening;
- (void)stopListening;
- (void)_addEmailToPersonMapping:(id)fp8;
- (void)_rebuildEmailToUID;
- (void)myStatusChanged:(id)fp8;
- (void)personChanged:(id)fp8;
- (void)presenceChanged:(id)fp8;
- (BOOL)personWithEmailIsOnline:(id)fp8;
- (id)addressCardUIDForEmail:(id)fp8;
- (void)_addressBookChanged:(id)fp8;
- (void)statusImagesChanged:(id)fp8;

@end

