/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class MessageAttachmentViewController;

@interface QuickTimeAttachmentView
{
    MessageAttachmentViewController *_attachmentViewController;
}

@property MessageAttachmentViewController *attachmentViewController; // @synthesize attachmentViewController=_attachmentViewController;

+ (void)initialize;
+ (id)viewForAttachmentViewController:(id)arg1;
- (struct CGSize)naturalSize;
- (struct CGSize)desiredSizeWithMaximumWidth:(double)arg1;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)viewWillMoveToSuperview:(id)arg1;
- (id)menuForEvent:(id)arg1;
- (BOOL)shouldDisplayInline;
- (void)mouseDragged:(id)arg1;
- (void)scrollWheel:(id)arg1;
- (id)attachmentViewController;
- (void)setAttachmentViewController:(id)arg1;

@end

