/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSLevelIndicator;

@interface QuotaBar
{
    NSLevelIndicator *_levelIndicator;
}

- (id)_labelFont;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)setQuotaUsed:(unsigned long long)arg1 limit:(unsigned long long)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)arg1;

@end

