/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class ABAddressBook, NSString;

@interface RecentsSearchOperation
{
    NSString *_searchString;
    id _delegate;
    ABAddressBook *_addressBook;
}

@property(retain) ABAddressBook *addressBook; // @synthesize addressBook=_addressBook;
@property(retain) id delegate; // @synthesize delegate=_delegate;
@property(retain) NSString *searchString; // @synthesize searchString=_searchString;

- (void)main;
- (void)dealloc;
- (id)addressBook;
- (void)setAddressBook:(id)arg1;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (id)searchString;
- (void)setSearchString:(id)arg1;

@end

