/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class ActivityMonitor, NSString;

@interface RSSFeedSubscriber
{
    int _state;
    NSString *_errorString;
    ActivityMonitor *_monitor;
}

@property(readonly) BOOL isIdle;
@property(readonly) BOOL isFetching;
@property(readonly) BOOL didFail;
@property(readonly) BOOL didSucceed;
@property(retain) NSString *errorString; // @synthesize errorString=_errorString;
@property int state; // @synthesize state=_state;

+ (BOOL)isFeedURLString:(id)arg1;
+ (id)subscriber;
+ (id)keyPathsForValuesAffectingIsIdle;
+ (id)keyPathsForValuesAffectingIsFetching;
+ (id)keyPathsForValuesAffectingDidFail;
+ (id)keyPathsForValuesAffectingDidSucceed;
- (void)subscribeWithURLString:(id)arg1 title:(id)arg2 addToInbox:(BOOL)arg3 autodiscover:(BOOL)arg4 addToBookmarks:(BOOL)arg5;
- (void)subscribeWithURLStrings:(id)arg1 titles:(id)arg2 addToInbox:(BOOL)arg3 autodiscover:(BOOL)arg4 addToBookmarks:(BOOL)arg5 parent:(id)arg6;
- (void)dealloc;
- (void)cancel;
- (void)_updateState:(id)arg1 status:(id)arg2;
- (void)_workerUpdateState:(int)arg1 status:(id)arg2;
- (void)_workerSubscribeWithURLStrings:(id)arg1 titles:(id)arg2 addToInbox:(BOOL)arg3 autodiscover:(BOOL)arg4 addToBookmarks:(BOOL)arg5 parent:(id)arg6;
- (BOOL)isIdle;
- (BOOL)isFetching;
- (BOOL)didFail;
- (BOOL)didSucceed;
- (id)errorString;
- (void)setErrorString:(id)arg1;
- (int)state;
- (void)setState:(int)arg1;

@end

