/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class SegmentedToolbarItem;

@interface SegmentedToolbarItemSegmentItem
{
    SegmentedToolbarItem *parent;
    long long segmentNumber;
}

@property long long segmentNumber; // @synthesize segmentNumber;
@property SegmentedToolbarItem *parent; // @synthesize parent;

- (id)menuFormRepresentation;
- (void)setToolTip:(id)arg1;
- (void)_setToolTip:(id)arg1;
- (void)setTag:(long long)arg1;
- (void)_setTag:(long long)arg1;
- (void)setImage:(id)arg1;
- (void)setMenu:(id)arg1;
- (long long)segmentNumber;
- (void)setSegmentNumber:(long long)arg1;
- (id)parent;
- (void)setParent:(id)arg1;

@end

