/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSArray, NSWindow;

@interface SheetContext
{
    NSArray *attachments;
    NSArray *messages;
    id delegate;
    NSWindow *window;
    BOOL needsSave;
}

@property BOOL needsSave; // @synthesize needsSave;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,VneedsSave

@property(retain) NSWindow *window; // @synthesize window;
// Preceeding property had unknown attributes: N
// Original attribute string: T@"NSWindow",&,N,Vwindow

@property(retain) id delegate; // @synthesize delegate;
// Preceeding property had unknown attributes: N
// Original attribute string: T@,&,N,Vdelegate

@property(retain) NSArray *messages; // @synthesize messages;
// Preceeding property had unknown attributes: N
// Original attribute string: T@"NSArray",&,N,Vmessages

@property(retain) NSArray *attachments; // @synthesize attachments;
// Preceeding property had unknown attributes: N
// Original attribute string: T@"NSArray",&,N,Vattachments


- (void)dealloc;
- (BOOL)needsSave;
- (void)setNeedsSave:(BOOL)arg1;
- (id)window;
- (void)setWindow:(id)arg1;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (id)messages;
- (void)setMessages:(id)arg1;
- (id)attachments;
- (void)setAttachments:(id)arg1;

@end

