/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class ExpandingSplitView;

@interface SplitterAnimation
{
    ExpandingSplitView *_splitView;
    double _startPercentage;
    double _endPercentage;
}

- (id)initWithSplitView:(id)arg1 endPercentage:(double)arg2;
- (id)initWithSplitView:(id)arg1 endPercentage:(double)arg2 duration:(double)arg3;
- (id)initWithDuration:(double)arg1 animationCurve:(unsigned long long)arg2;
- (void)dealloc;
- (void)_updatePercentage;
- (void)setCurrentProgress:(float)arg1;

@end

