/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSButton, NSString, NSTextField;

@interface SpotlightBar
{
    NSString *_searchString;
    NSTextField *_textField;
    NSButton *_searchButton;
}

- (void)_setupView;
- (id)initWithFrame:(struct CGRect)arg1 searchString:(id)arg2;
- (void)dealloc;
- (void)setSearchString:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)searchButtonAction:(id)arg1;

@end

