/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface TableHeaderView
{
    BOOL _noSeparatorLines;
}

+ (id)updateHeaderViewForTableView:(id)arg1;
- (BOOL)drawsSeparatorLines;
- (void)setDrawsSeparatorLines:(BOOL)arg1;
- (BOOL)_drawingEndSeparator;

@end

