/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "MessageEditor.h"

@class MessageTextView, NSView;

@interface TextMessageEditor : MessageEditor
{
    MessageTextView *composeText;
    NSView *composeWebView;
}

- (BOOL)loadEditorNib;
- (void)readDefaultsFromDictionary:(id)fp8;
- (void)writeDefaultsToDictionary:(id)fp8;
- (id)mainContentView;
- (id)attachmentStatusNeighbourView;
- (void)insertOriginalAttachmentsWithGatekeeperApproval:(id)fp8;
- (void)insertOriginalAttachments:(id)fp8;
- (void)removeAttachments:(id)fp8;
- (void)_toggleRichSheetDidEnd:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)toggleRich:(id)fp8;
- (void)pasteAsQuotation:(id)fp8;
- (BOOL)textView:(id)fp8 doCommandBySelector:(SEL)fp12;
- (void)stayPlainOrBecomeRich:(id)fp8 returnCode:(int)fp12 contextInfo:(void *)fp16;
- (void)updateContentsToShowSignature:(id)fp8;
- (id)attachments;
- (void)appendAttributedString:(id)fp8;
- (id)attachmentContextMenu;
- (unsigned long long)textLengthEstimate;
- (id)textView:(id)fp8 willWriteSelectionToPasteboard:(id)fp12 type:(id)fp16;
- (BOOL)validateAction:(SEL)fp8 tag:(int)fp12;
- (void)updateRichTextFlag;
- (BOOL)isRichText;
- (void)setRichText:(BOOL)fp8;
- (void)appendMessageArray:(id)fp8;
- (void)addFileWrappersForPaths:(id)fp8;
- (void)redisplayChangedAttachment:(id)fp8;
- (void)forceWindowClose;
- (BOOL)backEnd:(id)fp8 shouldSaveMessage:(id)fp12;
- (void)setBackEnd:(id)fp8;
- (void)updateMainContentView;
- (void)backEnd:(id)fp8 didCompleteLoadForEditorSettings:(id)fp12;
- (Class)backEndClass;

@end

