/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "TextMessageEditor.h"

@interface TextMessageEditor (Internal)
+ (id)sharedContextMenu;
- (void)reloadContentsFromMessage:(id)fp8;
- (void)messageWillNeedRecoloring:(id)fp8;
@end

