/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "NSView.h"

@class NSTextFieldCell;

@interface TilingView : NSView
{
    float _interRowSpacing;
    void *_titlesByView;
    NSTextFieldCell *_titleCell;
    float _titleWidth;
    NSView *_viewBeingResized;
    NSView *_footerView;
    NSView *_attachedView;
    unsigned int _needTileIndex:16;
    unsigned int _needsTile:1;
    unsigned int _fixingUpKeyViews:1;
    unsigned int _UNUSED_:14;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (void)dealloc;
- (void)didAddSubview:(id)fp8;
- (void)willRemoveSubview:(id)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (BOOL)isFlipped;
- (BOOL)isOpaque;
- (void)resizeWithOldSuperviewSize:(struct _NSSize)fp8;
- (float)interRowSpacing;
- (void)setInterRowSpacing:(float)fp8;
- (void)setTitleFont:(id)fp8;
- (id)titleFont;
- (void)setTitle:(id)fp8 forView:(id)fp12;
- (id)titleForView:(id)fp8;
- (id)attachedView;
- (void)setAttachedView:(id)fp8;
- (id)footerView;
- (void)setFooterView:(id)fp8;

@end

