/*
 *     Generated by class-dump 3.0.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004 by Steve Nygard.
 */

#import "TilingView.h"

@interface TilingView (Internal)
- (void)_resizeSubviewsFromIndex:(unsigned int)fp8;
- (void)_subviewResized:(id)fp8;
- (void)_recalculateTitleWidth;
@end

