/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface ToDoDatePicker
{
}

- (void)awakeFromNib;
- (void)setFrame:(struct CGRect)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)setBounds:(struct CGRect)arg1;
- (void)setBoundsSize:(struct CGSize)arg1;

@end

