/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@interface ToDoPopUpButtonCell
{
}

- (id)_originalPopupImage;
- (id)_tintedPopupImage;
- (id)_popupImage;
- (id)_enabledTextColor;
- (id)_disabledTextColor;
- (id)initWithMenu:(id)arg1 andCell:(id)arg2;
- (double)leadingSpace;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (struct CGSize)cellSize;
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawTitleWithFrame:(struct CGRect)arg1 inView:(id)arg2;

@end

