/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSString;

@interface ToDoHeaderCell
{
    NSString *_shortCellTitle;
    NSString *_longCellTitle;
    double _widthOfLargeString;
    BOOL _usingLongString;
}

@property(copy) NSString *longCellTitle; // @synthesize longCellTitle=_longCellTitle;
@property(copy) NSString *shortCellTitle; // @synthesize shortCellTitle=_shortCellTitle;

- (id)initWithShortCellTitle:(id)arg1 longCellTitle:(id)arg2;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)dealloc;
- (id)longCellTitle;
- (void)setLongCellTitle:(id)arg1;
- (id)shortCellTitle;
- (void)setShortCellTitle:(id)arg1;

@end

