/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSImage;

@interface VerticalSplitViewHandle
{
    NSImage *image;
}

@property(readonly) double handleWidth;
@property(retain) NSImage *image; // @synthesize image;

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (double)handleWidth;
- (BOOL)isOpaque;
- (void)drawRect:(struct CGRect)arg1;
- (id)image;
- (void)setImage:(id)arg1;

@end

