/*
 *     Generated by class-dump 3.2 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

@class NSArray, NSMutableDictionary, NSString;

@interface VisibleStateObject
{
    BOOL hadSelection;
    BOOL selectionWasVisible;
    BOOL scrollerWasAtEnd;
    BOOL forceSelToVisible;
    NSString *msgIDToPin;
    double msgUpperLeft;
    NSMutableDictionary *selectedMessageIDs;
    NSArray *openThreadIDs;
}

@property(retain) NSArray *openThreadIDs; // @synthesize openThreadIDs;
// Preceeding property had unknown attributes: N
// Original attribute string: T@"NSArray",&,N,VopenThreadIDs

@property(retain) NSMutableDictionary *selectedMessageIDs; // @synthesize selectedMessageIDs;
// Preceeding property had unknown attributes: N
// Original attribute string: T@"NSMutableDictionary",&,N,VselectedMessageIDs

@property double msgUpperLeft; // @synthesize msgUpperLeft;
// Preceeding property had unknown attributes: N
// Original attribute string: Td,N,VmsgUpperLeft

@property(retain) NSString *msgIDToPin; // @synthesize msgIDToPin;
// Preceeding property had unknown attributes: N
// Original attribute string: T@"NSString",&,N,VmsgIDToPin

@property BOOL forceSelToVisible; // @synthesize forceSelToVisible;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,VforceSelToVisible

@property BOOL scrollerWasAtEnd; // @synthesize scrollerWasAtEnd;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,VscrollerWasAtEnd

@property BOOL selectionWasVisible; // @synthesize selectionWasVisible;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,VselectionWasVisible

@property BOOL hadSelection; // @synthesize hadSelection;
// Preceeding property had unknown attributes: N
// Original attribute string: Tc,N,VhadSelection


- (void)dealloc;
- (id)openThreadIDs;
- (void)setOpenThreadIDs:(id)arg1;
- (id)selectedMessageIDs;
- (void)setSelectedMessageIDs:(id)arg1;
- (double)msgUpperLeft;
- (void)setMsgUpperLeft:(double)arg1;
- (id)msgIDToPin;
- (void)setMsgIDToPin:(id)arg1;
- (BOOL)forceSelToVisible;
- (void)setForceSelToVisible:(BOOL)arg1;
- (BOOL)scrollerWasAtEnd;
- (void)setScrollerWasAtEnd:(BOOL)arg1;
- (BOOL)selectionWasVisible;
- (void)setSelectionWasVisible:(BOOL)arg1;
- (BOOL)hadSelection;
- (void)setHadSelection:(BOOL)arg1;

@end

