/*
 *     Generated by class-dump 3.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2005 by Steve Nygard.
 */

#import "WebMessageController.h"

#import "MessageContentDisplayProtocol.h"

@class NSMutableSet;

@interface WebMessageDisplay : WebMessageController <MessageContentDisplay>
{
    NSMutableSet *_gatekeeperApprovedAttachments;
}

+ (void)initialize;
+ (id)copyDocumentForMessage:(id)fp8 viewingState:(id)fp12;
- (void)dealloc;
- (void)documentResized;
- (id)contentView;
- (id)textView;
- (void)display:(id)fp8 inContainerView:(id)fp12 replacingView:(id)fp16;
- (void)prepareToRemoveView;
- (void)highlightSearchText:(id)fp8;
- (id)selectedText;
- (id)selectedWebArchive;
- (id)attachmentsInSelection;
- (id)webArchive;
- (void)adjustFontSizeBy:(int)fp8 viewingState:(id)fp12;
- (id)findTarget;
- (void)updateURLMatches:(id)fp8 viewingState:(id)fp12;
- (BOOL)scrollVerticallyBy:(float)fp8;
- (float)verticalPageScrollDistance;
- (BOOL)cachedGatekeeperApprovalStatusForAttachment:(id)fp8;
- (void)cacheGatekeeperApprovalStatus:(BOOL)fp8 forAttachment:(id)fp12;

@end

